f-header@2.0.0-beta.31 - Fix header state issues
justeattakeaway/fozzie-components pull request #111
Opened 2019-11-29 16:39 UTC by xander-marjoram

Some of the existing issues were:

- SSR warning due to the screen width being used on the server, which failed. Defaulting now to null which works.
- Being able to force the header into an opaque state even when the mobile nav was closed by tabbing all the way through it.
- Being able to close the mobile nav by mousing off it.

2019-12-02 14:34 UTC, ashleynolan submitted a review, later dismissed

2019-12-03 09:23 UTC, smilburn1990 requested changes

2019-12-03 09:23 UTC, smilburn1990 commented on packages/f-header/CHANGELOG.md
> +*November 29, 2019*
Wrong date

2019-12-03 09:23 UTC, smilburn1990 commented on packages/f-header/src/components/Navigation.vue
> +                document.documentElement.classList.toggle('is-navInView', this.navIsOpen);
Do you need `if (typeof document !== 'undefined')`?

2019-12-03 09:39 UTC, smilburn1990 approved these changes

2019-12-03 10:20 UTC, ashleynolan approved these changes

2019-12-03 10:21 UTC, merged