f-mega-modal@v0.12.1 Bug fix where modal is destroyed without closing first
justeattakeaway/fozzie-components pull request #1187
Opened 2021-08-12 14:07 UTC by timrog

__*This is the standard PR description template.*__

__*Delete the parts of this template that aren’t relevant to the current PR you are submitting – for example, you may not need to amend documentation or testing of the component.*__

---

Fixed bug where scrolling is not re-enabled if the modal is destroyed while open for whatever reason. This can happen, for example, if your confirm action routes to another page and takes the modal out of scope. The consequence is that the page will continue to be unscrollable.

---

## Browsers Tested

- [X] Chrome (latest)
- [ ] Internet Explorer 11
- [ ] Mobile (Please list device/browser – Ideally one iPhone model and one Android)

### List any other browsers that this PR has been tested in:

- [View the Browser Support Checklist](http://fozzie.just-eat.com/documentation/general/browser-support)

2021-08-24 13:26 UTC, dandel10n requested changes
LGTM, the branch just needs to be rebased and the version to be updated

2021-08-24 13:30 UTC, DamianMullins commented on packages/components/molecules/f-mega-modal/src/components/MegaModal.vue
> +        const { megaModalDocument } = this.$refs;
Probably no need to descructure the `megaModalDocument` here as it's not used anywhere else. You could just do `enableBodyScroll(this.$refs.megaModalDocument);`?

2021-09-07 10:43 UTC, dandel10n commented on packages/components/molecules/f-mega-modal/CHANGELOG.md
> +*September 1, 2021*
v0.12.1 should be added as a separate entry above 0.12.0

2021-09-09 09:04 UTC, dandel10n approved these changes

2021-09-09 09:09 UTC, DamianMullins approved these changes

2021-09-13 13:37 UTC, merged