f-header@2.0.0 - Add new theme for brand-colour header
justeattakeaway/fozzie-components pull request #129
Opened 2020-02-05 13:15 UTC by InsungMulumba

Intended for [Opening Up Home on Mobile Web work](https://jira.just-eat.net/browse/CCS-218)

Sub-task [here](https://jira.just-eat.net/browse/CCS-330)

![image](https://user-images.githubusercontent.com/48129301/73845086-c41f7680-4819-11ea-8b31-ea40079a2a33.png)

2020-02-05 13:15 UTC, InsungMulumba commented
Please do not review just yet, need to sanity check the work.

2020-02-05 13:43 UTC, InsungMulumba commented
Ready!

2020-02-05 14:12 UTC, DamianMullins commented on packages/f-header/src/components/Header.vue
> +        :class="['c-header', { 'c-header--compressedPage': showCompressedHeader }, { 'c-header--transparent c-header--gradient': showTransparentHeader }]">
The dynamic classes should all be within a single object

```js
:class="['c-header', {
    'c-header--compressedPage': showCompressedHeader,
    'c-header--transparent c-header--gradient': showTransparentHeader
}]">
```

2020-02-05 14:13 UTC, DamianMullins commented on packages/f-header/src/components/Header.vue
> +    .c-header--compressedPage.c-header--gradient::before {
Do you need to do this? Is there a case where you'd have the transparent header and the red header at the same time?

2020-02-05 14:14 UTC, DamianMullins commented on packages/f-header/src/components/Header.vue
> +        showCompressedHeader: {
Maybe something like `showBrandColourHeader` or similar might better describe what this prop does?

2020-02-05 14:16 UTC, InsungMulumba commented on packages/f-header/src/components/Header.vue
> +    .c-header--compressedPage.c-header--gradient::before {
is-Transparent also sets the navigation button to the same colour as the logo, so my thinking was to set it to `true`.
Otherwise it will default to blue as shown below
![image](https://user-images.githubusercontent.com/48129301/73849541-0482f280-4822-11ea-8b37-c472e9f53d49.png)

2020-02-05 14:17 UTC, InsungMulumba commented on packages/f-header/src/components/Header.vue
> +        showCompressedHeader: {
I'm unsure about the naming myself to be honest, this was suggested by @kevinrodrigues but I'm happy to refactor

2020-02-05 14:18 UTC, InsungMulumba commented on packages/f-header/src/components/Header.vue
> +        :class="['c-header', { 'c-header--compressedPage': showCompressedHeader }, { 'c-header--transparent c-header--gradient': showTransparentHeader }]">
will do

2020-02-05 14:57 UTC, DamianMullins commented on packages/f-header/src/components/Header.vue
> +    .c-header--compressedPage.c-header--gradient::before {
Can you not update so that new prop makes the menu icon white as well? Seems weird that you'd apply the transparent prop to make the icon white.

2020-02-05 15:59 UTC, InsungMulumba commented on packages/f-header/src/components/Header.vue
> +    .c-header--compressedPage.c-header--gradient::before {
I've looked deeper into f-header and the transparent prop also [renders the logo white ](https://github.com/justeat/fozzie-components/blob/403537f37e24a795b3a3dcad5aeeff3da24d8661/packages/f-header/src/components/Logo.vue#L122)

@DamianMullins am I right to think the process from here is to add the `showCompressedHeader` prop to `Logo.vue` and `Navigation.vue`?

2020-02-05 16:21 UTC, DamianMullins commented on packages/f-header/src/components/Header.vue
> +    .c-header--compressedPage.c-header--gradient::before {
Looks like it, and then add a style which makes the icon background white for a new modifier class related to the new prop.

2020-02-06 10:55 UTC, ashleynolan commented on packages/f-header/src/components/Header.vue
> +    .c-header--brandColour.c-header--gradient::before {
Will `showTransparentHeader` and `showBrandColourHeader` ever be used together like this? (seems like they shouldn't be?)

2020-02-06 10:57 UTC, InsungMulumba commented on packages/f-header/src/components/Header.vue
> +    .c-header--brandColour.c-header--gradient::before {
Damian raised the same point above, I'm working on adding the new prop to `Logo.vue` and `Navigation.vue`, and then I will revert this

2020-02-06 13:42 UTC, ashleynolan commented on packages/f-header/src/components/Logo.vue
> +                'c-icon-je--transparentBg': showBrandColourHeader
Think `showBrandColourHeader` is a bit of a confusing name (I'm not quite sure what state this refers to – is it when we want the red background on the header?).

Would be good to put these class definitions across multi-lines too, as it's hard to see the different statements atm (which may be the issue).

Also, feels strange to have two props for what could essentially be controlled via one prop called something like `theme`. If we had a `theme` prop, we could pass in `transparent` or `default` for the different styles potentially, as I'm guessing we won't ever want them to be both switched on at once?

2020-02-06 13:48 UTC, InsungMulumba commented on packages/f-header/src/components/Logo.vue
> +                'c-icon-je--transparentBg': showBrandColourHeader
I've refactored the name a few times now, personally I'm unsure what the best name for this is. 
@DamianMullins @kevinrodrigues @SachaZvetelman any thoughts?

The class definition was on one line before this PR! But I agree it's a bit confusing, I can split it up.

I will need help for your last point about a new prop, can you send a small code snippet of what you mean?

2020-02-06 13:59 UTC, ashleynolan commented on packages/f-header/src/components/Logo.vue
> +                'c-icon-je--transparentBg': showBrandColourHeader
Yeh – I'd be happy to pair on this if it'd be easier?

So what I was thinking was rather than having `isTransparent` and `showBrandColourHeader` the header could just accept a `headerTheme` prop which takes a number of defined values. Otherwise everytime we want to change the theme style of the header, we'd need to add a new prop, which doesn't scale very well.

Like I say – happy to pair on this when you have some time tomorrow?

2020-02-06 14:03 UTC, ashleynolan commented on packages/f-header/src/components/Logo.vue
> +                'c-icon-je--transparentBg': showBrandColourHeader
Also see what you mean we class definition being on one line before, but as this is getting longer it's getting too verbose to see easily what's going on:

```js
:class="[
    iconClassName,
    isTransparent && iconComponent === 'je-logo' ? 'c-icon-je--transparentBg' : '',
    {
        'c-icon-je--transparentBg': showBrandColourHeader
    }]"
```

2020-02-06 16:47 UTC, DamianMullins commented on packages/f-header/src/components/Logo.vue
> +                isTransparent && iconComponent === 'je-logo' ? 'c-icon-je--transparentBg' : '',
Shouldn't really have ternaries in here as you're mixing them with the standard Vue way of applying classes. You should be able to do this?

```js
:class="[
    'c-logo-img',
    iconClassName,
    {
        'c-icon-je--transparentBg': isTransparent && iconComponent === 'je-logo'
        'c-icon-je--transparentBg': showBrandColourHeader
}]"
```

Also, probably best to move that `isTransparent && iconComponent === 'je-logo'` check into a computed prop/

2020-02-10 10:16 UTC, ashleynolan commented on packages/f-header/src/components/Logo.vue
> +        whiteLogo () {
If this is returning true/false, would be better named `isWhiteLogo`

2020-02-10 11:37 UTC, InsungMulumba commented
TO-DO: Refactor Tests

2020-02-10 17:52 UTC, InsungMulumba commented on packages/f-header/src/components/Header.vue
> +            'c-header--red': showRedBackgroundHeader,
I believe this name is suitable as the computed prop is explicitly for **red** theme, similar to that for the transparent theme just above

2020-02-11 10:43 UTC, ashleynolan commented on packages/f-header/src/components/Header.vue
> +    .c-header.c-header--red {
Do you need the `.c-header` part of this selector? I would have thought it should still take affect without this (so just `.c-header--red {`

2020-02-11 10:47 UTC, ashleynolan commented on packages/f-header/src/components/Navigation.vue
> +                'c-logo--brandColour': showBrandColourHeader
Where does `showBrandColourHeader` come from? (not sure if I'm being dull, but I can't see it as a `prop` or `data` in this file?)

2020-02-11 10:48 UTC, ashleynolan commented on packages/f-header/package.json
> +  "version": "v2.0.0",
Can you update this to just be "2.0.0"?

2020-02-11 10:54 UTC, ashleynolan commented on packages/f-header/src/components/Header.vue
> +        showRedBackgroundHeader () {
Rather than have a function that returns `true`/`false` here for red, you could return the classname itself for the header background?

So that way you would return `c-header--red` (also makes it a bit more scalable should we need more different colours in future).

So something like this:

```js
headerBgClass () {
  if (this.headerBackgroundTheme === 'red') {
    return 'c-header--red';
  }
}
```

2020-02-11 11:33 UTC, InsungMulumba commented on packages/f-header/src/components/Navigation.vue
> +                'c-logo--brandColour': showBrandColourHeader
Prop added :)

2020-02-11 11:35 UTC, InsungMulumba commented on packages/f-header/src/components/Header.vue
> +    .c-header.c-header--red {
c-header has it's own background-colour that takes precedence otherwise

2020-02-11 11:36 UTC, InsungMulumba commented on packages/f-header/src/components/Header.vue
> +        showRedBackgroundHeader () {
I will change this and do the same for the prop I just introduced in `Navigation.vue` (I committed that before seeing this comment)

2020-02-12 14:07 UTC, simonsandersje submitted a review, later dismissed

2020-02-12 14:11 UTC, smilburn1990 submitted a review, later dismissed

2020-02-12 15:00 UTC, ashleynolan commented on packages/f-header/src/components/Header.vue
> +    .c-header.c-header--red {
It should be the same specificity, and as this selector comes after `c-header` this style should take precedence.  If it's not, then might be something funky going on – does this definitely not work?

2020-02-12 15:03 UTC, InsungMulumba commented on packages/f-header/src/components/Header.vue
> +    .c-header.c-header--red {
I'll try again

2020-02-12 15:03 UTC, ashleynolan commented on packages/f-header/src/components/Logo.vue
> +            return (this.headerBackgroundTheme === 'transparent' || this.headerBackgroundTheme === 'red') && this.theme === 'je' ? 'c-icon-je--alt' : '';
Should likely rename this function as it implies that it's returning a `Boolean` (when it's actually returning a string for the class?).

`logoColourModifier` might make sense?

2020-02-12 15:05 UTC, ashleynolan commented on packages/f-header/src/components/Navigation.vue
> +        NavToggleThemeClass () {
should be `navToggleThemeClass` (so lowercase first letter)

2020-02-12 15:06 UTC, ashleynolan requested changes
Couple of super small changes – then looks good

2020-02-12 15:25 UTC, InsungMulumba commented on packages/f-header/src/components/Header.vue
> +    .c-header.c-header--red {
Hey @ashleynolan  So I think the reason I can't get it locally is because I don't know how to access `packages/f-header/src/components/Header.vue` locally in Homeweb. (it's not in my node_modules) I'll revert this change, and it should propagate through. :)

2020-02-12 16:03 UTC, InsungMulumba commented on packages/f-header/src/components/Logo.vue
> +            return (this.headerBackgroundTheme === 'transparent' || this.headerBackgroundTheme === 'red') && this.theme === 'je' ? 'c-icon-je--alt' : '';
This is done, not sure why it isn't flagging as `outdated`

2020-02-13 09:52 UTC, ashleynolan submitted a review, later dismissed

2020-02-13 10:46 UTC, asherstoppard approved these changes

2020-02-13 11:20 UTC, smilburn1990 approved these changes

2020-02-13 11:22 UTC, merged