f-button@3.0.3 - f-seleton-loader@2.1.0 - f-user-message@3.1.0 - Design team feedback
justeattakeaway/fozzie-components pull request #1361
Opened 2021-10-15 13:58 UTC by dandel10n

## f-button@3.0.3

### Changed
- Each button size vertical padding reduced by 1px to make button height 56px/48px/40px/32px instead of 58px/50px/42px/34px.

## f-seleton-loader@2.1.0

### Changed
- Rounded corners for all the skeleton blocks.

Before:
![Screenshot 2021-10-15 at 14 56 32](https://user-images.githubusercontent.com/19548183/137499159-766c2466-211c-486a-abb5-64b99ea5d023.png)

After:
![Screenshot 2021-10-15 at 14 55 22](https://user-images.githubusercontent.com/19548183/137499135-b80a8c5b-85dd-4f2e-9bfd-2fd14bc4c362.png)
f-user-message@3.1.0

### Changed
- Background and text colour to be in line with default warning message.

Before:
![Screenshot 2021-10-15 at 14 57 48](https://user-images.githubusercontent.com/19548183/137499279-93c72fe9-2e9a-4d97-a405-f9119e4f4f47.png)

After:
![Screenshot 2021-10-15 at 14 54 55](https://user-images.githubusercontent.com/19548183/137498940-a4ba742c-db34-44f5-a9c9-5df46ac15dda.png)

2021-10-15 14:03 UTC, 1itvinka approved these changes

2021-10-15 14:33 UTC, DamianMullins approved these changes

2021-10-16 11:12 UTC, ashleynolan requested changes

2021-10-16 11:12 UTC, ashleynolan commented on packages/components/atoms/f-button/CHANGELOG.md
> +- Each button size vertical padding reduced by 1px to make button height 56px/48px/40px/32px instead of 58px/50px/42px/34px.
I'm just checking storybook – it looks like the large button already is 56px (and then it has a 1px transparent border, which means devtools says it has a 58px height).

I think we've been back and forth a few times on button and form-field heights with design in the past, so probably worth catching up about this (and probably writing down whatever we do somewhere, cause I always forget!)

2021-10-16 11:13 UTC, ashleynolan commented
I would likely break these changes out into separate PRs per component. Just because otherwise, any comments on one of the component changes will hold up the others going through.

2021-10-18 09:16 UTC, closed without merging