f-navigation-links@v0.2.0 - Added styling and tests
justeattakeaway/fozzie-components pull request #1362
Opened 2021-10-15 16:54 UTC by oliversweb

### Added
- Component layout and styling

___

![image](https://user-images.githubusercontent.com/1353060/137524511-47b4d07d-50c8-444c-ab88-faf1837c3144.png)

2021-10-16 08:22 UTC, ashleynolan requested changes

2021-10-16 08:22 UTC, ashleynolan commented on packages/components/molecules/f-navigation-links/src/components/NavigationLinks.vue
> +                    :class="[$style['c-hightlighted-link']]">
I'd recommend adding classes to hook onto the elements for the styling – it just makes the styles less brittle if the markup ever were to change and it also helps define the hierarchy between the styles really clearly.

Also – do you need the outer div? I think you could just remove that and have the `ul` at the root.

So for this, I'd structure it something like this:

```
<ul class="c-navigationLinks">
    <li class="c-navigationLinks-item">
        <span
            if…
            class="c-navigationLinks-link c-navigationLinks-link--active">
            text
        </span>
        <a class="c-navigationLinks-link">
            text
        </a>
    </li>
</ul>
```

I think then in your styles below you should just be able to simplify the styles between the `span` and `a` as they have a shared classname, and then just add the `active` (or `highlight`) styles onto the modifier classname.

Happy to chat this through on Monday too

2021-10-16 08:26 UTC, ashleynolan commented on packages/components/molecules/f-navigation-links/src/components/NavigationLinks.vue
> +        a {
Atm, it doesn't look like there would ever be an `a` inside the `c-hightlighted-link` tag? It looks like an either or based on the if?

2021-10-16 08:30 UTC, ashleynolan commented on packages/components/molecules/f-navigation-links/src/components/_tests/NavigationLinks.test.js
> +    });
Not sure if this is planned for a future PR, but it would be good to have some tests around what happens if the data passed into the prop is of an incorrect structure. So what would happen if I passed empty or no values for `url`, `name` or `selected` (what are the valid states and default states?).

2021-10-18 13:55 UTC, SachaZvetelman reviewed
Looking good! Some minor comments only :)

2021-10-18 13:55 UTC, SachaZvetelman commented on packages/components/molecules/f-navigation-links/README.md
> +      Id: 'link1',            // Test Data Id
`Id` should be `id` 👍

2021-10-18 13:55 UTC, SachaZvetelman commented on packages/components/molecules/f-navigation-links/src/components/NavigationLinks.vue
> +            v-for="({ Id, url, name, selected }, i) in links"
Same as above, it should be `id`.

2021-10-18 13:55 UTC, SachaZvetelman commented on packages/components/molecules/f-navigation-links/src/components/NavigationLinks.vue
> +            :key="`${i}_link`"
I might be wrong, but I think `:key="i"` should be sufficient.

2021-10-18 13:55 UTC, SachaZvetelman commented on packages/components/molecules/f-navigation-links/src/components/NavigationLinks.vue
> +            font-weight: $font-weight-bold;
Where possible, can you please use `spacing()` to define margins and paddings?

2021-10-18 13:55 UTC, SachaZvetelman commented on packages/components/molecules/f-navigation-links/src/components/_tests/NavigationLinks.test.js
> +        expect(wrapper.props().links).toEqual(propsData.links);
I personally don't see the value of this assertion here, since we're basically testing that Vue knows how to receive `props`. But I might be wrong, so I'm keen to get your opinion as well on this.

2021-10-18 14:24 UTC, DamianMullins commented on packages/components/molecules/f-navigation-links/src/components/NavigationLinks.vue
> +            :key="`${i}_link`"
Using `id` would probably be best (as long as it's unique), that way if the number or order of items in the array changes then Vue will be able to use that to better update the DOM elements. By using the index Vue has no way of telling which elements can stay the same etc.

2021-10-18 14:25 UTC, DamianMullins commented on packages/components/molecules/f-navigation-links/src/components/NavigationLinks.vue
> +            :key="`${i}_link`"
Also, is the casing right for `id`? I see @SachaZvetelman mentioned above about casing of `id`?

2021-10-18 15:17 UTC, ashleynolan commented on packages/components/molecules/f-navigation-links/README.md
> +None
I'd just delete this section if there aren't any events.

2021-10-18 15:17 UTC, ashleynolan commented on packages/components/molecules/f-navigation-links/src/components/NavigationLinks.vue
> +            :class="$style['c-navigationLink-item']">
```suggestion
            :class="$style['c-navigationLinks-item']">
```

2021-10-18 15:17 UTC, ashleynolan commented on packages/components/molecules/f-navigation-links/src/components/NavigationLinks.vue
> +                :class="[$style['c-navigationLink-link'], $style['c-navigationLink--active']]">
So the base class is `c-navigationLinks-link` here and the modifier is indicated by the double dash which would be the active state `c-navigationLinks-link--active`. (Just a naming thing but can be easier to explain sometimes in person, so give me a shout if this doesn't make any sense!)

```suggestion
                :class="[$style['c-navigationLinks-link'], $style['c-navigationLinks-link--active']]">
```

2021-10-18 15:17 UTC, ashleynolan commented on packages/components/molecules/f-navigation-links/src/components/NavigationLinks.vue
> +                :class="$style['c-navigationLink-link']">
```suggestion
                :class="$style['c-navigationLinks-link']">
```

2021-10-18 15:17 UTC, ashleynolan commented on packages/components/molecules/f-navigation-links/src/components/NavigationLinks.vue
> +}
Better not to nest these as it will just make the styles more specific. So you could just do:
```suggestion
}

.c-navigationLinks-item {
    display: inline-block;
    width: 100%;
}

.c-navigationLinks-link {
    display: block;
    padding: spacing() 0 spacing() spacing(x2);
    border-left: 2px solid $color-grey-30;
    color: $color-grey;
 
    &:focus,
    &:hover {
        border-left: 2px solid $color-orange;
        text-decoration: none;
    }
 }

.c-navigationLinks-link--active {
        border-left: 2px solid $color-orange;
        font-weight: $font-weight-bold;
    }
}

```

2021-10-18 16:24 UTC, ashleynolan commented on packages/components/molecules/f-navigation-links/src/components/NavigationLinks.vue
> +                :class="[$style['c-navigationLinks-link'], $style['c-navigationLinks--active']]">
Missed the naming change to the second class:

```suggestion
                :class="[$style['c-navigationLinks-link'], $style['c-navigationLinks-link--active']]">
```

2021-10-18 16:26 UTC, ashleynolan commented on packages/components/molecules/f-navigation-links/src/components/NavigationLinks.vue
> +    }
This block can be unnested like the code block I posted before? (and rather than use `li`, can hook onto `c-navigationLinks-item`)

2021-10-19 07:41 UTC, SachaZvetelman submitted a review, later dismissed
Approved with some minor comments 👍

2021-10-19 07:41 UTC, SachaZvetelman commented on packages/components/molecules/f-navigation-links/src/components/NavigationLinks.vue
> +            :key="i"
I think in the end @DamianMullins recommended using the `id` instead, as long as it's unique, which I think was a good suggestion from him.

2021-10-19 07:41 UTC, SachaZvetelman commented on packages/components/molecules/f-navigation-links/src/components/NavigationLinks.vue
> +.c-navigationLinks-link {
Nit: empty line here, please :)

2021-10-19 07:41 UTC, SachaZvetelman commented on packages/components/molecules/f-navigation-links/src/components/NavigationLinks.vue
> +.c-navigationLinks-link--active {
Nit: empty line here, please :)

2021-10-19 08:21 UTC, oliversweb commented on packages/components/molecules/f-navigation-links/src/components/NavigationLinks.vue
> +            :key="i"
No guarantee as it's supplied by the consumer

2021-10-19 08:31 UTC, SachaZvetelman approved these changes

2021-10-19 08:32 UTC, SachaZvetelman approved these changes

2021-10-19 08:51 UTC, oliversweb commented on packages/components/molecules/f-navigation-links/src/components/_tests/NavigationLinks.test.js
> +    });
I could add a prop validator on a later pr 👍

2021-10-20 10:24 UTC, ashleynolan approved these changes

2021-10-20 11:55 UTC, merged