f-checkout@2.6.0 - handle event logging
justeattakeaway/fozzie-components pull request #1364
Opened 2021-10-18 08:58 UTC by FayeCarter

- `handleEventLogging` method to handle events and logging.

2021-10-18 09:48 UTC, charliearlie submitted a review, later dismissed

2021-10-18 14:39 UTC, charliearlie submitted a review, later dismissed

2021-10-18 14:42 UTC, BanksySan requested changes

2021-10-18 14:42 UTC, BanksySan commented on packages/components/organisms/f-checkout/src/components/Checkout.vue
> +                if (!data && !error) {
Could be easier to read if we invert the `if` to `data || error`.
_Generally_ you go for the positive option, then else the negative option.

2021-10-18 14:42 UTC, BanksySan commented on packages/components/organisms/f-checkout/src/components/Checkout.vue
> +                this.handleEventLogging('CheckoutGetSuccess');
Could we use the `EventNames` instead of a magic string?

2021-10-18 14:42 UTC, BanksySan commented on packages/components/organisms/f-checkout/src/components/Checkout.vue
>          async lookupGeoLocation () {
There's no `await` in this `async`.

2021-10-18 14:42 UTC, BanksySan commented on packages/components/organisms/f-checkout/src/log-events.js
> +    CheckoutSuccess: {
Can we use the `EventNames` here?

2021-10-18 14:46 UTC, FayeCarter commented on packages/components/organisms/f-checkout/src/components/Checkout.vue
>          async lookupGeoLocation () {
https://github.com/justeat/fozzie-components/pull/1364/files/c7262a16a4d4ea4ca04787ed67a80280f9d2b369#diff-3f7bda367e6ae2f5c141559c1aec5722d6606ee4d895f7d44e9837c20f7efb3cR895

2021-10-19 09:54 UTC, BanksySan approved these changes

2021-10-19 10:00 UTC, BanksySan approved these changes

2021-10-19 10:09 UTC, charliearlie approved these changes

2021-10-19 10:09 UTC, merged