f-button@3.2.0 - change of button height
justeattakeaway/fozzie-components pull request #1372
Opened 2021-10-18 15:22 UTC by dandel10n

### Changed
- Button border style definition moved to button types.
- Each button size vertical padding reduced by 1px to make button height 56px/48px/40px/32px instead of 58px/50px/42px/34px.

### Removed
- Outline css styles as focus styles applied with `box-shadow`.

2021-10-20 08:16 UTC, FayeCarter submitted a review, later dismissed

2021-10-20 11:41 UTC, ashleynolan requested changes

2021-10-20 11:41 UTC, ashleynolan commented on packages/components/atoms/f-button/CHANGELOG.md
> +- Each button size vertical padding reduced by 1px to make button height 56px/48px/40px/32px instead of 58px/50px/42px/34px.
Just re-adding my comment from the other PR 😆 

> I'm just checking storybook – it looks like the large button already is 56px (and then it has a 1px transparent border, which means devtools says it has a 58px height).

> I think we've been back and forth a few times on button and form-field heights with design in the past, so probably worth catching up about this (and probably writing down whatever we do somewhere, cause I always forget!)

2021-10-20 11:43 UTC, dandel10n commented on packages/components/atoms/f-button/CHANGELOG.md
> +- Each button size vertical padding reduced by 1px to make button height 56px/48px/40px/32px instead of 58px/50px/42px/34px.
I now changed the way we add borders to have consistent height between buttons without visual borders and with visual border (outline button).

2021-10-21 08:20 UTC, ashleynolan commented on packages/components/atoms/f-button/CHANGELOG.md
> +- Each button size vertical padding reduced by 1px to make button height 56px/48px/40px/32px instead of 58px/50px/42px/34px.
Have caught up with @dandel10n now – going to move the background and border style setting into a mixin that is commented so that it's a bit more manageable (and so we can comment it for anyone coming to these styles)

2021-10-22 14:47 UTC, ashleynolan submitted a review, later dismissed

2021-10-25 08:19 UTC, xander-marjoram commented on packages/components/atoms/f-button/CHANGELOG.md
> +- Button border style definition moved to button types. Introdused `background-color()` mixin to apply the same colour for the background and for the border colour.
Nit: typo
```suggestion
- Button border style definition moved to button types. Introduced `background-color()` mixin to apply the same colour for the background and for the border colour.
```

2021-10-25 08:20 UTC, xander-marjoram commented on packages/components/atoms/f-button/src/assets/scss/common.scss
> +// mixin to aply the same colour for the border and for background of the button
Nit: typo
```suggestion
// mixin to apply the same colour for the border and for background of the button
```

2021-10-25 08:21 UTC, xander-marjoram commented on packages/components/atoms/f-button/CHANGELOG.md
> +*October 22, 2021*
(Might as well bump the date while you're at it too 😄)

2021-10-25 08:46 UTC, xander-marjoram approved these changes

2021-10-25 09:12 UTC, FayeCarter approved these changes

2021-10-25 09:12 UTC, merged