fozzie-components@5.3.2 - Refactored wdio config #globalconfig
justeattakeaway/fozzie-components pull request #1391
Opened 2021-10-25 12:20 UTC by LTurns

Sorry in advance for the amount of files changed - lots of small script changes in the package.jsons

### Changed
- wdio configuration for component, visual and a11y tests
- allure script in `wdio-shared.conf.js` and `package.json`
- updated generator to reflect above changes

2021-10-25 14:46 UTC, siggerzz commented on .gitignore
>  !**/test/results/allure/README.md
Can the `results/allure/README.md` reference be removed?

2021-10-25 14:48 UTC, siggerzz commented on packages/tools/generator-component/generators/app/templates/__package__.json
>      "report:test-component:chome": "cross-env-shell JE_ENV=ci TEST_TYPE=component ALLURE_REPORTER=true wdio ../../../../wdio-chrome.conf.js && yarn:allure:open",
can `report:test-component:chrome` be removed?

2021-10-25 14:49 UTC, LTurns commented on .gitignore
>  !**/test/results/allure/README.md
yep

2021-10-25 14:50 UTC, siggerzz commented on test/configuration/circleci.config.js
> +        timeout: 60000,
Maybe change to `timeout: parseInt(process.env.WDIO_TIMEOUT, 10) || 60000`

that way we can control from CI without having to make code changes if CI tests are being flaky.

2021-10-25 14:50 UTC, siggerzz commented on test/configuration/circleci.config.js
> +        waitforTimeout: 10000
ditto, but make the env var `process.env.WDIO_WAITFOR_TIMEOUT`

2021-10-25 14:50 UTC, LTurns commented on packages/tools/generator-component/generators/app/templates/__package__.json
>      "report:test-component:chome": "cross-env-shell JE_ENV=ci TEST_TYPE=component ALLURE_REPORTER=true wdio ../../../../wdio-chrome.conf.js && yarn:allure:open",
confusingly I've done that in the other PR 😄

2021-10-25 14:52 UTC, LTurns commented on packages/tools/generator-component/generators/app/templates/__package__.json
>      "report:test-component:chome": "cross-env-shell JE_ENV=ci TEST_TYPE=component ALLURE_REPORTER=true wdio ../../../../wdio-chrome.conf.js && yarn:allure:open",
https://github.com/justeat/fozzie-components/pull/1392/files#diff-5b8553d5d0247cf469187a72a32169baad458ae4422d84172044a55024966396L43

2021-10-25 14:52 UTC, siggerzz commented on test/configuration/circleci.config.js
> +        desktopHugeWidth: 1280,
Maybe change to:


```
percy: {
    viewports: {
        mobile: [414],
        desktop: [1280]
    }
}
```

2021-10-25 14:53 UTC, siggerzz commented on test/configuration/local.config.js
> +    percy: {
ditto

2021-10-25 14:54 UTC, LTurns commented on test/configuration/circleci.config.js
> +        timeout: 60000,
awesome, will do

2021-10-25 14:54 UTC, siggerzz commented on test/configuration/shared.config.js
> +            'test/component/*.component.desktop.spec.js',
Refactor to `test/component/*.component.spec.js` once your other PR gets merged.

2021-10-25 14:57 UTC, siggerzz commented on test/configuration/shared.config.js
> +    ...(TEST_TYPE === 'visual' && isDesktop ? {
You don't need the `isMobile` / `isDesktop` check now. simply change to:

```
    ...(TEST_TYPE === 'visual' ? {
         name: 'visual',
         services: ['chromedriver', 'percy'],
         specs: ['test/visual/*.visual.*.spec.js']
     } : {})
```

2021-10-25 14:58 UTC, siggerzz requested changes
Few minor comments!

2021-10-25 14:58 UTC, siggerzz commented on packages/tools/generator-component/generators/app/templates/__package__.json
>      "report:test-component:chome": "cross-env-shell JE_ENV=ci TEST_TYPE=component ALLURE_REPORTER=true wdio ../../../../wdio-chrome.conf.js && yarn:allure:open",
Sweet, that PR should get merged first, so no worries!

2021-10-25 14:59 UTC, siggerzz commented on .gitignore
>  !**/test/results/allure/README.md
Make sure to move the README.md into `allure-results` too please!

2021-10-27 09:30 UTC, JoshuaNg2332 submitted a review, later dismissed

2021-10-27 13:33 UTC, JoshuaNg2332 submitted a review, later dismissed

2021-10-27 13:37 UTC, siggerzz commented on package.json
> +    "allure:open": "allure generate test/results/allure-results --clean && yarn allure:clean && allure open",
Do we need `allure:clean` if we're passing the `--clean` argument?

2021-10-27 13:57 UTC, LTurns commented on package.json
> +    "allure:open": "allure generate test/results/allure-results --clean && yarn allure:clean && allure open",
yep the `--clean` only removes historic allure files where as `allure:clean` removes historic and new so none remain once the report is opened. Unfortunately allure scripts require the `--clean` so we need both for the time being

2021-10-27 14:04 UTC, siggerzz commented on wdio-shared.conf.js
> +            browser.addCommand('percyScreenshot', (screenshotName, featureType) => {
Should be able to refactor to this, or something similar:


```
            browser.addCommand('percyScreenshot', (screenshotName, featureType) => {
            
            const formattedFeatureType = featureType.toLowerCase();

            if(formattedFeatureType !== 'mobile' || formattedFeatureType !== 'desktop)
            {
                throw new Error(`Feature type ${formattedFeatureType} is not supported. Please use 'mobile' or 'desktop`);
            }

                 browser.call(async () => {
                     await percySnapshot(`${screenshotName} - ${featureType}`, {
                         widths: configuration.percy.viewports[formattedFeatureType]
                     });
                 });
             });
```

2021-10-27 14:05 UTC, siggerzz requested changes
Minor comments. Looking way better than before though!

2021-10-27 14:06 UTC, LTurns commented on wdio-shared.conf.js
> +            browser.addCommand('percyScreenshot', (screenshotName, featureType) => {
awesome, thank youu

2021-11-11 14:32 UTC, xander-marjoram commented on test/configuration/shared.config.js
> +    } : []),
It may still work but it should probably be like this:
```suggestion
    } : {}),
```

2021-11-11 14:43 UTC, xander-marjoram reviewed
A few tiny things

2021-11-11 14:43 UTC, xander-marjoram commented on test/configuration/configuration-helper.js
> +const fileName = CIRCLECI ? 'circleci' : 'local';
Probably best to have your imports at the top, and we don't seem to be using the variable anywhere else so it's not necessary.
```suggestion
const video = require('wdio-video-reporter');

const fileName = process.env.CIRCLECI ? 'circleci' : 'local';
```

2021-11-11 14:43 UTC, xander-marjoram commented on test/configuration/shared.config.js
> +            'test/accessibility/axe-accessibility.spec.js']
Nit:
```suggestion
        specs: VS_DEBUGGER ? [SPEC_FILE] : [
            'test/accessibility/axe-accessibility.spec.js'
        ]
```
or
```suggestion
        specs: VS_DEBUGGER ? [SPEC_FILE] : ['test/accessibility/axe-accessibility.spec.js']
```

2021-11-11 16:58 UTC, xander-marjoram submitted a review, later dismissed

2021-11-12 11:50 UTC, xander-marjoram approved these changes, later dismissed

2021-11-12 14:18 UTC, xander-marjoram commented
GitHub doesn't seem to think so yet, but I reckon this will need updating with master because I think I pinched v5.3.1 with #1469

2021-11-12 15:01 UTC, xander-marjoram approved these changes

2021-11-18 11:59 UTC, siggerzz approved these changes

2021-11-18 12:00 UTC, merged