f-user-message@v0.1.0 - Initial Component implementation
justeattakeaway/fozzie-components pull request #140
Opened 2020-02-17 16:18 UTC by zlatinivanov-je

Adds `f-user-message` vue component

---

## UI Review Checks

<img width="724" alt="Screenshot 2020-03-27 at 10 39 44" src="https://user-images.githubusercontent.com/26770126/77749598-317da580-701a-11ea-8b1b-468821760b02.png">

- [x] README and/or UI Documentation has been [created|updated]
- [x] Unit tests have been [created|updated]
- [ ] This code has been checked with regard to [our accessibility standards](http://fozzie.just-eat.com/documentation/general/accessibility/checklist)

## Browsers Tested

- [x] Chrome (latest)
- [ ] Internet Explorer 11
- [ ] Mobile (Please list device/browser – Ideally one iPhone model and one Android)

### List any other browsers that this PR has been tested in:

- [View the Browser Support Checklist](http://fozzie.just-eat.com/documentation/general/browser-support)

2020-02-18 14:07 UTC, asherstoppard commented on packages/f-user-message/src/components/UserMessage.vue
> +// import sharedServices from '@justeat/f-services';
Could these commented lines be removed prior to merging

2020-02-18 14:10 UTC, asherstoppard commented on packages/f-user-message/src/components/tests/UserMessage.test.js
> +jest.mock('axios');
I'd recommend using [axios mock adapter](https://www.npmjs.com/package/axios-mock-adapter) here as it gives you a bit more flexibility on response types/errors/timeouts etc.

2020-02-18 14:13 UTC, asherstoppard commented on packages/f-user-message/src/components/UserMessage.vue
> +                this.userMessageEnabled = true;
Just looking over the data model below. Should `userMessageEnabled` be explicit here or pulled from `UserMessageApi`?

2020-02-18 15:19 UTC, xander-marjoram commented on packages/f-user-message/src/components/UserMessage.vue
> +                this.userMessageEnabled = true;
We probably could just pass it back from the API, but the API does the check to see whether or not the message is enabled, returning either the message (if it's present and enabled) or an empty string, so we only need to check for that. If we reach this point in the code then we can show the banner.

I guess it comes down to where we feel like the logic should live, in the API or in the component?

2020-02-18 15:56 UTC, zlatinivanov-je commented on packages/f-user-message/src/components/UserMessage.vue
> +// import sharedServices from '@justeat/f-services';
Thank you for your review, first of all. Those will be removed, however I am bit unclear on how to approach the `locale` and `theme` of the component. Hence why I left those here as a reminder.

2020-02-18 16:07 UTC, zlatinivanov-je commented on packages/f-user-message/src/components/UserMessage.vue
> +                this.userMessageEnabled = true;
I can change to `null` initially if it makes more sense.

2020-02-18 16:44 UTC, asherstoppard commented on packages/f-user-message/src/components/UserMessage.vue
> +// import sharedServices from '@justeat/f-services';
Ah ok no worries :+1:

2020-02-19 16:47 UTC, ashleynolan reviewed
Looks good – couple of comments from me, but nothing major at first glance.

Happy to go through anything you want to tomorrow (like the `locale/theme` bits?

2020-02-19 16:47 UTC, ashleynolan commented on packages/f-user-message/LICENSE
> +Copyright 2019 Just Eat Holding Ltd
Should be `2020`

2020-02-19 16:47 UTC, ashleynolan commented on packages/f-user-message/README.md
> +[![Build Status](https://travis-ci.org/justeat/f-user-message.svg)](https://travis-ci.org/justeat/f-user-message)
Imagine we don't need this. We use circleCI in this repo, so likely will need to replace this bade with a CircleCI Badge at some point.

2020-02-19 16:47 UTC, ashleynolan commented on packages/f-user-message/package.json
> +  "version": "0.1.0-beta",
I'd just go for `0.1.0` for now (and then move it to `v1.0.0` once you're happy with it.

2020-02-19 16:47 UTC, ashleynolan commented on packages/f-user-message/package.json
> +    "node": ">=8.0.0"
Can bump this to `>=10.0.0` (need to update the other `package.json` files – I'll look to do this)

2020-02-19 16:47 UTC, ashleynolan commented on packages/f-user-message/package.json
> +    "lint": "vue-cli-service lint --fix",
Can you split this into two script tasks (I'm just updating this on otehr components. So should be:

```js
"lint": "vue-cli-service lint",
"lint:fix": "yarn lint --fix"
```

2020-02-19 16:47 UTC, ashleynolan commented on packages/f-user-message/src/components/UserMessage.vue
> +// import sharedServices from '@justeat/f-services';
Prob worth catching up about the `locale` and `theme` aspects of this? Could pair on this tomorrow when you have time @zlatinivanov-je

2020-02-19 16:47 UTC, ashleynolan commented on packages/f-user-message/src/components/UserMessage.vue
> +<style lang="scss">
I'd likely set this to `module` ([like here](https://github.com/justeat/fozzie-components/blob/master/packages/f-footer/src/components/ButtonList.vue#L37)) as that should encapsulate the selectors.

2020-02-19 17:19 UTC, zlatinivanov-je commented on packages/f-user-message/README.md
> +[![Build Status](https://travis-ci.org/justeat/f-user-message.svg)](https://travis-ci.org/justeat/f-user-message)
... This was a copy from `f-header`

2020-02-20 10:30 UTC, ashleynolan commented on packages/f-user-message/README.md
> +[![Build Status](https://travis-ci.org/justeat/f-user-message.svg)](https://travis-ci.org/justeat/f-user-message)
I'll look to remove it from all the other packages today as I'm doing a bit of a tidy-up atm of the `fozzie-components`

2020-02-20 10:40 UTC, ashleynolan commented on packages/f-user-message/README.md
> +[![Build Status](https://travis-ci.org/justeat/f-user-message.svg)](https://travis-ci.org/justeat/f-user-message)
@zlatinivanov-je If you can replace it with the following:

```
[![CircleCI](https://circleci.com/gh/justeat/fozzie-components.svg?style=svg&circle-token=4c77c1990b98c8e06e01b497bc80f376346f609d)](https://circleci.com/gh/justeat/workflows/fozzie-components)
```

2020-02-24 16:27 UTC, ashleynolan commented on packages/f-user-message/babel.config.js
> +    const isSettings = api.env('settings');
Just been tidying up some stuff in the monorepo – you don't need this `isSettings`. Looks like it got copied over from another project but it's never used (can delete the reference on line 11 as well)

2020-02-24 16:31 UTC, ashleynolan commented on packages/f-user-message/jest.config.js
> +        '\\.(jpg|jpeg|png|gif|svg)$': '<rootDir>/fileMock.js'
Don't think you'll need this line either

2020-03-25 15:27 UTC, zlatinivanov-je commented on packages/f-user-message/README.md
> +[![Build Status](https://travis-ci.org/justeat/f-user-message.svg)](https://travis-ci.org/justeat/f-user-message)
@ashleynolan I have added the suggested, jus not sure what ones of the other should remain. Also things have changed since. Please double check.

2020-03-26 10:04 UTC, smilburn1990 commented on packages/f-user-message/CHANGELOG.md
> +*March 25, 2020*
NIT: Yesterday's date

2020-03-26 10:07 UTC, smilburn1990 commented on packages/f-user-message/src/components/UserMessage.vue
> +                        d="M14 3c6.09 0 11 4.99 11 11s-4.99 11-11 11c-6.01.078-11-4.911-11-11C3 7.91 7.871 3 14 3zm2.16 11.785V7.832h-2.867v5.5H7.95v2.867h6.796c.825 0 1.415-.589 1.415-1.414z" />
Is there a way of not having this in the component? Maybe have the svg as an asset?

2020-03-26 17:10 UTC, zlatinivanov-je commented on packages/f-user-message/CHANGELOG.md
> +*March 25, 2020*
It was re-opened on this day. I can update once ready to go out

2020-03-26 17:50 UTC, zlatinivanov-je commented on packages/f-user-message/src/components/UserMessage.vue
> +                        d="M14 3c6.09 0 11 4.99 11 11s-4.99 11-11 11c-6.01.078-11-4.911-11-11C3 7.91 7.871 3 14 3zm2.16 11.785V7.832h-2.867v5.5H7.95v2.867h6.796c.825 0 1.415-.589 1.415-1.414z" />
That could probably do with f-icons use. Will have a look

2020-03-27 09:16 UTC, DamianMullins commented on yarn.lock
> +  resolved "http://packages.je-labs.com/npm/private-npm/axios-mock-adapter/-/axios-mock-adapter-1.18.1.tgz#a2ba2638ef513d954793f96bde3e26bd4a1b7940"
You'll need to set your registry to the public URL otherwise CI won't be able to find these references.

2020-03-27 09:55 UTC, zlatinivanov-je commented on yarn.lock
> +  resolved "http://packages.je-labs.com/npm/private-npm/axios-mock-adapter/-/axios-mock-adapter-1.18.1.tgz#a2ba2638ef513d954793f96bde3e26bd4a1b7940"
Good shout. This is because of my other project, although it has an `.npmrc` file.

2020-03-30 09:19 UTC, ashleynolan requested changes
Looks good – just a few minor comments but then LGTM.

2020-03-30 09:19 UTC, ashleynolan commented on packages/f-user-message/README.md
> +A development server is set to provide a stubed response for the api call, when running locally.
Typo: `stubed` > `stubbed`

2020-03-30 09:19 UTC, ashleynolan commented on packages/f-user-message/README.md
> +See [Demo folder](./src/demo/) for more detail._
Can get rid of the trailing `_` here.

2020-03-30 09:19 UTC, ashleynolan commented on packages/f-user-message/package.json
> +    "axios-mock-adapter": "^1.18.1",
Can you remove the `^` on this dependency (and re-run `yarn install` to update the `yarn.lock`)

2020-03-30 09:19 UTC, ashleynolan commented on packages/f-user-message/src/components/UserMessage.vue
> +                :class="$style['c-userMessageContainer']"
Should be `c-userMessage-container` to matching naming convention

2020-03-30 09:19 UTC, ashleynolan commented on packages/f-user-message/src/components/UserMessage.vue
> +                <p :class="$style['c-userMessageText']">
Should be `c-userMessage-text` to matching naming convention (as this is a child of `c-userMessage`)

2020-03-30 09:19 UTC, ashleynolan commented on packages/f-user-message/src/assets/img/icons/clock.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 28 28"><path fill-rule="nonzero" d="M14 3c6.09 0 11 4.99 11 11s-4.99 11-11 11c-6.01.078-11-4.911-11-11C3 7.91 7.871 3 14 3zm2.16 11.785V7.832h-2.8
Do you need this? Looks like you're pulling the icon from `f-vue-icons`?

2020-03-30 09:19 UTC, ashleynolan commented on packages/f-user-message/src/components/UserMessage.vue
> +        fill: white;
Should use `$white` here.

2020-03-30 09:19 UTC, ashleynolan commented on packages/f-user-message/src/components/UserMessage.vue
> +        min-width: 28px;
Could set this as a variable (`$userMessage-icon-size` for instance?) and that way if it ever changes, from `28px` you only have to change the variable value.

2020-03-30 09:19 UTC, ashleynolan commented on packages/f-user-message/src/index.js
> +    Vue.component('User Message', UserMessage);
Think this value shouldn't include spaces? So would just be `UserMessage`

2020-03-30 12:22 UTC, zlatinivanov-je commented
Thank you @ashleynolan for the review. All comments actioned.

2020-03-30 12:27 UTC, DamianMullins requested changes
You have a couple of internal package references in your yarn lock file again.

2020-03-30 12:37 UTC, ashleynolan commented on packages/f-user-message/src/assets/img/icons/clock.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 28 28"><path fill-rule="nonzero" d="M14 3c6.09 0 11 4.99 11 11s-4.99 11-11 11c-6.01.078-11-4.911-11-11C3 7.91 7.871 3 14 3zm2.16 11.785V7.832h-2.8
Bump on this comment as seems to have resolved – do you still need this commited? (as it's pulling this icon from `f-vue-icons`)?

2020-03-30 12:42 UTC, DamianMullins commented on packages/f-user-message/src/components/tests/UserMessage.test.js
> +    it('calls populateUserMessage on mount', async () => {
I'm not super keen on this type of testing, I think we should focus on testing inputs and outputs of functions rather than testing their internals?

2020-03-30 16:12 UTC, zlatinivanov-je commented on packages/f-user-message/src/assets/img/icons/clock.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 28 28"><path fill-rule="nonzero" d="M14 3c6.09 0 11 4.99 11 11s-4.99 11-11 11c-6.01.078-11-4.911-11-11C3 7.91 7.871 3 14 3zm2.16 11.785V7.832h-2.8
Oh, yeah, sorry. I don't think we need that file anymore. 

_On a separate note, I wonder if this is the most appropriate icon at all, a clock. But going with what is already in use._

2020-03-30 16:14 UTC, zlatinivanov-je commented on packages/f-user-message/src/components/tests/UserMessage.test.js
> +    it('calls populateUserMessage on mount', async () => {
This is a copy of the tests already in sue on Home Web. What would you like me to change it to?

2020-03-31 09:03 UTC, DamianMullins commented on packages/f-user-message/src/components/tests/UserMessage.test.js
> +    it('calls populateUserMessage on mount', async () => {
I think it's fine for now, probably needs further discussion with all the engineers around testing best practices. We have similar tests in Menu Web which test internals of functions that don't have a return value.

2020-03-31 09:18 UTC, ashleynolan submitted a review, later dismissed
:shipit:

2020-03-31 09:43 UTC, zlatinivanov-je commented
Good catch @DamianMullins keep switching context with my other project that relies on the internal packages and forgetting to switch back when updating this. :)  Thank you
Now updated, hopefully all correct

2020-03-31 09:59 UTC, ashleynolan commented
@zlatinivanov-je I think there's a way to set which package repository a repo looks at using a `.yarnrc`. Might save you some pain switching between projects then as `yarn` will just check that when doing package updates rather than having to manually switch 😄 

> https://gemfury.com/help/private-yarn/

2020-03-31 13:47 UTC, zlatinivanov-je commented
@ashleynolan I have an [.npmrc](https://github.je-labs.com/cogchord/ConsumerHelpWebApp/blob/master/.npmrc) file in my project but that seems to fail on the internal `generate-configs` package that is not scoped. 
I have updated this PR though. Do you mind giving it one more once-over?
@DamianMullins

2020-03-31 14:27 UTC, DamianMullins approved these changes

2020-03-31 15:16 UTC, ashleynolan approved these changes

2020-03-31 15:18 UTC, ashleynolan commented
All approved. Happy to merge when you're ready for this to go in. Can you check the PR description as well to show what browsers it's been tested in 👍

2020-04-01 08:43 UTC, merged