f-footer@2.1.0 - Fix country selector closing on-click for mobile
justeattakeaway/fozzie-components pull request #152
Opened 2020-03-05 14:05 UTC by laurenrodney

Moved v-click-outside handler from button to parent element to prevent the country selector from closing on-click

---

## UI Review Checks

- [x] This code has been checked with regard to [our accessibility standards](http://fozzie.just-eat.com/documentation/general/accessibility/checklist)

## Browsers Tested

- [x] Chrome (latest)
- [ ] Internet Explorer 11
- [x] Mobile (iPhone and Android on chrome)

2020-03-05 14:53 UTC, DamianMullins submitted a review, later dismissed

2020-03-05 14:55 UTC, simonsandersje submitted a review, later dismissed

2020-03-06 09:36 UTC, ashleynolan submitted a review, later dismissed
Got conflicts to resolve, but otherwise LGTM :shipit:

2020-03-06 09:45 UTC, ashleynolan commented on packages/f-footer/CHANGELOG.md
>  Latest (roll into next release)
You can delete this line and the one below now (think you had before, but the merge has brought it back)

2020-03-06 10:54 UTC, ashleynolan submitted a review, later dismissed

2020-03-06 14:40 UTC, asherstoppard submitted a review, later dismissed

2020-03-06 14:44 UTC, xander-marjoram requested changes
Looks like we just need to fix the changelog so we're not writing over Simon's entry

2020-03-06 15:11 UTC, xander-marjoram approved these changes

2020-03-06 16:01 UTC, ashleynolan approved these changes

2020-03-06 16:01 UTC, merged