fozzie-components@v1.6.0 - Package updates and eslint import helper added
justeattakeaway/fozzie-components pull request #154
Opened 2020-03-27 15:37 UTC by ashleynolan

### Added
- Added the `eslint-import-resolver-webpack` so that eslint can understand webpack special characters such as `@` used in import paths

### Changed
- Minor package updates

2020-03-27 15:41 UTC, simonsandersje submitted a review, later dismissed

2020-03-27 15:53 UTC, zlatinivanov-je submitted a review, later dismissed

2020-03-27 16:15 UTC, ashleynolan commented
@simonsandersje @zlatinivanov-je Could I get a re-review. Had some linting issues I had to address.

2020-03-27 16:50 UTC, zlatinivanov-je commented
Had a look but the build is still failing

2020-03-30 15:49 UTC, ashleynolan commented
@zlatinivanov-je Have resolved build issieu. Ignore the Danger checks – simply as I'm not bumping the f-header/footer packages because it's a minor config change that can be rolled into the next release.

2020-03-30 16:06 UTC, smilburn1990 requested changes

2020-03-30 16:06 UTC, smilburn1990 commented on CHANGELOG.md
> +v1.6.0
NIT: Wrong date

2020-03-30 16:06 UTC, smilburn1990 commented on packages/f-footer/CHANGELOG.md
> +*March 27, 2020*
Same as above

2020-03-30 16:06 UTC, smilburn1990 commented on packages/f-header/CHANGELOG.md
> +*March 27, 2020*
Same as above

2020-03-30 16:06 UTC, smilburn1990 commented on packages/f-vue-icons/CHANGELOG.md
> +*March 30, 2020*
Same as above

2020-03-30 16:16 UTC, ashleynolan commented on packages/f-vue-icons/CHANGELOG.md
> +*March 30, 2020*
This one's actually right 😆

2020-03-30 16:17 UTC, ashleynolan commented
@smilburn1990 Fixed those dates

2020-03-30 16:19 UTC, smilburn1990 approved these changes

2020-03-30 21:42 UTC, DamianMullins approved these changes

2020-03-31 08:16 UTC, merged