#trivial fixes for atom component tests
justeattakeaway/fozzie-components pull request #1547
Opened 2021-12-10 13:03 UTC by LTurns

- removed unused `open` function from component object
- updated `f-wdio-utils` version
- added scripts to `f-spinner`
- removed `selector.js` file since it usually only holds one `data-test-id`
- other small linting fixes

2021-12-15 11:57 UTC, siggerzz commented on packages/components/atoms/f-button/test-utils/component-objects/f-button.component.js
> +    get component () { return $('[data-test-id="action-button-component"]'); }
I feel like this file should be renamed to `f-button--action.component.js` to match the convention of the other component objects.

2021-12-15 11:58 UTC, siggerzz commented on packages/components/atoms/f-button/test/component/f-button.component.spec.js
> +        button = new Button();
When you update  the file name, change this to `button = new ActionButton();` to match the naming convention.

2021-12-15 12:01 UTC, siggerzz requested changes
Looking way better! Just a minor comment around f-button.

2021-12-15 16:48 UTC, siggerzz approved these changes, later dismissed

2021-12-15 16:56 UTC, JoshuaNg2332 submitted a review, later dismissed

2021-12-16 09:28 UTC, JoshuaNg2332 submitted a review, later dismissed

2021-12-16 09:28 UTC, siggerzz submitted a review, later dismissed

2021-12-16 15:23 UTC, JoshuaNg2332 approved these changes

2021-12-16 15:53 UTC, oliversweb approved these changes

2021-12-16 15:56 UTC, merged