#trivial - small fixes to molecules component tests
justeattakeaway/fozzie-components pull request #1552
Opened 2021-12-13 15:26 UTC by LTurns

- removed unused `open` function from component object
- updated `f-wdio-utils` version
- updated component names
- removed `selector.js` file 
- other small linting fixes

2021-12-13 16:18 UTC, ashleynolan approved these changes, later dismissed

2021-12-15 12:04 UTC, siggerzz commented on packages/components/molecules/f-promotions-showcase/test/accessibility/axe-accessibility.spec.js
>          const axeResults = getAccessibilityTestResults('f-promotionsShowcase');
Update to `f-promotions-showcase`

2021-12-15 12:05 UTC, siggerzz requested changes
Just a few minor comments!

2021-12-15 16:47 UTC, siggerzz submitted a review, later dismissed

2021-12-15 16:52 UTC, JoshuaNg2332 approved these changes, later dismissed

2021-12-17 09:21 UTC, JoshuaNg2332 approved these changes

2021-12-17 09:36 UTC, oliversweb approved these changes

2021-12-17 09:42 UTC, merged