Storybook deploy fix v2
justeattakeaway/fozzie-components pull request #1578
Opened 2022-01-07 11:35 UTC by siggerzz

2022-01-07 15:04 UTC, ashleynolan approved these changes

2022-01-07 15:11 UTC, FayeCarter approved these changes, later dismissed

2022-01-07 15:44 UTC, ashleynolan requested changes
I think you may not need the cache stuff to be removed – just double checking atm

2022-01-10 10:17 UTC, siggerzz commented
> I think you may not need the cache stuff to be removed – just double checking atm

I tested this by storing the cache folder as an artefact, and it wasn't caching sub-directories of node_modules/@justeat :(

2022-01-10 11:25 UTC, FayeCarter approved these changes

2022-01-10 12:10 UTC, JoshuaNg2332 approved these changes

2022-01-10 13:07 UTC, merged