storybook@v0.1.0
justeattakeaway/fozzie-components pull request #163
Opened 2020-04-16 11:20 UTC by siggerzz

This is still very much a WIP, however it's a start!

`cd packages/storybook`
`yarn`
`yarn storybook:serve`

This will start up the Storybook app. (We'll need to host this somewhere eventually)
From here, you'll be able to interact with the `f-header` and `f-footer` components in isolation.

**Note: I was having some webpack issues, which I was able to resolve by doing the various Sass imports, however this shouldn't be merged until it's resolved. A front-end engineer is probably better placed to resolve this :)**

![image](https://user-images.githubusercontent.com/14013357/79450262-a1a99680-7fdc-11ea-905e-50925b03eeca.png)

2020-04-16 11:24 UTC, siggerzz commented on packages/f-footer/src/components/Footer.vue
> +        theme () {
Changed this so that we could dynamically change the theme within Storybook. Not sure what implications this could have though...

2020-04-16 11:25 UTC, siggerzz commented on packages/f-header/src/assets/scss/common.scss
> +@import '~@justeat/fozzie-colour-palette/src/scss/index';
Storybook was complaining for some reason about this...

2020-04-16 11:25 UTC, siggerzz commented on packages/f-header/src/components/Header.vue
> +        theme () {
ditto

2020-04-16 12:36 UTC, xander-marjoram commented on packages/f-footer/src/components/Footer.vue
> +        theme () {
I think this is probably a good thing if we ever wanted to do multiple tenants/themes on a single page anyway, or experimentations with theming.

2020-04-16 12:38 UTC, xander-marjoram commented
Looks like you'll need to do a minor/patch version increment of f-header and f-footer, with changelog updates as well.

2020-04-16 13:46 UTC, xander-marjoram commented on packages/f-footer/CHANGELOG.md
> +*April 16, 2020*
If there's already a `Latest` section, those entries should be rolled into yours, like so:
```markdown
v2.1.1
------------------------------
*April 16, 2020*

### Added
- `stories` folder that will contain `*.stories.js` files for use with Storybook

### Changed
- Updated name of component in `index.js` from `Footer` > `VueFooter` (as `Footer` is a reserved word according to linting rules)
```

2020-04-16 13:47 UTC, xander-marjoram commented on packages/f-header/CHANGELOG.md
> +*April 16, 2020*
Ditto here

2020-04-16 15:55 UTC, ashleynolan requested changes
Might be worth catching up about the `common.scss` additions. Guessing this was a webpack issue that prompted the addition?

2020-04-16 15:55 UTC, ashleynolan commented on packages/f-footer/src/assets/scss/icons.scss
> +@import "../assets/scss/common.scss";
This file should get imported already [by this line](https://github.com/justeat/fozzie-components/blob/master/packages/f-footer/vue.config.js#L14)?

2020-04-16 15:55 UTC, ashleynolan commented on packages/f-footer/src/components/ButtonList.vue
> +@import "../assets/scss/common.scss";
Same for all these references. Might be worth catching up about this, as don't really want to add references in for every component for this if possible.

2020-04-16 15:58 UTC, ashleynolan commented on packages/f-footer/src/components/Footer.vue
> +        theme () {
I don't think it would have too much of an implication tbh 👍

2020-04-16 16:02 UTC, ashleynolan submitted a review, later dismissed

2020-04-16 16:02 UTC, ashleynolan commented on packages/f-footer/src/components/LinkList.vue
> +@import '../assets/scss/icons.scss';
Was the `@` failing build somewhere? This is webpack specific syntax so should work I would think (would be interested if it was failing).

2020-04-16 16:02 UTC, ashleynolan commented on packages/storybook/package.json
> +    "@storybook/addon-actions": ">=5.3.0",
Can you lock these versions (so just remove the characters before the number on each package?)

2020-04-16 16:05 UTC, siggerzz commented on packages/f-footer/src/components/LinkList.vue
> +@import '../assets/scss/icons.scss';
Yeah was seeing some issue when compiling. Again, not sure if it's related to all the webpack related stuff or not 👍

2020-04-16 16:06 UTC, siggerzz commented
@ashleynolan Yep, all these `common.scss` imports are to get around the webpack related issues. One the webpack stuff is resolved, these can be removed 👍

2020-04-21 10:37 UTC, DamianMullins submitted a review, later dismissed

2020-04-21 10:58 UTC, DamianMullins commented on packages/f-footer/src/components/Footer.vue
> +        localeProp: {
Why was the name of this prop changed? The `Prop` suffix is kind of redundant.

Also, if this is going to change then we should bump the major version of the package as it requires users to update their code.

2020-04-21 11:00 UTC, DamianMullins commented on packages/f-footer/src/components/Footer.vue
> +        localeProp: {
I see it was changed so you could introduce a computed property, I'd argue that the name of that property should be updated rather than the prop.

2020-04-21 11:03 UTC, siggerzz commented on packages/f-footer/src/components/Footer.vue
> +        localeProp: {
Because I had to make `locale` a computed in order for changes to take effect within Storybook if you changed the locale (it was part of the component data previously.)

Having the following code results in issues, because both the computed + the prop are called `locale`

```
        locale () {
            return sharedServices.getLocale(tenantConfigs, this.locale, this.$i18n);
        },
```

I can change the name of the computed instead if you like?

2020-04-21 11:04 UTC, siggerzz commented on packages/f-footer/src/components/Footer.vue
> +        localeProp: {
@DamianMullins Sure thing. I guess it reduces the changed file count too :)

2020-04-21 12:16 UTC, DamianMullins approved these changes

2020-04-21 13:36 UTC, tommcclean commented on packages/f-footer/src/components/Footer.vue
> +        theme () {
Perfect for when we have a nuxt site and when you change from one country to another, it could be completely client side :D

2020-04-21 13:38 UTC, asherstoppard commented on packages/f-footer/CHANGELOG.md
> +- `stories` folder that will contain `*.stories.js` files for use with Storybook
Might be worth considering `__stories__` as a directory to ensure it's at the top and bring it inline with `__tests__`?

2020-04-21 13:38 UTC, tommcclean commented on packages/f-header/src/components/Header.vue
> -                :show-for-you-copy="showForYouCopy"
Is removing this intended?

2020-04-21 13:39 UTC, siggerzz commented on packages/f-header/src/components/Header.vue
> -                :show-for-you-copy="showForYouCopy"
Yep. As far as I can tell, this prop wasn't actually doing anything. Although if you can prove me wrong, I'll add it back in 👀

2020-04-21 13:40 UTC, tommcclean commented
I think you should add a readme to the storybook folder - so people can read instructions, and what it is

2020-04-21 13:42 UTC, siggerzz commented
> I think you should add a readme to the storybook folder - so people can read instructions, and what it is

@tommcclean Does this suffice - https://lmgtfy.com/?q=storybookjs ? 😁 

In all seriousness though, what would you want me to add?

2020-04-21 13:44 UTC, tommcclean commented
> > I think you should add a readme to the storybook folder - so people can read instructions, and what it is
> 
> @tommcclean Does this suffice - https://lmgtfy.com/?q=storybookjs ? 😁
> 
> In all seriousness though, what would you want me to add?

Run commands, any troubleshooting tips, why we use it. In brief

2020-04-21 13:45 UTC, siggerzz commented
Spoke with @tommcclean about adding a readme / updating PR template. Will do this as part of my next ticket, which will be to host Storybook.

2020-04-21 13:47 UTC, tommcclean approved these changes

2020-04-21 13:47 UTC, siggerzz commented on packages/f-footer/CHANGELOG.md
> +- `stories` folder that will contain `*.stories.js` files for use with Storybook
Are we doing this with tests? I couldn't see an example anywhere?

2020-04-22 08:33 UTC, merged