f-account-info@v0.21.1 - Added temp extra logging for auth exp (2)
justeattakeaway/fozzie-components pull request #1822
Opened 2022-04-29 16:07 UTC by oliversweb

2022-05-03 14:50 UTC, kevinrodrigues approved these changes, later dismissed

2022-05-03 15:28 UTC, kevinrodrigues submitted a review, later dismissed

2022-05-04 12:27 UTC, BanksySan requested changes

2022-05-04 12:27 UTC, BanksySan commented on packages/components/pages/f-account-info/src/components/AccountInfo.vue
> +                }
Can we put the `1`, `0` and `-1` into an object describing them instead of using magic numbers?

2022-05-04 13:06 UTC, BanksySan approved these changes

2022-05-04 13:33 UTC, tommcclean approved these changes

2022-05-04 13:46 UTC, merged