f-registration@v0.6.0
justeattakeaway/fozzie-components pull request #192
Opened 2020-06-02 14:44 UTC by adamashton

Added create account API call when clicking create account button

## UI Review Checks

- [X] README and/or UI Documentation has been [created|updated]
- [X] Unit tests have been [created|updated]
- [X] This code has been checked with regard to [our accessibility standards](http://fozzie.just-eat.com/documentation/general/accessibility/checklist)

## Browsers Tested
- [X] Chrome (latest)
- [X] Internet Explorer 11

## Images
### API Error
![image](https://user-images.githubusercontent.com/1670343/83533742-dcfa1900-a4e7-11ea-86a3-9b3381c045ab.png)

2020-06-02 15:09 UTC, kevinrodrigues commented on packages/f-registration/src/components/Registration.vue
> +                v-if="shouldShowGenericError"
I think you could just pass in `genericErrorMessage` instead as the computed prop isn't doing much but returning that value.

2020-06-02 15:09 UTC, kevinrodrigues commented on packages/f-registration/src/components/tests/Registration.test.js
> +        it('should post correct data and emit success event when API responds with 201 Created', async () => {
There's quite a lot going on in here. For clarity would it not be better to use a spy and mock the data. Seems that this test and the next one is mostly testing `RegistrationServiceApi.createAccount`. Ideally this service should have it's own tests for these type of calls and in here you would mostly test that this method was called with some params and you can also add tests for some of the local data values that are changed.

2020-06-02 17:09 UTC, adamashton commented on packages/f-registration/src/components/tests/Registration.test.js
> +        it('should post correct data and emit success event when API responds with 201 Created', async () => {
Yeh, done.

2020-06-03 07:14 UTC, kevinrodrigues submitted a review, later dismissed

2020-06-03 08:31 UTC, DamianMullins commented on packages/f-registration/babel.config.js
> +        '@babel/plugin-transform-regenerator',
Do you need to add this plugin?

2020-06-03 08:34 UTC, DamianMullins commented on packages/f-registration/src/event-names/index.js
> +const CreateAccountSuccess = 'registration-create-account-success';
You could move this file to the root of `/src` and rename it to `event-names`?

2020-06-03 09:09 UTC, adamashton commented on packages/f-registration/babel.config.js
> +        '@babel/plugin-transform-regenerator',
They're needed to allow async methods in unit testing.

2020-06-03 09:11 UTC, DamianMullins commented on packages/f-registration/babel.config.js
> +        '@babel/plugin-transform-regenerator',
I know `plugin-transform-runtime` is but I'm not sure `plugin-transform-regenerator` is required? Also, it's not in the dev dependencies below?

2020-06-03 09:22 UTC, adamashton commented on packages/f-registration/babel.config.js
> +        '@babel/plugin-transform-regenerator',
You're right. I did not need `plugin-transform-regenerator`. Where is the dev devependenvies for babel plugins?

2020-06-03 09:25 UTC, DamianMullins commented on packages/f-registration/babel.config.js
> +        '@babel/plugin-transform-regenerator',
Looks good. I mean the `devDependencies` in the package.json file. You've already added `plugin-transform-runtime` so you're all good.

2020-06-03 09:27 UTC, DamianMullins commented on packages/f-registration/src/components/Registration.vue
> +                    .then(() => {
If you're using await you shouldn't need the promise chain here? Everything in `.then()` can just go on the line below the awaited API call.

You should be able to move your error handling into a `catch` block before `finally` below.

2020-06-03 09:32 UTC, adammorr requested changes

2020-06-03 09:32 UTC, adammorr commented on packages/f-registration/src/services/RegistrationServiceApi.js
> +            .post(url, data, config);
The tenant should be part of the URL as opposed to setting the `Accept-Tenant` header

2020-06-03 09:36 UTC, adamashton commented on packages/f-registration/src/services/RegistrationServiceApi.js
> +            .post(url, data, config);
Not if we're calling AccountWeb, which we are at the moment.

2020-06-03 09:36 UTC, adamashton commented on packages/f-registration/src/components/Registration.vue
> +                    .then(() => {
I see, nice.

2020-06-03 09:39 UTC, adammorr commented on packages/f-registration/src/services/RegistrationServiceApi.js
> +            .post(url, data, config);
OK so we're releasing a version of the package with AccountWeb and then a follow up for AccountApi?

2020-06-03 09:54 UTC, adamashton commented on packages/f-registration/src/services/RegistrationServiceApi.js
> +            .post(url, data, config);
Yup

2020-06-03 11:24 UTC, DamianMullins commented on packages/f-registration/src/components/tests/Registration.test.js
> +            return mount(Registration, { propsData, sync: false, attachTo: div });
What does `sync` do here? I can't see it in the vue-test-utils docs?

2020-06-03 11:24 UTC, DamianMullins commented on packages/f-registration/src/components/tests/Registration.test.js
> +            const wrapper = mountComponentAndAttachToDocument();
Why do you need to attach the component to the document?

2020-06-03 11:31 UTC, adamashton commented on packages/f-registration/src/components/tests/Registration.test.js
> +            return mount(Registration, { propsData, sync: false, attachTo: div });
Not needed actually

2020-06-03 11:31 UTC, adamashton commented on packages/f-registration/src/components/tests/Registration.test.js
> +            const wrapper = mountComponentAndAttachToDocument();
attachToDocument is deprecated, so I need to use attachTo to ensure that the trigger('click') actually triggers the click event for Vue

2020-06-03 11:37 UTC, DamianMullins commented on packages/f-registration/src/components/tests/Registration.test.js
> +            const wrapper = mountComponentAndAttachToDocument();
So the call to `trigger` doesn't submit the form if you don't do this? Interested as I've not seen this syntax or hit this issue before.

2020-06-03 11:41 UTC, adamashton commented on packages/f-registration/src/components/tests/Registration.test.js
> +            const wrapper = mountComponentAndAttachToDocument();
I was having that problem yes, and I followed this. https://stackoverflow.com/questions/53382235/trigger-form-submit-on-button-click-in-vue-unit-test

2020-06-03 11:45 UTC, DamianMullins commented on packages/f-registration/src/components/tests/Registration.test.js
> +            try {
Do you need the try/catch blocks?

2020-06-03 11:45 UTC, DamianMullins submitted a review, later dismissed

2020-06-03 11:48 UTC, ashleynolan commented on packages/f-registration/babel.config.js
> +        '@babel/plugin-transform-runtime'
More for info than anything else – what did you need to add this for?

2020-06-03 11:48 UTC, ashleynolan commented on packages/f-registration/package.json
> +    "axios-mock-adapter": "^1.18.1",
Can you lock these dependencies (so get rid of the `^` and then rerun yarn to update the lockfile

2020-06-03 11:51 UTC, adamashton commented on packages/f-registration/babel.config.js
> +        '@babel/plugin-transform-runtime'
It's something to do with transpiling from ES6 to ES5 when you have async methods in your unit tests. I was really just googling the error message that came up.

2020-06-03 11:55 UTC, ashleynolan requested changes

2020-06-03 11:55 UTC, ashleynolan commented on packages/f-registration/src/components/Registration.vue
> +        tenant: {
Would be good to handle this through locale, as we should be able to map locales to tenants.

We do this in [`f-searchbox` for instance](https://github.com/justeat/f-searchbox/blob/6367272646a21824449bb55df9e371497d40a3db/src/tenants/index.js#L16-L30) – just means one less prop to define as it implicit config

2020-06-03 12:00 UTC, adamashton commented on packages/f-registration/package.json
> +    "axios-mock-adapter": "^1.18.1",
Sure, done.

2020-06-03 12:03 UTC, ashleynolan commented on packages/f-registration/babel.config.js
> +        '@babel/plugin-transform-runtime'
Ah ok – we've hit that issue in a couple of other packages.

Best way to solve it is to change the babel config to [match this](https://github.com/justeat/fozzie-components/blob/master/packages/f-header/babel.config.js#L10-L17) – the main thing that does is run the tests using the latest version of Node so that you don't need to transpile async/await for the tests. If you still see the issues after adding that give me a shout as sometimes you then also need to manually clear the jest cache so that the new babel config comes through correctly.

2020-06-03 12:43 UTC, adamashton commented on packages/f-registration/src/components/Registration.vue
> +        tenant: {
Probably getting outside of scope for the ticket I'm working on. Perhaps for another ticket.

2020-06-03 13:27 UTC, adamashton commented on packages/f-registration/babel.config.js
> +        '@babel/plugin-transform-runtime'
Thanks, fixed it with the updated babel config

2020-06-03 15:50 UTC, xander-marjoram commented on packages/f-registration/src/components/tests/Registration.test.js
> +                    email = 'adam.ashton+jetest@just-eat.com',
I would avoid checking personal info in (even if it's quite easy to guess/work out).

2020-06-03 16:06 UTC, xander-marjoram commented on packages/f-registration/src/components/Registration.vue
> +        tenant: { // TODO Compute tenant value from local config instead of using this prop
We normally recommend adding a JIRA ID so that stuff like this doesn't get forgotten

2020-06-04 07:49 UTC, adamashton commented on packages/f-registration/src/components/tests/Registration.test.js
> +                    email = 'adam.ashton+jetest@just-eat.com',
Sure

2020-06-04 09:03 UTC, xander-marjoram approved these changes

2020-06-04 09:09 UTC, ashleynolan approved these changes

2020-06-04 09:15 UTC, adammorr approved these changes

2020-06-04 09:15 UTC, merged

2020-06-04 10:25 UTC, DamianMullins commented on packages/f-registration/babel.config.js
> +        '@babel/plugin-transform-runtime'
Was it not needed to transpile the async code in the main codebase as well? Or does `present-env` handle that?

2020-06-05 11:44 UTC, ashleynolan commented on packages/f-registration/babel.config.js
> +        '@babel/plugin-transform-runtime'
`preset-env` should handle the transform (which is why there was a regenerator runtime error shown in Jest, as that's what it converts it to)