f-footer@2.0.0-beta.6 - Use f-vue-icons
justeattakeaway/fozzie-components pull request #20
Opened 2019-07-18 10:07 UTC by xander-marjoram

### Added
- `yarn demo` command for easier prototyping
- Dependency on `f-vue-icons`
- Make use of `AppStoreIcon`, `BaseProviderIcon` and `ChevronIcon` from `f-vue-icons`
- Generic `IconList` component
- Component styles
- Extend tests for `LinkList` component

 ### Changed
- Remove `Footer` prefix from most components
- Remove unused fields from resource files and add locale

2019-07-18 10:27 UTC, dandel10n commented on packages/f-footer/src/components/LinkList.vue
> +    display: inline-block;
Do we need it to be `inline-block` here?

2019-07-18 10:58 UTC, ashleynolan requested changes
Few naming and styling comments

2019-07-18 10:58 UTC, ashleynolan commented on packages/f-footer/src/components/CountrySelector.vue
> +.c-footer-country-selector {
Should be `c-footer-countrySelector`

2019-07-18 10:58 UTC, ashleynolan commented on packages/f-footer/src/components/FeedbackBlock.vue
> +.c-footer-feedback-block {
Same as above – `c-footer-feedbackBlock`

2019-07-18 10:58 UTC, ashleynolan commented on packages/f-footer/src/components/Footer.vue
> +        <div class="c-footer-container c-footer-row c-footer-row--no-pad-below-wide">
Dashes should be camel case (dashes are to signify child element only).

So `c-footer-row--noPadBelowWide`

2019-07-18 10:58 UTC, ashleynolan commented on packages/f-footer/src/components/Footer.vue
> +                    class="c-icon-list c-icon-list--apps"
`c-iconList` and `c-iconList--apps`

2019-07-18 10:58 UTC, ashleynolan commented on packages/f-footer/src/components/Footer.vue
> +.c-footer-heading--short-below-wide {
`c-footer-heading--shortBelowWide`

2019-07-18 10:58 UTC, ashleynolan commented on packages/f-footer/src/components/Footer.vue
> +.c-footer-row--light {
It doesn't look like the default `c-footer-row` has a background, so makes sense for this to be called `shaded` rather than light? (as white is lighter than `$footer-bgLight` technically)

2019-07-18 10:58 UTC, ashleynolan commented on packages/f-footer/src/components/IconList.vue
> +.c-icon-list {
`c-iconList`

2019-07-18 10:58 UTC, ashleynolan commented on packages/f-footer/src/components/LinkList.vue
> +            <h2>
Is it semantically valid to put heading tags inside a button? (I'm not sure myself, but doesn't look quite right)

2019-07-18 10:58 UTC, ashleynolan commented on packages/f-footer/src/components/LinkList.vue
> +    &.is-collapsed {
This could probably just be c-footer-panel `.is-collapsed .c-footer-list` (as it would lower the specificity of the selector)

2019-07-18 10:58 UTC, ashleynolan commented on packages/f-footer/src/components/LinkList.vue
> +            display: block;
Better to put these media queries inline with the selector (so this would be on line 93 with the other chevron styles). Sass compresses the media queries into one statement later so it's better to make these more verbose here so that it's clear what states each selector has.

2019-07-18 11:06 UTC, ashleynolan commented on packages/f-vue-icons/src/components/AppStoreIcon/AppStoreIcon.vue
>  import AndroidIconEnGb from '@justeat/f-icons/src/img/icons/appstore/android.svg';
Would it not be worth only importing this once, and then using that import variable in the export:

```js
import AndroidIconEnGb from '@justeat/f-icons/src/img/icons/appstore/android.svg';

export default {
    components: {
        AndroidIconDaDk,
        AndroidIconEnGb,
        AndroidIconEnIe: AndroidIconEnGb,
        AndroidIconEnAu: AndroidIconEnGb,
        …
    }
}
```

Same for the ios SVGs?

2019-07-18 11:07 UTC, ashleynolan commented on packages/f-footer/src/components/tests/LinkList.test.js
> +    describe('for mobile widths', () => {
Best to keep these tests referencing viewport width rather than device.

`for narrow viewport widths`

2019-07-18 11:09 UTC, ashleynolan commented on packages/f-footer/src/components/tests/LinkList.test.js
> +        it('should contain the class "is-collapsed"', () => {
Would make more sense (to me) to reference the behaviour rather than the classname. So:

`should be in a collapsed state`

2019-07-18 11:09 UTC, ashleynolan commented on packages/f-footer/src/components/tests/LinkList.test.js
> +        it('shouldn\'t contain class "is-collapsed" when linkList title is clicked', () => {
`should be in an open state (not collapsed) when linkList title is clicked`

2019-07-18 11:10 UTC, ashleynolan commented on packages/f-footer/src/components/tests/LinkList.test.js
> +    describe('for desktop widths', () => {
`for wide viewport widths`

2019-07-18 11:10 UTC, ashleynolan commented on packages/f-footer/src/components/tests/LinkList.test.js
> +        it('should not contain the class "is-collapsed"', () => {
`Should not be in a collapsed state`

2019-07-18 11:56 UTC, xander-marjoram commented on packages/f-vue-icons/src/components/AppStoreIcon/AppStoreIcon.vue
>  import AndroidIconEnGb from '@justeat/f-icons/src/img/icons/appstore/android.svg';
Didn't realise that was possible, I'll give it a go

2019-07-18 13:02 UTC, xander-marjoram commented on packages/f-footer/src/components/LinkList.vue
> +            <h2>
You're right, it's not valid. We'll try switching it around.

2019-07-19 09:16 UTC, ashleynolan commented on packages/f-footer/src/components/Footer.vue
> +        <div class="c-footer-container c-footer-row c-footer-row--noPadBelowWide">
Are the `c-footer-container` and `c-footer-row` classes always used together (as it looks like they are here?

Seems like they have some styles that conflict with one another (padding for instance). If they can be merged into one `c-footer-container` class, that might make sense?

2019-07-19 09:16 UTC, ashleynolan commented on packages/f-footer/src/components/Footer.vue
> +    padding: spacing(x2);
Looks like a duplicate padding definition to that on line 132.

2019-07-19 09:20 UTC, ashleynolan commented on packages/f-vue-icons/src/components/AppStoreIcon/AppStoreIcon.vue
> +/* eslint-disable import/no-duplicates */
Can remove this now as this shouldn't fail the linting now after the import changes.

2019-07-19 09:54 UTC, dandel10n commented on packages/f-footer/src/components/Footer.vue
> +        <div class="c-footer-container c-footer-row c-footer-row--noPadBelowWide">
I've removed padding from the container class, but I think it is better to have separate `f-footer-row` and `c-footer-container` class. Container is responsible for max-width of the component and row has rows specific styles.

2019-07-19 09:54 UTC, dandel10n commented on packages/f-footer/src/components/Footer.vue
> +    padding: spacing(x2);
✅

2019-07-19 10:58 UTC, DamianMullins commented on packages/f-footer/src/components/IconList.vue
> +                        :is="isApps ? 'app-store-icon' : 'base-provider-icon'"
As this logic is duplicated in two places it would be better to pull it out into a computed property and reference that here instead.

2019-07-19 10:58 UTC, DamianMullins commented on packages/f-footer/src/components/LinkList.vue
> +        window.addEventListener('resize', () => {
Should probably be throttling this, [have a look here for an example](https://github.je-labs.com/menu/menuweb/blob/87551c5c11f01d6afd7e473bd127cefd9539b45c/src/MenuWeb/Assets/vue/components/nav/CategoryNav.vue#L86-L103).

2019-07-19 14:18 UTC, DamianMullins approved these changes

2019-07-19 14:47 UTC, ashleynolan commented on packages/f-footer/src/components/IconList.vue
> +.c-iconList {
More of a question than anything else – where does this class (`c-iconList`) actually get applied to the markup?

2019-07-19 14:48 UTC, ashleynolan approved these changes

2019-07-19 14:56 UTC, dandel10n commented on packages/f-footer/src/components/IconList.vue
> +.c-iconList {
this class is added to the "icon-list" component call in Footer.vue like this:
```
<icon-list
      :title="copy.downloadOurApps"
      :icons="copy.appStoreIcons"
      :is-apps="true"
      :locale="copy.locale"
      class="c-iconList c-iconList--apps" />
```

2019-07-19 14:57 UTC, merged

2019-07-22 14:20 UTC, ashleynolan commented on packages/f-footer/src/components/IconList.vue
> +.c-iconList {
Should `c-iconList` not just be a default class for the `iconList` component? Makes sense to extend it with modifier's for the apps etc though