f-checkout@v3.33.0 - fix address mapping
justeattakeaway/fozzie-components pull request #2009
Opened 2022-06-29 11:09 UTC by FayeCarter

### Fixed
- Address mapping from local storage.

2022-06-29 11:10 UTC, charliearlie approved these changes, later dismissed

2022-06-29 11:19 UTC, jamieomaguire commented on packages/components/pages/f-checkout/src/store/checkout.module.js
> +                if (address.lines) {
does this require any additional testing?

2022-06-29 12:09 UTC, jamieomaguire submitted a review, later dismissed

2022-06-29 12:38 UTC, BanksySan requested changes, later dismissed

2022-06-29 12:38 UTC, BanksySan commented on packages/components/pages/f-checkout/src/store/checkout.module.js
> +                if (address.lines) {
You can use the null coalesce operator here.

2022-06-30 13:27 UTC, FayeCarter commented on packages/components/pages/f-checkout/src/store/checkout.module.js
> +                if (address.lines) {
No longer using this bit of code 🙂

2022-07-01 09:35 UTC, charliearlie approved these changes

2022-07-01 09:37 UTC, jamieomaguire approved these changes

2022-07-01 09:38 UTC, merged