f-mfa@0.11.1 - Republish to pull latest atoms
justeattakeaway/fozzie-components pull request #2112
Opened 2022-08-23 15:34 UTC by xander-marjoram

### Changed
- No changes. Republish to pull latest versions of atoms.

2022-08-23 16:17 UTC, DamianMullins approved these changes

2022-08-23 17:51 UTC, ashleynolan requested changes

2022-08-23 17:51 UTC, ashleynolan commented on packages/components/pages/f-mfa/package.json
> +  "version": "0.11.1",
This PR won’t do anything as far as I’m aware (as there’s no lock file or package changes). You shouldn’t need to re-publish to pull in the latest changes as far as I’m aware tbh.

2022-08-24 12:25 UTC, closed without merging

2022-08-24 12:26 UTC, xander-marjoram commented
Superseded by #2113