f-registration@v3.9.0 - Update visual tests to include multiple tenants
justeattakeaway/fozzie-components pull request #2180
Opened 2022-10-28 14:34 UTC by siggerzz

v3.9.0
------------------------------
*October 28, 2022*

### Changed
- Visual tests to include new tenants
- Updated Story file to use Storybook `Controls`.

2022-10-28 14:40 UTC, adammorr requested changes

2022-10-28 14:40 UTC, adammorr commented on packages/components/pages/f-registration/stories/Registration.stories.js
> +        defaultValue: '/account/login'
```suggestion
        defaultValue: '/account/register'
```

2022-10-28 14:40 UTC, adammorr commented on packages/components/pages/f-registration/test/visual/f-registration.visual.desktop.spec.js
> +const locales = ['en-GB', 'en-AU', 'en-NZ', 'es-ES', 'it-IT'];
Is this meant to be missing `en-IE`?

2022-10-28 15:50 UTC, siggerzz commented on packages/components/pages/f-registration/test/visual/f-registration.visual.desktop.spec.js
> +const locales = ['en-GB', 'en-AU', 'en-NZ', 'es-ES', 'it-IT'];
Ah yeah, my bad. Bad copy paste job 😁

2022-10-28 15:53 UTC, siggerzz commented
@adammorr I took the opportunity to remove `.desktop` from the visual test file name, hence why it looks like the whole file has changed.

This file name used to determine whether or not to run Percy checks on mobile / desktop, but it looks like we missed this when refactoring to use the `devices` array.

2022-10-30 16:01 UTC, adammorr submitted a review, later dismissed

2022-10-31 11:21 UTC, philgoff approved these changes

2022-10-31 11:22 UTC, adammorr approved these changes

2022-10-31 11:22 UTC, merged