f-footer@2.0.0-beta.7 - Country selector component
justeattakeaway/fozzie-components pull request #24
Opened 2019-07-29 15:14 UTC by xander-marjoram

### Added
- `CountrySelector` component logic and styles
- `CountrySelector` tests

2019-07-30 08:35 UTC, dandel10n commented on packages/f-footer/src/components/LinkList.vue
> -        &:focus {
Why you removed focus from here?

2019-07-30 08:40 UTC, dandel10n commented on packages/f-footer/src/components/CountrySelector.vue
> +            :aria-expanded="showCountryList ? 'true' : 'false'">
I would recommend to add `:aria-controls` attribute to show relationship of the button with the expandable region. The list of flags will need an id.

2019-07-30 08:42 UTC, dandel10n commented on packages/f-footer/src/components/CountrySelector.vue
> +        <ul
and `:aria-labelledby="countrySelector-button"` and `role="region"` here

2019-07-30 08:44 UTC, dandel10n commented
Will jest tests come in separate PR for this component?

2019-07-30 12:35 UTC, xander-marjoram commented on packages/f-footer/src/components/LinkList.vue
> -        &:focus {
On focus, we already have the outline, we don't need the underline as well. This matches what we currently have in production (although the outline colour is different)

2019-07-30 13:40 UTC, ashleynolan commented on packages/f-footer/src/components/CountrySelector.vue
> +        class="c-footer-countrySelector"
Could probably just call this `c-countrySelector`?  There's likely no dependency on it being a part of the footer and that way we could pull it out of the footer later if we ever wanted to.

2019-07-30 13:41 UTC, ashleynolan commented on packages/f-footer/src/components/CountrySelector.vue
> +.c-footer-countrySelector-list {
`c-countrySelector-list`?

2019-07-30 13:42 UTC, ashleynolan requested changes
Couple of small updates from me

2019-08-01 08:05 UTC, ashleynolan commented
@xander-marjoram Needs a rebase and update to the description.

2019-08-01 13:20 UTC, dandel10n commented on packages/f-footer/src/components/CountrySelector.vue
> +        class="c-footer-countrySelector"
✅

2019-08-01 13:32 UTC, ashleynolan approved these changes

2019-08-01 14:36 UTC, dandel10n approved these changes

2019-08-01 14:36 UTC, merged