fozzie-components@1.23.0 - Remove demo scripts in favour of Storybook / Update README.md's
justeattakeaway/fozzie-components pull request #246
Opened 2020-07-15 14:21 UTC by siggerzz

2020-07-15 14:41 UTC, tommcclean commented on packages/f-header/package.json
> +  "version": "3.5.0",
What happened to 3.4.0 🚀

2020-07-15 14:45 UTC, siggerzz commented on packages/f-header/package.json
> +  "version": "3.5.0",
https://github.com/justeat/fozzie-components/pull/244

2020-07-15 14:46 UTC, tommcclean reviewed
LGTM - Except that I don't think we should bump the versions as we aren't going to release; happy to be pursuaded otherwise though.

2020-07-15 15:08 UTC, ashleynolan requested changes
I actually think it's worth keeping the separate demo components – my main reason is that there's no other way of debugging them through Vue dev tools as this doesn't work with storybook (I think because the component gets iframed in).

Happy to hear if there's a big reason for getting rid of them, but I think there's a use-case for keeping them in addition to the main storybook way of viewing them.

2020-09-23 16:09 UTC, siggerzz commented
Not needed

2020-09-23 16:09 UTC, closed without merging