Update: rating fixed point value
justeattakeaway/fozzie-components pull request #2460
Opened 2024-02-26 11:44 UTC by mmakwe-onyeka

Changed
Update the rating fixed point

2024-03-11 11:50 UTC, Charlotte-91 approved these changes, later dismissed

2024-03-14 11:24 UTC, siggerzz approved these changes

2024-03-14 11:25 UTC, siggerzz requested changes
Looks like you've got a couple unit tests to update before this can be merged. Please reach out if you need a hand with this @mmakwe-onyeka!

2024-03-25 09:04 UTC, mmakwe-onyeka commented
> Looks like you've got a couple unit tests to update before this can be merged. Please reach out if you need a hand with this @mmakwe-onyeka!

Thank you @siggerzz ive made the update

2024-03-26 14:44 UTC, siggerzz approved these changes

2024-03-26 14:49 UTC, Charlotte-91 approved these changes

2024-03-26 14:51 UTC, merged