f-registration@0.11.0 - Add validation for first and last name
justeattakeaway/fozzie-components pull request #272
Opened 2020-08-05 15:38 UTC by adamashton

Improved validation for first name and last name.

- [X] README and/or UI Documentation has been [created|updated]
- [X] Unit tests have been [created|updated]

## Browsers Tested

- [X] Chrome (latest)
- [X] Edge
- [ ] Mobile (Please list device/browser – Ideally one iPhone model and one Android)

2020-08-05 15:47 UTC, xander-marjoram commented on packages/f-registration/src/components/Registration.vue
> +                        First name exceeds 50 chars
Should we stick with "characters"? Its meaning is slightly more obvious to non-technical users or those using screen readers.

2020-08-05 15:47 UTC, xander-marjoram commented on packages/f-registration/src/components/Registration.vue
> +                        Last name exceeds 50 chars
Same here

2020-08-05 15:48 UTC, xander-marjoram commented on packages/f-registration/src/components/Registration.vue
> +                        Last name should only contain letters, hyphens or apostrophes
What about spaces?

2020-08-05 15:50 UTC, adamashton commented on packages/f-registration/src/components/Registration.vue
> +                        First name exceeds 50 chars
I'm going off the ticket here, which comes from the UI designers...

2020-08-05 15:50 UTC, adamashton commented on packages/f-registration/src/components/Registration.vue
> +                        Last name exceeds 50 chars
Again, see ticket

2020-08-05 15:52 UTC, adamashton commented on packages/f-registration/src/components/Registration.vue
> +                        Last name should only contain letters, hyphens or apostrophes
Hm, gonna go back to Aaron Wilson about this one because I reckon we should allow spaces.

2020-08-05 15:54 UTC, xander-marjoram commented on packages/f-registration/src/components/Registration.vue
> +    return /^[a-zA-Z'-]*$/.test(value);
This also excludes names with accented characters, or those using different alphabets

2020-08-05 15:55 UTC, adamashton commented on packages/f-registration/src/components/Registration.vue
> +    return /^[a-zA-Z'-]*$/.test(value);
Again, this is from the ticket.

2020-08-05 15:59 UTC, xander-marjoram commented on packages/f-registration/src/components/Registration.vue
> +            return this.$v.firstName.$invalid && !this.$v.firstName.maxLength && this.$v.firstName.$dirty;
I _think_ I see how this works, but perhaps we could make it a little clearer and easy to maintain by extracting some of these behind some more computed properties? For example:
```
firstNameIsPresent () {
    return this.$v.firstName.required;
},
firstNameTooLong () {
    return !this.$v.firstName.maxLength;
}
```
What do you think?

2020-08-05 16:01 UTC, adamashton commented on packages/f-registration/src/components/Registration.vue
> +            return this.$v.firstName.$invalid && !this.$v.firstName.maxLength && this.$v.firstName.$dirty;
Initially I thought I agreed with this, it's definitely much cleaner. However, it's doing slightly more in that it's testing to see if the input has been touched as well. The test for `this.$v.firstName.$invalid` is unneeded actually.
It would look like this,
```
<p v-if="!firstNameIsPresent() && this.$v.firstName.$dirty"

...

firstNameIsPresent () {
    return this.$v.firstName.required;
}
```

2020-08-05 16:03 UTC, xander-marjoram commented on packages/f-registration/src/components/Registration.vue
> +    return /^[a-zA-Z'-]*$/.test(value);
I appreciate you're following the AC provided on the ticket, but I think we need to make this regex more inclusive

2020-08-05 16:05 UTC, xander-marjoram requested changes
There are a few questions that need answering around accessibility/inclusiveness. I'd appreciate some input from your PM.

2020-08-05 16:08 UTC, smarkey commented on packages/f-registration/src/components/tests/Registration.test.js
> +                // Assert
Should there be an assertion to ensure that the field either gets cleared or remains populated (depending on requirements) on failure event emission and presentation of the validation error message?

2020-08-05 16:11 UTC, philgoff commented on packages/f-registration/src/components/Registration.vue
> +                        First name exceeds 50 chars
yes, I would say use Characters. Chars is a developer term.

2020-08-05 16:11 UTC, philgoff commented on packages/f-registration/src/components/Registration.vue
> +                        Last name exceeds 50 chars
yes, I would say use Characters. Chars is a developer term.

2020-08-05 16:11 UTC, philgoff commented on packages/f-registration/src/components/Registration.vue
> +    return /^[a-zA-Z'-]*$/.test(value);
@adamashton One to take back to Aaron and mention other accented characters or those using different alphabets.

2020-08-05 16:11 UTC, philgoff commented on packages/f-registration/src/components/tests/Registration.test.js
> +
Where is the NameMaxLengthError check?

2020-08-05 16:11 UTC, philgoff commented on packages/f-registration/src/components/tests/Registration.test.js
> +
Could we switch up the checks between first name and last name fields, please?

2020-08-05 16:14 UTC, smarkey commented on packages/f-registration/src/components/Registration.vue
> +                        First name exceeds 50 chars
Non-blocking, but I've brought this to Aaron:

```
It came up on the PR that the use of the word "chars" isn't particularly user friendly. Additionally since it's not a word in the dictionary it may be not particularly accessible when you consider screen readers will be reading that out.
Do you know who provided the designs/copy so I can just query it with them?
```

2020-08-05 16:17 UTC, xander-marjoram commented on packages/f-registration/src/components/Registration.vue
> +    return /^[a-zA-Z'-]*$/.test(value);
I think a better approach may be to instead _exclude_ certain characters, like `/^[^\[\]{}()#\/\\]$/`?

2020-08-06 08:43 UTC, ashleynolan commented on packages/f-registration/src/components/Registration.vue
> +const validCharsInName = value => {
Probably tidier to put this under a `methods` section of the default export below, as that's what we tend to do in other components

2020-08-06 08:44 UTC, ashleynolan commented on packages/f-registration/src/components/Registration.vue
> +// Returns true if there are no invalid chars in value. Valid chars are: a-z, A-Z, apostrophe, hyphen
Can you make sure this comment is in JSDoc format (we're starting to try and standardise our comments a bit more).

Usually can get a JSDoc extension that helps with this too.

2020-08-06 08:45 UTC, adamashton commented
Closing PR for now as we work out the final validation rules.

2020-08-06 08:45 UTC, closed without merging

2020-08-06 10:15 UTC, minrwhite commented on packages/f-registration/src/components/Registration.vue
> +    return /^[a-zA-Z'-]*$/.test(value);
Accented characters will be disallowed from an allowlist unless the unicode `u` flag is used anyhow, in which case IMO the list of excluded characters would be of similar length to the list of included characters (for example, would you want to allow block-drawing characters? emoji?).

It may be worth looking into using [Unicode property escapes](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Unicode_Property_Escapes), though given as those have only been possible in the last couple of versions of most browsers, and not at all in IE11, a fallback to a series of allowed unicode value ranges (e.g. `[\uXXXX-\uXXXX]`) should perhaps be used instead.