V0.4.1: Add tests for f-card computed properties
justeattakeaway/fozzie-components pull request #321
Opened 2020-09-17 14:17 UTC by FayeCarter

Tests added for f-card computed properties.

- [X] Unit tests have been [created|updated]

2020-09-17 14:25 UTC, siggerzz commented on packages/f-card/src/components/tests/Card.test.js
> +        let mockedLocale;
Are we able to use `const` for some of these?

2020-09-17 14:26 UTC, SachaZvetelman reviewed
Good first PR, @FayeCarter, nice job 👏

2020-09-17 14:26 UTC, SachaZvetelman commented on packages/f-card/CHANGELOG.md
> +- Tests for f-card computed properties.
Nit: let's write `f-card` (wrap in "`").

2020-09-17 14:26 UTC, SachaZvetelman commented on packages/f-card/src/components/tests/Card.test.js
> +jest.mock('@justeat/f-services');
Not sure if it works, but if it does, can we move the `import` on top of this `jest.mock` line so we keep all the imports together?

2020-09-17 14:26 UTC, SachaZvetelman commented on packages/f-card/src/components/tests/Card.test.js
> +        let mockedTennats;
Typo: `mockedTenants`.

2020-09-17 14:26 UTC, SachaZvetelman commented on packages/f-card/src/components/tests/Card.test.js
> +                const mockedI18n = () => 'en-AU'
Probably worth extracting `en-AU` to a `const` since we're using it everywhere in the file.

2020-09-17 14:26 UTC, SachaZvetelman commented on packages/f-card/src/components/tests/Card.test.js
> +        let mockedLocale;
Personal preference, but I'd actually only prefix with `mocked` those that are actually mocks. In this case, unless I'm wrong, `mockedLocale` is just a hardcoded locale you're using (`en-AU`).

2020-09-17 14:28 UTC, siggerzz commented on packages/f-card/package.json
> +  "version": "0.4.1",
I _think_ we only do patches (incrementing 3rd digit) for bug fixes?

I usually do a minor release for tests, but perhaps @ashleynolan can confirm 👍

2020-09-17 14:29 UTC, siggerzz commented on packages/f-card/src/components/tests/Card.test.js
> +            mockedTennats = {
Change to `mockedTenants`

2020-09-17 14:30 UTC, siggerzz requested changes
Great job! 🎉 

Just a few minor comments, but looks fine otherwise!

2020-09-17 15:08 UTC, DamianMullins commented on packages/f-card/package.json
> +  "version": "0.4.1",
Patch versions are for backwards compatible bug fixes. This one should be a minor version bump as you say @siggerzz.

2020-09-17 15:08 UTC, DamianMullins commented on packages/f-card/package.json
> +  "version": "0.4.1",
https://semver.org

2020-09-17 15:09 UTC, DamianMullins commented on packages/f-card/package.json
> +  "version": "0.4.1",
Saying that, if the changes here are only for the tests then maybe it should be a minor version bump as nothing will have changed for the end-user.

2020-09-17 15:35 UTC, FayeCarter commented on packages/f-card/src/components/tests/Card.test.js
> +        let mockedLocale;
Hi, I've moved all of the variables in the beforeEach to consts. Is that what you meant?

2020-09-18 08:20 UTC, siggerzz approved these changes

2020-09-18 10:28 UTC, BanksySan approved these changes

2020-09-18 10:36 UTC, merged