generator-component@v1.4.0 - added accessibility test template
justeattakeaway/fozzie-components pull request #362
Opened 2020-10-13 13:32 UTC by LTurns

In the generator component: 

### Added
- Axe Accessibility Spec template in its own Accessibility folder

### Changed
- Refactored test by moving conditional statement from axe-accessibility.spec to axe-helper

2020-10-13 13:39 UTC, siggerzz commented on packages/generator-component/generators/app/index.js
> +
Nit: This white space can be removed

2020-10-13 13:39 UTC, siggerzz commented on packages/generator-component/generators/app/templates/test/specs/accessibility/axe-accessibility.spec.js
> +    it('a11y - should test f-registration component WCAG compliance', () => {
This string still mentions f-registration

2020-10-13 13:39 UTC, siggerzz requested changes
Minor comments, but looks good otherwise!

2020-10-13 13:41 UTC, LTurns commented on packages/generator-component/generators/app/templates/test/specs/accessibility/axe-accessibility.spec.js
> +    it('a11y - should test f-registration component WCAG compliance', () => {
ah well spotted, will change now!

2020-10-13 13:49 UTC, simonsandersje submitted a review, later dismissed
LGTM - apart from Ben's comment about the f-reg mention

2020-10-13 13:55 UTC, siggerzz submitted a review, later dismissed
🎉

2020-10-13 14:09 UTC, SachaZvetelman commented on packages/generator-component/generators/app/templates/test/specs/accessibility/axe-accessibility.spec.js
> +        if (axeResults.violations.length > 0) {
I personally think having logic (e.g. conditionals, loops) within tests is not a good idea. Is this something we must have or can we find a way to avoid this? cc @LTurns and @siggerzz.

2020-10-13 14:20 UTC, siggerzz commented on packages/generator-component/generators/app/templates/test/specs/accessibility/axe-accessibility.spec.js
> +        if (axeResults.violations.length > 0) {
Yeah, this is mandatory. A11y tests should only fail if there are any Axe violations. All tests look identical, the only difference is the component that gets loaded in the page.

2020-10-13 14:41 UTC, SachaZvetelman commented on packages/generator-component/generators/app/templates/test/specs/accessibility/axe-accessibility.spec.js
> +        if (axeResults.violations.length > 0) {
Well, we could potentially amend `processResults` so it checks if there are violations inside it, instead of requiring putting this conditional in every test we want to write in the future for accessibility. Unless I'm wrong here.
I'm normally quite against logic in tests, because...Who's testing the logic in those tests is correct?
I'm happy to get more opinions here, and if most of the people are ok with having conditionals in tests, then I'll shut up 😬, but in general, it's not a practice I'm very happy with.

2020-10-13 14:42 UTC, SachaZvetelman commented on packages/generator-component/generators/app/templates/test/specs/accessibility/axe-accessibility.spec.js
> +        if (axeResults.violations.length > 0) {
Sorry, one more question. Is this the one and only test we'll have for accessibility in our components or are we going to be writing more tests in the future? If it's this one and nothing else, not a big deal and ignore my comment above.

2020-10-13 14:58 UTC, DamianMullins commented on packages/generator-component/generators/app/templates/test/specs/accessibility/axe-accessibility.spec.js
> +        if (axeResults.violations.length > 0) {
I'm with @SachaZvetelman on this, conditions in tests should be avoided as it complicates the tests, makes them harder to follow, and could lead to failures which have nothing to do with the SUT. 

As @SachaZvetelman mentioned, why not wrap up the `processResults` call in the `getAccessibilityTestResults` function? I', wondering if you could check the violations and do the additional work before returning?

2020-10-13 15:17 UTC, siggerzz commented on packages/generator-component/generators/app/templates/test/specs/accessibility/axe-accessibility.spec.js
> +        if (axeResults.violations.length > 0) {
@SachaZvetelman Yeah, this _should_ be the only accessibility test for most components. Happy to address this though :)

2020-10-13 15:18 UTC, LTurns commented on packages/generator-component/generators/app/templates/test/specs/accessibility/axe-accessibility.spec.js
> +        if (axeResults.violations.length > 0) {
Yeah I agree there's probably a simple way to do this, will take a look at the logic now! :)

2020-10-13 18:55 UTC, ashleynolan commented
@LTurns Just an FYI – I've also raised a PR for the generator just now with some small updates. Mine are quite minor changes and saw you were addressing comments, so put mine as `v1.2.0` too incase it gets approved first, but happy to change if this is ready for review/merge (and I'll merge your changes into mine then).

2020-10-14 07:31 UTC, LTurns commented
> @LTurns Just an FYI – I've also raised a PR for the generator just now with some small updates. Mine are quite minor changes and saw you were addressing comments, so put mine as `v1.2.0` too incase it gets approved first, but happy to change if this is ready for review/merge (and I'll merge your changes into mine then).

No problem @ashleynolan, I'm still testing my changes locally so probably unlikely to merge before you. Will rebase before I push up again. 👍

2020-10-15 13:21 UTC, siggerzz commented on package.json
> +    "chromedriver": "85.0.1",
This can be reverted

2020-10-15 13:22 UTC, siggerzz commented on packages/f-form-field/test/specs/README.md
> +# Usage
This can be removed

2020-10-15 13:22 UTC, siggerzz commented on packages/generator-component/CHANGELOG.md
> +*October 14, 2020*
Date needs updating

2020-10-15 13:23 UTC, siggerzz commented on test/utils/axe-helper.js
> +};
Add a new line at the end of this one

2020-10-15 13:23 UTC, siggerzz requested changes
Few minor changes!

2020-10-15 13:39 UTC, LTurns commented
> Few minor changes!

Just changed @siggerzz thank you!

2020-10-15 14:04 UTC, siggerzz submitted a review, later dismissed

2020-10-15 16:52 UTC, siggerzz approved these changes

2020-10-16 07:29 UTC, simonsandersje approved these changes

2020-10-16 08:19 UTC, merged