f-registration@v0.37.0
justeattakeaway/fozzie-components pull request #365
Opened 2020-10-13 14:30 UTC by luke-andrew-parry

This PR makes a number of styling tweaks to align closer to the Pie designs. There will be further changes to follow when amendments have been made to the `f-form-field` component.

## UI Review Checks
iPhone (iOS14 Safari)

![image](https://user-images.githubusercontent.com/3658456/95963852-17fa4a80-0e00-11eb-9a72-7d4d8f3ea65f.png)

Google Pixel 4 (Android 11 Chrome)

![image](https://user-images.githubusercontent.com/3658456/95964200-7293a680-0e00-11eb-9b48-31f567b1a6ac.png)

## Browsers Tested

- [x] Chrome (latest)
- [x] Mobile

2020-10-13 18:17 UTC, ashleynolan commented on packages/f-registration/src/components/Registration.vue
> +.c-loginLink, .c-legal-hyperlinks {
Smal NIT: Can you put these selectors on separate lines?  Just makes it a bit clearer

2020-10-13 18:18 UTC, ashleynolan commented on packages/f-registration/src/demo/Index.vue
> -                preLinkText: 'Already have an account?',
Is it worth getting rid of the reference to this in the template (.vue file)

2020-10-14 15:00 UTC, ashleynolan commented on packages/f-registration/src/components/Button.vue
> +$btn-default-weight                 : bold;
Can you change this to `$font-weight-bold`? That links to a variable that [handles this in fozzie](https://github.com/justeat/fozzie/blob/master/src/scss/settings/_variables.scss#L57)

2020-10-14 15:02 UTC, ashleynolan commented on packages/f-registration/src/components/Button.vue
> +$btn-default-font-size              : 20px;
Should use `heading-s` here (so it links into the font-map keys in fozzie). I'm pretty sure you could then just remove the line-height declation on line 86, as the mixin below should output `line-height: 1.5` in the styles when it's called.

2020-10-14 15:07 UTC, ashleynolan commented on packages/f-registration/src/components/Registration.vue
> +            <div
It's more semantic to keep this text in a paragraph tag (as links with no block tag `p` don't always read correctly to screenreaders).

is this change style related?

2020-10-14 15:08 UTC, ashleynolan commented on packages/f-registration/src/components/Registration.vue
> +            <div :class="$style['c-legal-hyperlinks']">
Same here as above – these should stay as `p` tags ideally. If it's style related, we probably need to look at the styles and change those a little.

2020-10-14 15:09 UTC, ashleynolan commented on packages/f-registration/src/components/Registration.vue
> +        font-weight: bold;
Should use `$font-weight-bold` here instead of `bold`

2020-10-14 15:10 UTC, ashleynolan commented on packages/f-registration/src/components/Registration.vue
> +    padding-top: 55px;
Probably worth checking with Tom, but is this padding specific to the registration component?

2020-10-14 15:11 UTC, ashleynolan commented on packages/f-registration/src/components/Registration.vue
> +        padding-bottom: 32px;
Can use `spacing(x4)` here instead of `32px`

2020-10-14 15:12 UTC, ashleynolan commented on packages/f-registration/src/components/Registration.vue
> +    padding-bottom: 50px;
We tend to use padding as a multiple of 8px throughout the site (defined by design). So this would likely either be `spacing(x6)` or  `spacing(x7)` (for 48px or 56px) depending on which fits the component best.

2020-10-14 15:15 UTC, ashleynolan commented on packages/f-registration/src/components/Registration.vue
> +    position: relative;
I'd be tempted to make this icon `position: absolute` and pass the icon inside the card component (as `absolute` is a bit less flakey to change than relatively positioned elements).

2020-10-14 15:15 UTC, ashleynolan commented on packages/f-registration/src/components/Registration.vue
> +    @include media('<mid') {
Can you put this media query below the margin and display lines below (just our convention in the styles)

2020-10-15 13:24 UTC, luke-andrew-parry commented on packages/f-registration/src/components/Registration.vue
> +            <div
Yeah, it's style-related as it seems to add a bunch of padding to `p` tags. I'll revert and we can address the styles assigned to these.

2020-10-15 13:24 UTC, luke-andrew-parry commented on packages/f-registration/src/components/Registration.vue
> +            <div :class="$style['c-legal-hyperlinks']">
Yeah, it's style-related as it seems to add a bunch of padding to `p` tags.

2020-10-15 13:26 UTC, luke-andrew-parry commented on packages/f-registration/src/components/Registration.vue
> +    padding-top: 55px;
I added this in to give some extra space between the bag icon and the title.

2020-10-15 13:28 UTC, luke-andrew-parry commented on packages/f-registration/src/components/Registration.vue
> +    position: relative;
Sure,  I'll have a look at this.

2020-10-16 13:23 UTC, luke-andrew-parry commented on packages/f-registration/src/components/Registration.vue
> +    position: relative;
@ashleynolan I've had a look at changing this to be absolute and it's turning out to be quite fiddly and from what I can see requiring a number of different top/left values base on screen size. 

Did you have a specific solution in mind?

2020-10-16 14:10 UTC, luke-andrew-parry commented on packages/f-registration/src/components/Registration.vue
> +    padding-top: 55px;
Yeah, it's style-related as it seems to add a bunch of padding to `p` tags. I'll revert and we can address the styles assigned to these.

2020-10-16 15:00 UTC, adamashton commented on packages/f-registration/src/tenants/en-GB.js
> +        createAccountTitle: 'Create account',
Is this coming from the zeplin designs? The spreadsheet I used might have been wrong again.

2020-10-16 15:01 UTC, luke-andrew-parry commented on packages/f-registration/src/tenants/en-GB.js
> +        createAccountTitle: 'Create account',
Yep. I'd get access to the zeplin designs and use that as the source of truth.

2020-10-16 15:06 UTC, adamashton submitted a review, later dismissed

2020-10-19 11:02 UTC, ashleynolan commented on packages/f-registration/CHANGELOG.md
> +*October 16, 2020*
Super NIT – can you bump the date and put a line break between the date and the first title on line 9?

2020-10-19 11:05 UTC, ashleynolan commented on packages/f-registration/src/demo/Index.vue
> +    background: #f9fafb;
Can this styling not be applied to the registration component? You could potentially give the outside div in `Registration.vue` a classname `c-registration` and then put the background colour on that I think.

2020-10-19 11:06 UTC, ashleynolan commented on packages/f-registration/src/demo/Index.vue
>  .registration-form {
Similarly for this – you could add a class `c-registration-form` on the form element in `Registration.vue` and put this spacing on that class.

2020-10-20 08:10 UTC, luke-andrew-parry commented on packages/f-registration/src/demo/Index.vue
> +    background: #f9fafb;
These styles aren't related to the registration component. The background colour is the greyish colour for the containing page. I've moved the other style into the component though.

2020-10-23 10:41 UTC, simonsandersje submitted a review, later dismissed

2020-10-23 10:44 UTC, AlixRichards submitted a review, later dismissed

2020-10-23 10:45 UTC, tommcclean submitted a review, later dismissed

2020-10-23 10:45 UTC, ashleynolan commented on packages/f-registration/src/components/Registration.vue
> +        :class="$style['c-registration-form']">
Could this just be `c-registration`? (the extra dash in our naming scheme implies there's a parent class of `c-registration` above `c-registration-form`)

2020-10-23 10:48 UTC, ashleynolan commented on packages/f-registration/src/components/Registration.vue
> +                    class="submit-button-padding"
I'd go with `c-registration-btn` for this (here's our [naming scheme for classes](https://fozzie.just-eat.com/documentation/css/css-naming) too – dashes indicate element relationship and we use camelCase for joined words)

2020-10-23 10:52 UTC, ashleynolan reviewed
Couple of super small classname suggestions – then LGTM

2020-10-23 10:52 UTC, luke-andrew-parry commented on packages/f-registration/src/components/Registration.vue
> +                    class="submit-button-padding"
I actually got rid of this style and forgot to remove the `class` attribute.

2020-10-23 10:53 UTC, ashleynolan requested changes
Couple of super small classname suggestions – then LGTM

2020-10-23 10:58 UTC, ashleynolan approved these changes

2020-10-23 11:00 UTC, AlixRichards approved these changes

2020-10-23 11:08 UTC, merged