f-checkout@0.4.0 - Replicate Collection layout
justeattakeaway/fozzie-components pull request #381
Opened 2020-10-21 14:17 UTC by FayeCarter

Allows `f-checkout` to be used for logged in Collection as well as Delivery.

*There will be more changes to follow with `f-form-field` and `f-button` updates/creation*

### Added
- Address component to be displayed if `checkoutMethod` is set to 'Delivery'.

### Removed
- Address related form fields from `f-checkout`.

### Changed
- Checkout Component to replicate Collection and Delivery in ConsumerWeb.
- Selector to uses `method` prop to change label text.

## UI Review Checks
Collection | Delivery
|---|---|
![image](https://user-images.githubusercontent.com/24740015/96967915-16b7d480-1508-11eb-9f1a-756a03853abe.png) | ![image](https://user-images.githubusercontent.com/24740015/96967969-27684a80-1508-11eb-96b0-7ed9fc6c6638.png)

- [ ] README and/or UI Documentation has been [created|updated]
- [x] Unit tests have been [created|updated]
- [ ] This code has been checked with regard to [our accessibility standards](http://fozzie.just-eat.com/documentation/general/accessibility/checklist)

2020-10-22 10:28 UTC, simonsandersje submitted a review, later dismissed

2020-10-22 10:48 UTC, ashleynolan requested changes

2020-10-22 10:48 UTC, ashleynolan commented on packages/f-checkout/src/components/Address.vue
> +        <div :class="$style['l-addressGroup']">
Not sure if there could be an accessibility benefit to defining this component as a fieldset? (as it is a group of related fields)

Doesn't need to to be resolved by this PR, but would be good to look into

2020-10-22 10:48 UTC, ashleynolan commented on packages/f-checkout/src/components/Address.vue
> +                input-type="text"
If you want to save yourself some code, `text` is the default type for the form-field component, so you shouldn't have to define the prop (and for the references below)

2020-10-22 10:48 UTC, ashleynolan commented on packages/f-checkout/src/components/Address.vue
> +                :class="$style['c-formField']"
More a question than a comment – does defining this classname here, does it effectively add two `c-formField` classes to the component? (as `c-formField` is also added to the `div` as part of the f-form-field component)

2020-10-22 10:48 UTC, ashleynolan commented on packages/f-checkout/src/components/Address.vue
> +        height: 50px;
Any changes to the height of the inputs should happen as part of the `f-form-field` component (so that the height of `input` elements are consistent everywhere (I'm updating that to the PIE version today, so that might be one of the values that updates :) )

2020-10-22 10:48 UTC, ashleynolan commented on packages/f-checkout/src/components/Address.vue
> +        @include font-size(body-l);
Same with the label – should be consistent across all form-fields

2020-10-22 10:50 UTC, ashleynolan commented on packages/f-checkout/src/components/Selector.vue
> +        method: {
`method` is a bit of a loaded word in JS – I'd probably call this `orderType` or `orderMethod`?

2020-10-22 10:58 UTC, minrwhite commented on packages/f-checkout/src/constants.js
> +export const VALID_CHECKOUT_METHOD = ['Collection', 'Delivery'];
I'd say it's worth separating out the values from this array into individual `const`s that are also exported that you can then import for use in comparisons like the `v-if` in address-block. Additionally, you should probably re-export these in `index.js` as named exports so that consuming applications can use the values directly.

2020-10-22 10:58 UTC, minrwhite commented on packages/f-checkout/stories/Checkout.stories.js
> +import { withKnobs, select } from '@storybook/addon-knobs';
Knobs are deprecated as of storybook v6, please look into using controls if possible.

2020-10-22 10:58 UTC, minrwhite commented on packages/f-checkout/src/components/Address.vue
> +    div {
Is this intended to apply to every `div` nested within an element with the `l-addressGroup` style applied? Even those nested within each other? It'd be better to specify a class here, if possible, unless there's a good reason for it.

2020-10-22 12:41 UTC, FayeCarter commented on packages/f-checkout/src/components/Address.vue
> +        <div :class="$style['l-addressGroup']">
Cool, I'll have a look

2020-10-22 12:47 UTC, FayeCarter commented on packages/f-checkout/src/components/Selector.vue
> +        method: {
Good point 😂

2020-10-22 12:48 UTC, FayeCarter commented on packages/f-checkout/src/constants.js
> +export const VALID_CHECKOUT_METHOD = ['Collection', 'Delivery'];
Cool, I'll give this a go.

2020-10-22 12:49 UTC, FayeCarter commented on packages/f-checkout/src/components/Address.vue
> +    div {
No good reason, just unnoticed 😂. Thanks

2020-10-22 15:30 UTC, FayeCarter commented on packages/f-checkout/src/components/Address.vue
> +                :class="$style['c-formField']"
It does this 😬 
![image](https://user-images.githubusercontent.com/24740015/96894866-cdbe3c80-1483-11eb-851b-2dd515b41faa.png)
It's now removed.

2020-10-22 15:51 UTC, minrwhite submitted a review, later dismissed

2020-10-22 15:51 UTC, minrwhite commented on packages/f-checkout/src/components/Selector.vue
> +            {{ orderMethod }} time
Not an immediate concern, but at some point this should be made Localization (L10n) compatible, as even though this might not roll out to EU in lieu of them moving to takeaway's legacy platform, ANZ use the term 'pickup' rather than collection.

2020-10-22 16:19 UTC, FayeCarter commented on packages/f-checkout/src/components/Address.vue
> +        height: 50px;
I've removed the height modification, it looks a little bit weird at the moment but I can update from the PIE design in another PR right?

2020-10-23 07:34 UTC, ashleynolan commented on packages/f-checkout/src/components/Address.vue
> +        height: 50px;
Yeh – this should update when the new f-form-field changes come in too (or if you need to change them, can work out how to change through a prop to that component)

2020-10-23 07:36 UTC, ashleynolan commented on packages/f-checkout/src/components/Address.vue
> +        <fieldset :class="$style['l-addressGroup']">
I'd change the classname here to be `c-addressGroup`. We tend to only use `l-` for global layout helper classes (so those aren't used very often).

2020-10-23 07:37 UTC, ashleynolan commented on packages/f-checkout/src/components/Address.vue
> +                :class="$style['c-checkout-formField']"
As you have the addressGroup class above now, you could use `c-addressGroup-formField` here to keep all the classname's in this SFC relative to this address component?

2020-10-23 07:38 UTC, ashleynolan reviewed
Looks - good. Couple of super small class name suggestions, otherwise LGTM :shipit:

2020-10-23 07:57 UTC, minrwhite approved these changes

2020-10-23 08:06 UTC, ashleynolan approved these changes

2020-10-23 08:06 UTC, merged