f-content-cards@v2.2.0-beta.2 - Adds groupCards option / prop to content cards to display by group title
justeattakeaway/fozzie-components pull request #384
Opened 2020-10-22 15:22 UTC by matthewhardern

Adds new callback for groups, function for handling grouped card impressions, plus new function for handling content cards. 
Adds template changes to support looping over groups.

Minor style changes to make cards line up both in height and across with margin in the design. ( can be removed but needed it to see visually what I am doing)  

- [x] README and/or UI Documentation has been [created|updated]
- [x] Unit tests have been [created|updated]

As a side note I am not running browser tests as part of this PR as a this will be handled in my next PR for this component with PIE changes.

2020-10-27 11:43 UTC, dandel10n commented on packages/f-content-cards/src/components/cardTemplates/CardContainer.vue
> +        //height: 100%;
Should this be removed if not needed anymore?

2020-10-27 11:44 UTC, minrwhite commented on CHANGELOG.md
Add an extra newline between version entries, please

2020-10-27 11:44 UTC, minrwhite commented on packages/f-content-cards/CHANGELOG.md
>  Latest (to be added to next release)
Concatenate the entries below into the one above.

2020-10-27 11:44 UTC, minrwhite commented on packages/f-content-cards/src/components/ContentCards.vue
> +                        :data-test-id="testIdForItemWithIndex(cardIndex)"
We probably should do something different with grouped cards, as the same index is certain to reoccur between different groups of cards, leading to cards with identical test ids. Maybe modifying the `testIdForItemWithIndex()` function to accept an optional `groupIndex` parameter also, could solve this.

2020-10-27 11:44 UTC, minrwhite commented on packages/f-content-cards/src/components/ContentCards.vue
> +                    :class="[$style['c-contentCards--group-title']]"
Can we add a non-`$style` wrapped `'c-contentCards--group-title'` class here, to allow for externally introduced styling, please?

2020-10-27 11:44 UTC, minrwhite commented on packages/f-content-cards/src/components/cardTemplates/CardContainer.vue
> +        //height: 100%;
Remove rather than comment please, if this isn't needed.

2020-10-27 11:44 UTC, minrwhite commented on packages/f-content-cards/stories/mockData/cards.js
> +export function timeRange10HoursAroundNow () {
Do we need this exported?

2020-10-27 13:23 UTC, matthewhardern commented on packages/f-content-cards/src/components/ContentCards.vue
> +                        :data-test-id="testIdForItemWithIndex(cardIndex)"
Thanks missed this one, will add optional parameter and handle it as suggested.

2020-10-27 13:23 UTC, matthewhardern commented on packages/f-content-cards/src/components/ContentCards.vue
> +                    :class="[$style['c-contentCards--group-title']]"
will do

2020-10-27 13:23 UTC, matthewhardern commented on packages/f-content-cards/src/components/cardTemplates/CardContainer.vue
> +        //height: 100%;
Yep my mistake, removing

2020-10-27 13:25 UTC, matthewhardern commented on packages/f-content-cards/stories/mockData/cards.js
> +export function timeRange10HoursAroundNow () {
No we don't it was exported as part of some local development work with mocking the API's. I shall remove it and put it back to previous state.

2020-10-27 13:38 UTC, matthewhardern commented on packages/f-content-cards/src/components/cardTemplates/CardContainer.vue
> +        //height: 100%;
fixed

2020-10-27 13:39 UTC, matthewhardern commented on packages/f-content-cards/stories/mockData/cards.js
> +export function timeRange10HoursAroundNow () {
removed

2020-10-27 13:40 UTC, matthewhardern commented on packages/f-content-cards/src/components/ContentCards.vue
> +                    :class="[$style['c-contentCards--group-title']]"
added to allow external styles

2020-10-27 13:40 UTC, matthewhardern commented on packages/f-content-cards/src/components/ContentCards.vue
> +                        :data-test-id="testIdForItemWithIndex(cardIndex)"
added a optional parameter and additional test

2020-10-27 13:41 UTC, matthewhardern commented on packages/f-content-cards/CHANGELOG.md
>  Latest (to be added to next release)
they are now on one line

2020-10-27 13:41 UTC, matthewhardern commented on CHANGELOG.md
added the extra new line

2020-10-27 13:41 UTC, matthewhardern commented on packages/f-content-cards/src/components/cardTemplates/CardContainer.vue
> +        //height: 100%;
thanks have removed

2020-10-27 16:06 UTC, minrwhite commented on packages/f-content-cards/CHANGELOG.md
>  Latest (to be added to next release)
Thanks, but that's not quite what I meant - everything below the `Latest (to be added to next release)` should be added into the `v2.2.0-beta.2` changelog; `Added` entries added on their own lines alongside those that exist, `Changed` entry added on its own.

2020-10-27 16:09 UTC, minrwhite commented on packages/f-content-cards/src/components/tests/ContentCards.test.js
> +        it('should generate test id attributes on child content cards components within a group', async () => {
💯

2020-10-27 16:11 UTC, matthewhardern commented on packages/f-content-cards/CHANGELOG.md
>  Latest (to be added to next release)
Sorry for the confusion, get what you mean now sorry :)

2020-10-27 16:27 UTC, minrwhite submitted a review, later dismissed

2020-10-27 16:28 UTC, matthewhardern commented on packages/f-content-cards/CHANGELOG.md
>  Latest (to be added to next release)
changed

2020-10-27 16:44 UTC, dandel10n approved these changes

2020-10-27 20:16 UTC, dandel10n requested changes
Noticed that you haven't increased the version in package.json in the project root to 2.9.0 as noted in changelog. Actually, because it is only gitignore change I am not sure if the version bump is needed at all. Maybe it is better to leave a note in changelog "Latest (to be added to next release)" instead of "v2.9.0" on line 6.

2020-10-27 21:29 UTC, matthewhardern commented
@dandel10n agreed, change made to the changelog. 👍

2020-10-28 10:43 UTC, minrwhite approved these changes

2020-10-28 14:10 UTC, dandel10n approved these changes

2020-10-28 14:15 UTC, merged