f-checkout@v0.6.0 – Test added for visibility on displayed fields.
justeattakeaway/fozzie-components pull request #395
Opened 2020-10-27 17:02 UTC by JoshuaNg2332

---

This PR is to add tests for f-checkout. This test confirms the existence of fields on the page.

---

## Browsers Tested

- [X] Chrome (latest)

2020-10-27 21:02 UTC, matthewhardern commented on packages/f-checkout/test/specs/component/f-checkout.component.spec.js
> +        var areFieldsDisplayed = function(){
You can use `const` here as you never re-assign `areFieldsDisplayed`

2020-10-27 21:07 UTC, matthewhardern commented on packages/f-checkout/test/specs/component/f-checkout.component.spec.js
> +            var fields = CheckoutComponent.isCheckoutFormFieldsDisplayed();
`isCheckoutFormFieldsDisplayed` does not currently exist in the imported utilities, and hence the reason for CI tests failing, did you forget to add it to git?

2020-10-27 21:09 UTC, matthewhardern commented on packages/f-checkout/test/specs/component/f-checkout.component.spec.js
> +            for(i = 0; i < fields.values.length; i++){
Having logic inside tests In my personal opinion is not best practice. This logic should be moved to a function that itself can be tested. This prevents the test failing because of this logic.

2020-10-28 08:09 UTC, SachaZvetelman reviewed
A few comments. Feel free to ping me if you have any questions, of course.
Make sure you set up ESLint on your VS Code. There are many issues that will be automatically fixed for you when saving the file (e.g. spacing), and it will warn you of important things such as "you can use `const` here".

2020-10-28 08:09 UTC, SachaZvetelman commented on packages/f-checkout/test/specs/component/f-checkout.component.spec.js
> +            for(i = 0; i < fields.values.length; i++){
Normally we try not to "create new functionality or logic" inside a test. For example, you are creating a function, having conditionals and loops. The problem with this approach is that nothing is testing your test if it makes sense. Happy to explain more on a Hangouts, if you want!

2020-10-28 08:09 UTC, SachaZvetelman commented on packages/f-checkout/test/specs/component/f-checkout.component.spec.js
> +                    console.log(fields);
Nit: remove from the test once it's ready 😄

2020-10-28 08:09 UTC, SachaZvetelman commented on packages/f-checkout/test/specs/component/f-checkout.component.spec.js
> +                if(fields[i]==false){
I'm not entirely sure what we're checking here. Could you please clarify?
At the same time, remember the difference between `==` and `===`. 
In most scenarios, `if (!fields[i]) {` would suffice.

2020-10-28 08:33 UTC, kevinrodrigues commented on packages/f-checkout/test/specs/component/f-checkout.component.spec.js
> +    it('should display all fields', () => {
I think you could switch the entire contents of this test out for a simpler test. You would only need to test that that the individual fields exist, similar idea to what you are already doing. The [util](https://github.com/justeat/fozzie-components/blob/12d5aab2756c5c38dc186d150e5a745e4a8824a1/packages/f-checkout/test-utils/component-objects/f-checkout.component.js) contains all the data test IDs for you to be able to either loop or individually test them without the `areFieldsDisplayed` setup.

2020-10-28 08:34 UTC, xander-marjoram commented on packages/f-checkout/test/specs/component/f-checkout.component.spec.js
> +            for(i = 0; i < fields.values.length; i++){
It looks like you're checking a list of boolean values to see if any of them are false, is that correct?

If so, you could use a function like [`filter`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter) to check this rather than using a for-loop to iterate through the array.

```javascript
const fields = CheckoutComponent.isCheckoutFormFieldsDisplayed();
const hiddenFields = fields.filter(f => !f); // This removes any "truthy" elements
expect(hiddenFields.length).toBe(0);
```

Also, nit: I would rename `isCheckoutFormFieldsDisplayed` to something like `areFormFieldsDisplayed`. You could even move the bit where you filter it down into the method itself, and just return true or false inside there. 😄

2020-10-28 08:36 UTC, kevinrodrigues commented on packages/f-checkout/test/specs/component/f-checkout.component.spec.js
> +            var fields = CheckoutComponent.isCheckoutFormFieldsDisplayed();
Looks to me that this is exported ok?

2020-10-28 08:44 UTC, matthewhardern commented on packages/f-checkout/test/specs/component/f-checkout.component.spec.js
> +            var fields = CheckoutComponent.isCheckoutFormFieldsDisplayed();
On master `f-checkout.component` in the test-utils directory does not contain `isCheckoutFormFieldsDisplayed` unless I am mistaken? Also Circle CI error is because isCheckoutFormFieldsDisplayed is not a function. So assumed it was undefined, happy to be corrected though

2020-10-28 08:45 UTC, matthewhardern commented on packages/f-checkout/test/specs/component/f-checkout.component.spec.js
> +    it('should display all fields', () => {
The above is a good shout, not sure on opinions here, but you could do a `it.each` passing in the data test id's of all the fields.

2020-10-28 08:50 UTC, kevinrodrigues commented on packages/f-checkout/test/specs/component/f-checkout.component.spec.js
> +    it('should display all fields', () => {
`it.each` is something we would usually use here 👍

2020-10-28 08:53 UTC, kevinrodrigues commented on packages/f-checkout/test/specs/component/f-checkout.component.spec.js
> +            var fields = CheckoutComponent.isCheckoutFormFieldsDisplayed();
Looks ok to me on master, would need to pull it to see what was happening, it does seem to already be used in this file further up too tho.

2020-10-28 09:15 UTC, Festivejelly commented on packages/f-checkout/test/specs/component/f-checkout.component.spec.js
> +                    console.log(fields);
@SachaZvetelman where would you put this logic then? It cant live in the page object model. All this is doing is asserting if fields are displayed. Its not changing the path the test would take, only the outcome of the assertion.

2020-10-28 09:20 UTC, Festivejelly commented on packages/f-checkout/test/specs/component/f-checkout.component.spec.js
> +    it('should display all fields', () => {
Aka test.each i guess? https://jestjs.io/docs/en/api

Tbh we were struggling to find examples on how to do this because it.each isnt an available function.

Also the test i'ds dont seem to be in a collection so how would one pass each one in?

2020-10-28 09:21 UTC, SachaZvetelman commented on packages/f-checkout/test/specs/component/f-checkout.component.spec.js
> +                    console.log(fields);
@Festivejelly, my comment was about `console.log`, which shouldn't be there, since that is for dev purposes only. Or what part are you talking about exactly?

2020-10-28 09:22 UTC, matthewhardern commented on packages/f-checkout/test/specs/component/f-checkout.component.spec.js
> +    it('should display all fields', () => {
have a look at f-metadata `BrazeDispatcher.test.js` its got some good examples

2020-10-28 11:49 UTC, xander-marjoram commented on packages/f-checkout/test/specs/component/f-checkout.component.spec.js
> +    it('should display all fields', () => {
@Festivejelly Yes `it` and `test` are interchangeable

2020-10-28 11:52 UTC, Festivejelly commented on packages/f-checkout/test/specs/component/f-checkout.component.spec.js
> +    it('should display all fields', () => {
This is in Mocha. Your comments are relating to Jest afaik? We've added a new library to do a each on the it.

2020-10-28 11:54 UTC, xander-marjoram commented on packages/f-checkout/test/specs/component/f-checkout.component.spec.js
> +    it('should display all fields', () => {
I think we're picturing something along these lines
```javascript
it.each([
    'field1',
    'field2'
])('should display %s field', testId => {
    // Test that element with data-test-id=testId is displayed
});
```

2020-10-28 12:16 UTC, siggerzz commented on package.json
> +    "mocha-each": "^2.0.1",
You can remove the `^` from here 👍

2020-10-28 12:18 UTC, siggerzz commented on wdio.conf.js
> +    reporters: ['spec'],
This can be reverted

2020-10-28 12:18 UTC, siggerzz requested changes
Few minor comments, but otherwise looks good to me 🎉

2020-10-28 12:55 UTC, siggerzz submitted a review, later dismissed

2020-10-28 13:07 UTC, tommcclean submitted a review, later dismissed

2020-10-28 13:08 UTC, SachaZvetelman commented
Only one question, and probably because I'm missing something, but why are we adding Mocha? :)

2020-10-28 13:54 UTC, ashleynolan commented
Can you remove the JIRA ID's from your commit titles?

2020-10-28 13:54 UTC, ashleynolan requested changes
Just blocking this until the commit msgs are updated

2020-10-28 14:27 UTC, JoshuaNg2332 commented
> Just blocking this until the commit msgs are updated

@ashleynolan  Updated commit messages now.

2020-10-28 14:35 UTC, siggerzz commented
@SachaZvetelman Mocha has always been part of the framework, we're just adding an additional mocha plugin. Mocha is the test framework that's use by WebDriverIO. (in the same way Jest is used for unit tests, or how we use Specflow in C#) 👍

2020-10-28 15:01 UTC, SachaZvetelman commented
That's what I was missing: didn't know we were using Mocha with WebDriverIO. Now I do 😬

2020-10-28 17:21 UTC, siggerzz submitted a review, later dismissed

2020-10-30 11:06 UTC, simonsandersje commented on packages/f-checkout/CHANGELOG.md
> +*October 28, 2020*
Change to today's date before merging

2020-10-30 11:13 UTC, ashleynolan submitted a review, later dismissed

2020-10-30 11:15 UTC, kevinrodrigues submitted a review, later dismissed

2020-10-30 11:21 UTC, siggerzz submitted a review, later dismissed

2020-10-30 11:21 UTC, simonsandersje submitted a review, later dismissed

2020-10-30 11:49 UTC, SachaZvetelman commented on packages/f-checkout/test-utils/component-objects/f-checkout.component.js
> +    }
Sorry if I'm a bit late to the party, since you already have two approvals, but I feel this can be simplified.
For example, if you pass in the input as a parameter rather than the name, your function would pretty much be reduced to `return element.isDisplayed();`.

2020-10-30 11:51 UTC, SachaZvetelman commented on packages/f-checkout/test-utils/component-objects/f-checkout.component.js
> +    }
On a similar note, the function name should probably be singular in the end. You're checking that one given field is displayed, not all the checkout form fields are displayed, if it makes sense.

2020-10-30 12:04 UTC, JoshuaNg2332 commented on packages/f-checkout/test-utils/component-objects/f-checkout.component.js
> +    }
I've had a chat with @siggerzz & @Festivejelly about this and we wanted to have a single test that checks these in one go rather than having individual functions that check visibility. If these were split into individual functions as part of the same test, one failure would stop the execution of the rest of the test.

2020-10-30 12:06 UTC, SachaZvetelman commented on packages/f-checkout/test-utils/component-objects/f-checkout.component.js
> +    }
Hmmm, I think we're talking about different things here, hehe. Let's have a chat after my training, before we merge this, please.

2020-10-30 12:10 UTC, SachaZvetelman requested changes
Just setting this "request changes" to avoid an accidental merge before we discuss those outstanding comments

2020-10-30 15:14 UTC, siggerzz submitted a review, later dismissed

2020-10-30 15:18 UTC, SachaZvetelman submitted a review, later dismissed
Approved with a minor comment.

2020-10-30 15:18 UTC, SachaZvetelman commented on packages/f-checkout/test-utils/component-objects/f-checkout.component.js
> +// exports.mobileNumberInput = () => $('[data-test-id="input-mobile-number"]');
Please remove commented code.

2020-10-30 15:20 UTC, JoshuaNg2332 commented on packages/f-checkout/test-utils/component-objects/f-checkout.component.js
> +// exports.mobileNumberInput = () => $('[data-test-id="input-mobile-number"]');
Removed. 😄

2020-10-30 15:24 UTC, SachaZvetelman submitted a review, later dismissed

2020-11-02 10:13 UTC, siggerzz submitted a review, later dismissed

2020-11-02 10:17 UTC, siggerzz submitted a review, later dismissed

2020-11-02 10:52 UTC, ashleynolan commented on CHANGELOG.md
> +v2.9.0
You can delete the latest line above by the looks of it and make this:

```
v2.9.0
------------------------------
*November 2, 2020*

### Added
- Added `mocha-each` to package.json.
- Added an entry to gitignore to ignore some local development tools for mocking http requests
```

2020-11-02 10:53 UTC, ashleynolan reviewed
Super small comment then LGTM

2020-11-02 11:02 UTC, JoshuaNg2332 commented on CHANGELOG.md
> +v2.9.0
@ashleynolan I've had a look at this and thought that it follows the existing convention? The version number lives below the actual update and then the one above reading `Latest (to be added to next release)` needs to be there?
@siggerzz Do correct me if I'm wrong here?

2020-11-02 11:05 UTC, ashleynolan commented on CHANGELOG.md
> +v2.9.0
So the version number should be above each update. We use the `Latest` title to indicate that the package has been updated but didn't require a version bump, so those `CHANGELOG` entries get merged into the next release (so the `latest` changes there currently, merge into your release)

2020-11-02 11:07 UTC, ashleynolan commented on CHANGELOG.md
> +v2.9.0
Tbh, I'm not sure why there's a `latest` entry in the root of the mono repo anyway – it never gets released as such, so the version should just get bumped every change. So bit confusing – if you update it to be as I showed though that should resolve the issue.

2020-11-02 11:22 UTC, siggerzz approved these changes

2020-11-02 11:59 UTC, ashleynolan approved these changes

2020-11-02 11:59 UTC, ashleynolan commented
Happy for this to be merged as long as you've checked the build is ok on CircleCI.

2020-11-02 12:16 UTC, siggerzz commented
All good on CircleCI! - https://app.circleci.com/pipelines/github/justeat/fozzie-components/2118/workflows/6d8dc34c-fe01-4a93-8f6a-a47f7425ce9c

2020-11-02 12:16 UTC, merged