f-checkout@0.8.0 - Add server side and client side error handling
justeattakeaway/fozzie-components pull request #400
Opened 2020-10-29 11:26 UTC by FayeCarter

### Added
- Inline error handling to `Checkout` and `Address` components.
- Server side error handling.

## UI Review Checks
**Collection** | **Delivery** | **Server Error Messages**
|---|---|--|
![image](https://user-images.githubusercontent.com/24740015/97890504-82c6e380-1d25-11eb-96a5-0e6fcad9728f.png) | ![image](https://user-images.githubusercontent.com/24740015/97890377-61fe8e00-1d25-11eb-92e8-d32642c68b42.png) | ![image](https://user-images.githubusercontent.com/24740015/98030016-44eebb80-1e08-11eb-864d-dae8d545680a.png)

2020-10-29 13:31 UTC, SachaZvetelman commented on packages/f-checkout/package.json
> +    "@justeat/f-alert": "^0.1.1",
Remove `^` so we pin the version 👍

2020-10-29 13:31 UTC, SachaZvetelman commented on packages/f-checkout/package.json
> +    "flush-promises": "^1.0.2",
And here.

2020-10-29 13:31 UTC, SachaZvetelman commented on packages/f-checkout/package.json
> +    "vuelidate": "^0.7.6"
And here.

@ashleynolan, @tommcclean, is this another candidate to add to `f-services`?

2020-10-29 13:31 UTC, SachaZvetelman commented on packages/f-checkout/src/components/Checkout.vue
> +            const mobileNumberInvalid = !this.$v.mobileNumber.required || !this.$v.mobileNumber.numeric || !this.$v.mobileNumber.minLength;
Since it's a boolean, it should be `isMobileNumberInvalid`.
On a similar note, it might be easier to read if we invert the variable and call it `isMobileNumberValid`, but this is just a personal preference.

2020-10-29 13:31 UTC, SachaZvetelman commented on packages/f-checkout/src/components/Checkout.vue
> +            delivery: CHECKOUT_METHOD_DELIVERY,
Not sure what `delivery` is supposed to represent. Is it `delivery` or `checkout`? Maybe this should be a boolean? I might be missing some context here.

2020-10-29 13:31 UTC, SachaZvetelman commented on packages/f-checkout/src/components/Checkout.vue
> +                        error: !this.$v.address.line1.required && this.$v.address.line1.$dirty,
This pattern seems to be repeated in multiple places (required and dirty). Maybe we can extract this to a common function?

2020-10-29 13:31 UTC, SachaZvetelman commented on packages/f-checkout/src/components/tests/Checkout.test.js
> +                // expect(wrapper.html()).toBe('1');
Nit: remove comment.

2020-10-29 13:31 UTC, SachaZvetelman commented on packages/f-checkout/src/components/tests/Checkout.test.js
> +    describe('with a working checkout service', () => {
Not sure I understand this description.

2020-10-29 13:31 UTC, SachaZvetelman commented on packages/f-checkout/src/components/tests/Checkout.test.js
> +                expect(wrapper.emitted(EventNames.GoToPaymentFailure)[0][0].invalidFields).toContain('mobileNumber');
Shouldn't the verification here be about the address? I might be confused.

2020-10-29 13:31 UTC, SachaZvetelman commented on packages/f-checkout/src/components/tests/Checkout.test.js
> +                // expect(wrapper.html()).toBe('1');
Nit: remove.

2020-10-29 13:48 UTC, ashleynolan commented on packages/f-checkout/package.json
> +    "vuelidate": "^0.7.6"
Nope – if it's a dependency that's needed for a specific component, we should just include it in the `package.json` like this (or as a peerDependency).

If including it like this, then ideally we'd set-up webpack to chunk these dependencies so that they can be used (only really need to do once we know we'll have two occurrences of this package on the page at once, which I doubt would be the case for checkout).

Benefit of chunking it would also mean we could cache the chunked vuelidate JS for longer too (and across pages).

2020-10-29 13:49 UTC, ashleynolan commented on packages/f-checkout/package.json
> +    "axios": "0.20.0",
I don't think you need to include `axios` here, as it'll come down with `f-services` if you're using the axios methods.

2020-10-29 13:51 UTC, ashleynolan commented on packages/f-checkout/src/components/Address.vue
> +        localAddress: {
Would be good to comment what `localAddress` is/represents (especially in comparison to `address`). Not knowing the context, I'd otherwise have to read through the whole component to try and work it out.

2020-10-29 13:52 UTC, ashleynolan commented on packages/f-checkout/src/components/Address.vue
> +    color: $red;
Can use `$color-text--danger` here

2020-10-29 14:03 UTC, ashleynolan commented on packages/f-checkout/src/components/Checkout.vue
> +        shouldShowMobileNumberInvalidError () {
Can you add JSDoc comments to any computed functions or `methods` below?

2020-10-29 14:15 UTC, ashleynolan commented on packages/f-checkout/src/components/Address.vue
> +        localAddress: {
Are you using this computed to essentially `emit` to the `checkout` component? Not sure but I think it may be a bit tidier to use a watcher to do this if so (as would avoid needing two definitions of `address` in the component)

2020-10-29 14:17 UTC, ashleynolan commented on packages/f-checkout/src/components/Checkout.vue
> +function isValidPostcode () {
Is there a reason this wouldn't just be declared in the `methods` part of the component?

2020-10-29 14:18 UTC, ashleynolan commented on packages/f-checkout/src/components/Checkout.vue
> +const formValidationState = $v => {
Same for this – could this be defined in the `methods`?

2020-10-29 14:19 UTC, FayeCarter commented on packages/f-checkout/src/components/Address.vue
> +    color: $red;
Can do, this class will be removed when `f-error-messages` is used as well. I should've added a note.

2020-10-29 14:21 UTC, FayeCarter commented on packages/f-checkout/src/components/Checkout.vue
> +            delivery: CHECKOUT_METHOD_DELIVERY,
This was added in from review in a previous PR, but I'm not sure it's still needed 👍

2020-10-29 14:22 UTC, FayeCarter commented on packages/f-checkout/src/components/Checkout.vue
> +                        error: !this.$v.address.line1.required && this.$v.address.line1.$dirty,
Sure, I'll give it a go 🙂

2020-10-29 14:24 UTC, FayeCarter commented on packages/f-checkout/src/components/tests/Checkout.test.js
> +    describe('with a working checkout service', () => {
Honestly, this was based off of f-registration so I'm not 100% sure. The aim was for it to be if there's not a server side error, but I'll update it with something a bit clearer

2020-10-29 14:31 UTC, FayeCarter commented on packages/f-checkout/src/components/Address.vue
> +        localAddress: {
Yes that's what I'm trying to do. I tried a few approaches and this is the only way it worked for me yesterday.
I was hoping there was a better way. The double address definitely seems like overkill.
Thanks I'll have a look at using a watcher.

2020-10-29 14:32 UTC, FayeCarter commented on packages/f-checkout/src/components/Checkout.vue
> +function isValidPostcode () {
Nope, I'll move it in.

2020-10-29 14:39 UTC, matthewhardern commented on packages/f-checkout/src/components/Checkout.vue
> +                        error: !this.$v.address.line1.required && this.$v.address.line1.$dirty,
Can I ask why we don't use $error on these, I not saying it should just more of a why are we not using $error ?

2020-10-29 15:08 UTC, matthewhardern commented on packages/f-checkout/src/components/Checkout.vue
> +        addressErrors () {
Just a thought, have you considered using provide and inject so that instead of passing a giant list of address errors, you could do 
```
provide() {
    return {
      $v: this.$v
    }
}
``` 
on the parent. Then use 
```
inject: ['$v']
```
on the child to allow the child to have the access to the same instance of `$v`, allowing you to put the address errors in the address block making the parent less bloated.

2020-10-29 15:16 UTC, matthewhardern commented on packages/f-checkout/src/components/Checkout.vue
> +                            v-if="shouldShowMobileNumberInvalidError"
As an alternative way of doing this (if we wanted) we could loop over all the params under the `$v. mobileNumber.$params` with `v-for` accessing the index / key from the `v-for` to pull the error message from the messages object as long as the object key was the same.

```
<template v-for="(param, index) in $v. mobileNumber.$params" >
    {{ copy.validationMessages.mobileNumber[index] }}
</template>
```
Not a must but just a thought

2020-10-29 15:23 UTC, FayeCarter commented on packages/f-checkout/src/components/Checkout.vue
> +        addressErrors () {
Ooh interesting that may save a whole load of issues. I haven't come across provide and inject. I'll have a look, thanks!

2020-11-02 15:23 UTC, FayeCarter commented on packages/f-checkout/package.json
> +    "axios": "0.20.0",
Axios is currently used in `CheckoutServiceApi`. I've left it in for now as I'm imagining it's going to be changed in later PRs. Is that OK?

2020-11-02 16:10 UTC, FayeCarter commented on packages/f-checkout/src/components/Checkout.vue
> +                            v-if="shouldShowMobileNumberInvalidError"
I'll take a look

2020-11-03 07:48 UTC, matthewhardern commented on packages/f-checkout/src/components/Address.vue
> +    inject: ['shared'],
recommend injecting the two `$v` and `copy` separately, makes it easier to read and understand. Nice work on getting it to run through provide and inject.

2020-11-03 07:49 UTC, matthewhardern commented on packages/f-checkout/src/components/Checkout.vue
> +        Object.defineProperties(shared, {
again as above better if you just do them separately from a readability point of view.

2020-11-03 07:50 UTC, matthewhardern commented on packages/f-checkout/src/components/Checkout.vue
> +        isValidPostcode () {
Is this likely to be used in another component in the future?

2020-11-03 09:58 UTC, FayeCarter commented on packages/f-checkout/src/components/Checkout.vue
> +                            v-if="shouldShowMobileNumberInvalidError"
I'm not sure this will work as it makes 3 error messages pop up at the same time. All 3 errors require the same error message at the moment.

2020-11-03 09:59 UTC, FayeCarter commented on packages/f-checkout/src/components/Address.vue
> +    inject: ['shared'],
Thanks, it was really good to learn about 😄. I'll separate them now

2020-11-03 10:00 UTC, FayeCarter commented on packages/f-checkout/src/components/Checkout.vue
> +        isValidPostcode () {
I can't see where it would be used at this point. Unless fozzie begins to extend into the user account components. I may be wrong though

2020-11-03 10:03 UTC, kevinrodrigues commented on packages/f-checkout/src/components/Checkout.vue
> +        isValidPostcode () {
https://github.com/justeat/fozzie-components/pull/404/files#diff-e5a30357c1de2a2c914b4ad1279462e384f27637f6afed4d0ffc02eda10a71fdR17

2020-11-03 10:04 UTC, kevinrodrigues commented on packages/f-checkout/src/components/Checkout.vue
> +        if (this.checkoutMethod === 'Delivery') {
You could move this to a computed prop and then reuse it here and also in the template above.

2020-11-03 10:07 UTC, kevinrodrigues commented on packages/f-checkout/src/components/Checkout.vue
> +        if (this.checkoutMethod === 'Delivery') {
It might also be better to write it like:

```javascript
const deliveryDetails = isDeliveryMethod === 'Delivery'
? {}
: {};

1. `{}` being the values you need to return.

2. `isDeliveryMethod` the computed for `this.checkoutMethod === 'Delivery'`

2020-11-03 10:11 UTC, kevinrodrigues commented on packages/f-checkout/src/components/tests/Checkout.test.js
> +            it('should not show error message or emit failure event when the address input fields are not populated', async () => {
Is this test correct? The expect below says that there should be an error unless i've read it wrong?

2020-11-03 10:14 UTC, kevinrodrigues commented on packages/f-checkout/src/components/tests/Checkout.test.js
> +            it('should show error message and emit failure event when the mobile number field is not populated', async () => {
Should there be a further test to check that the number meets the min & numeric requirement?

2020-11-03 11:07 UTC, FayeCarter commented on packages/f-checkout/src/components/Checkout.vue
> +        isValidPostcode () {
Ahh I see. I'll put a note on it for now so it can be updated when it is in f-services?

2020-11-03 11:08 UTC, FayeCarter commented on packages/f-checkout/src/components/Checkout.vue
> +        if (this.checkoutMethod === 'Delivery') {
Right ok, that makes sense. I'll have a look, thanks!

2020-11-03 11:09 UTC, FayeCarter commented on packages/f-checkout/src/components/tests/Checkout.test.js
> +            it('should not show error message or emit failure event when the address input fields are not populated', async () => {
Ah yeah it's wrong. I'll update it

2020-11-03 11:20 UTC, FayeCarter commented on packages/f-checkout/src/components/Checkout.vue
> +        if (this.checkoutMethod === 'Delivery') {
@kevinrodrigues just double checking, you mean like this right?
![image](https://user-images.githubusercontent.com/24740015/97979111-85c5e080-1dc6-11eb-88b7-f9eebb7344d3.png)

2020-11-04 08:36 UTC, kevinrodrigues submitted a review, later dismissed

2020-11-04 09:36 UTC, SachaZvetelman requested changes

2020-11-04 09:36 UTC, SachaZvetelman commented on packages/f-checkout/package.json
> +    "vuelidate": "^0.7.6"
This version should be pinned, as per my previous comment 🙂

2020-11-04 09:36 UTC, SachaZvetelman commented on packages/f-checkout/src/components/Address.vue
> +        checkValid (field) {
I'd rename this to `isFieldValid` or similar, given it returns a `boolean`.

2020-11-04 09:36 UTC, SachaZvetelman commented on packages/f-checkout/src/components/Address.vue
> +        isAddressLine1Invalid () {
I find the names a bit confusing, personally.
This computed property says `isInvalid`, but inside we call a function that says `checkValid`. One is negative ("invalid"), while the other one is positive ("valid"). I think we should do some renaming here. Happy to have a chat about this if you need!

2020-11-04 09:36 UTC, SachaZvetelman commented on packages/f-checkout/src/components/Checkout.vue
> +                            data-test-id='error-mobile-number-empty'>
Nit: `data-test-id` should be set with `"` (double quotes)

2020-11-04 09:36 UTC, SachaZvetelman commented on packages/f-checkout/src/components/Checkout.vue
> +            const mobileNumberInvalid = !this.$v.mobileNumber.required || !this.$v.mobileNumber.numeric || !this.$v.mobileNumber.minLength;
This has been marked as resolved, but I still see the same things I mentioned on my original comment.

2020-11-04 09:36 UTC, SachaZvetelman commented on packages/f-checkout/src/components/Checkout.vue
> +            return this.checkoutMethod === 'Delivery';
We should probably extract this `"Delivery"` into a constant. I'd add it to our `constants` file.

2020-11-04 09:36 UTC, SachaZvetelman commented on packages/f-checkout/src/components/Checkout.vue
> +                this.$emit(EventNames.CheckoutSuccess);
I'm not entirely familiar with the code you're writing, but under what circumstances would this actually fail and would cause the `catch` to be "triggered"? Emitting an event shouldn't ever fail. Please, correct me if I'm wrong here.

2020-11-04 09:36 UTC, SachaZvetelman commented on packages/f-checkout/src/components/Checkout.vue
> +                if (error && error.response && error.response.data && error.response.data.errors) {
We're using the conditional chaining operator plugin in these projects, as far as I'm aware. That means you could do:
`if (error?.response?.data?.errors) {`

2020-11-04 09:36 UTC, SachaZvetelman commented on packages/f-checkout/src/components/Checkout.vue
> +                    this.genericErrorMessage = thrownErrors[0].description || 'Something went wrong, please try again later';
If we get an array of errors, why do we should only the first one?

2020-11-04 09:36 UTC, SachaZvetelman commented on packages/f-checkout/src/components/Checkout.vue
> +                    this.$emit(EventNames.CreateAccountFailure, thrownErrors);
I'm struggling to understand here why we're throwing a `CreateAccountFailure` here. Could you please clarify?

2020-11-04 09:36 UTC, SachaZvetelman commented on packages/f-checkout/src/components/Checkout.vue
> +        const deliveryDetails = this.isDeliveryMethod
This shouldn't be `deliveryDetails` is it could be `collectionDetails`.

2020-11-04 09:36 UTC, SachaZvetelman commented on packages/f-checkout/src/components/Checkout.vue
> +                }
This bit is always needed, regardless of whether it's collection or delivery. Maybe you can add it always to the validation details and then only add the address ones if it's delivery.

2020-11-04 09:36 UTC, SachaZvetelman commented on packages/f-checkout/src/components/Checkout.vue
> +        width: 462px;
Is this super-specific because it's the width of the checkout page?

2020-11-04 09:36 UTC, SachaZvetelman commented on packages/f-checkout/src/components/tests/Checkout.test.js
> +                await wrapper.vm.$nextTick();
I'm not so sure I understand why we're flushing promises and doing `$nextTick` in this case.
Besides that, `onFormSubmit` is not an `async` function, as far as I can tell, so I'm unsure why we're `await`ing here.

It might be me getting confused or missing some concepts here, but could you please clarify? (this applies to all the tests because I see we're flushing promises everywhere).

2020-11-04 09:36 UTC, SachaZvetelman commented on packages/f-checkout/src/components/tests/Checkout.test.js
> +            it('should show error message and emit failure event when the mobile number field is populated with non numeric value', async () => {
Is there any test in which we verify we're showing the right error message?

2020-11-04 09:36 UTC, SachaZvetelman commented on packages/f-checkout/src/components/tests/Checkout.test.js
> +                expect(wrapper.emitted(EventNames.CheckoutSuccess).length).toBe(1);
Might be a good idea to add an `expect` to check the `CheckoutFailure` event hasn't been emitted.

2020-11-04 09:36 UTC, SachaZvetelman commented on packages/f-checkout/src/components/tests/Checkout.test.js
> +            it('should emit failure event when the address input fields are not populated', async () => {
We should add more tests to check for valid postcodes.
In the future, these tests will be in `f-services`, when you move that RegEx for validations, and in here we'll just check basically that "the right validation is used".

2020-11-04 09:36 UTC, SachaZvetelman commented on packages/f-checkout/src/event-names.js
> +const VisitCheckoutPage = 'checkout-visit-payment-page';
Should we rename to `CheckoutVisitPage` to keep it consistent?

2020-11-04 09:47 UTC, FayeCarter commented on packages/f-checkout/package.json
> +    "vuelidate": "^0.7.6"
Noooooo I was sure these had all been removed 🤦‍♀️

2020-11-04 10:06 UTC, FayeCarter commented on packages/f-checkout/src/components/Checkout.vue
> +        width: 462px;
It is, I'll move it to a variable

2020-11-04 16:35 UTC, FayeCarter commented on packages/f-checkout/src/components/tests/Checkout.test.js
> +            it('should show error message and emit failure event when the mobile number field is populated with non numeric value', async () => {
I've now added an expect statement to each of the tests to get an error message. Not sure if it would be better to have them in separate tests though?

2020-11-04 16:56 UTC, FayeCarter commented on packages/f-checkout/src/components/Checkout.vue
> +                    this.$emit(EventNames.CreateAccountFailure, thrownErrors);
I may have borrowed some code and not updated it 😬

2020-11-05 09:29 UTC, FayeCarter commented on packages/f-checkout/src/components/Checkout.vue
> +                this.$emit(EventNames.CheckoutSuccess);
I've now added a method that makes this make slightly more sense. I hope

2020-11-05 09:29 UTC, FayeCarter commented on packages/f-checkout/src/components/Checkout.vue
> +                if (error && error.response && error.response.data && error.response.data.errors) {
I can't get this to work for some reason. I'll keep exploring

2020-11-05 09:30 UTC, FayeCarter commented on packages/f-checkout/src/components/tests/Checkout.test.js
> +                await wrapper.vm.$nextTick();
I've removed a lot of this now. I hadn't finished the full submit method

2020-11-05 11:47 UTC, SachaZvetelman requested changes

2020-11-05 11:47 UTC, SachaZvetelman commented on packages/f-checkout/src/components/Address.vue
> +        value: {
Not sure what `value` is. Let's try finding a name that describes what it is, please 🙂

2020-11-05 11:47 UTC, SachaZvetelman commented on packages/f-checkout/src/components/Checkout.vue
> +            heading="Error">
`Error` should also come from the translation files.
Btw, we need to check if `Error` is the correct word to show here. We might have to ask the designers.

2020-11-05 11:47 UTC, SachaZvetelman commented on packages/f-checkout/src/components/Checkout.vue
> +            collectionDetails.address = {
Hmmm, `collectionDetails` doesn't make a lot of sense to me, sorry. But if it's `delivery`, then it's not `collection details` 😬

2020-11-05 11:47 UTC, SachaZvetelman commented on packages/f-checkout/src/components/tests/Checkout.test.js
> +        }
This is a bit of weird way to get and mount the component. I haven't seen it before. Is there any particular reason why we're doing it this way and not the way we do it in most of our `fozzie-components` tests?

2020-11-05 11:47 UTC, SachaZvetelman commented on packages/f-checkout/src/components/tests/Checkout.test.js
> +                expect(mobileNumberEmptyMessage.exists()).toBe(true);
Probably you want to check what text you're showing, not just that it exists. `toMatchSnapshot` would do.

2020-11-05 11:47 UTC, SachaZvetelman commented on packages/f-checkout/src/components/tests/Checkout.test.js
> +                wrapper.find('[data-test-id="input-mobile-number"]').setValue('07777777777');
Could we extract this information to a constant at the top of the file? We're reusing the address and the mobile number in some parts.

2020-11-05 11:55 UTC, FayeCarter commented on packages/f-checkout/src/components/Address.vue
> +        value: {
@SachaZvetelman  - This seems to be the only way that it will work with a nested v-model. I've tried setting it to address (because it would make more sense that way), but that way it can't read the prop at all.
I'm hoping I'm wrong here though

2020-11-05 11:57 UTC, FayeCarter commented on packages/f-checkout/src/components/Checkout.vue
> +            collectionDetails.address = {
It was delivery before. I think I changed it because of another review 🤦‍♀️. But agreed it makes more sense as delivery

2020-11-05 11:58 UTC, FayeCarter commented on packages/f-checkout/src/components/tests/Checkout.test.js
> +        }
I couldn't get it to work how it is normally done. Just tried it again ... it works. It's changed now.

2020-11-05 11:59 UTC, FayeCarter commented on packages/f-checkout/src/components/tests/Checkout.test.js
> +                wrapper.find('[data-test-id="input-mobile-number"]').setValue('07777777777');
I'll give it a go

2020-11-05 15:59 UTC, FayeCarter commented on packages/f-checkout/src/components/tests/Checkout.test.js
> +                expect(mobileNumberEmptyMessage.exists()).toBe(true);
@SachaZvetelman Just wanted to check I've done this correctly now

2020-11-05 16:00 UTC, FayeCarter commented on packages/f-checkout/src/components/tests/Checkout.test.js
> +                wrapper.find('[data-test-id="input-mobile-number"]').setValue('07777777777');
@SachaZvetelman Same with this, just wanted to check that I've written it as you expected

2020-11-05 16:02 UTC, SachaZvetelman requested changes

2020-11-05 16:02 UTC, SachaZvetelman commented on packages/f-checkout/babel.config.js
> +            }]
Nit: indentation looks funny here.

2020-11-05 16:02 UTC, SachaZvetelman commented on packages/f-checkout/src/tenants/en-GB.js
> +        errors: {
Why do we have `errors` within `errorMessages`? :)

2020-11-05 16:04 UTC, SachaZvetelman commented on packages/f-checkout/src/components/tests/Checkout.test.js
> +                wrapper.find('[data-test-id="input-mobile-number"]').setValue('07777777777');
@FayeCarter, I was actually talking about the data we're using in `setValue` (i.e. the phone number, the address, etc)

2020-11-05 16:04 UTC, FayeCarter commented on packages/f-checkout/babel.config.js
> +            }]
Ahh didn't realise this was still in. This was an experiment to try and get babel to work. I'll remove it

2020-11-05 16:04 UTC, FayeCarter commented on packages/f-checkout/src/tenants/en-GB.js
> +        errors: {
It's been a long day 😂

2020-11-05 16:08 UTC, FayeCarter commented on packages/f-checkout/src/components/tests/Checkout.test.js
> +                wrapper.find('[data-test-id="input-mobile-number"]').setValue('07777777777');
Ahhhh that makes sense. Thanks

2020-11-06 09:55 UTC, FayeCarter commented on packages/f-checkout/src/components/Address.vue
> +        value: {
I was wrong 🥳

2020-11-06 15:01 UTC, xander-marjoram commented on packages/f-checkout/package.json
> +    "@justeat/f-services": "1.0.0",
We should probably update this to `1.3.0` soon

2020-11-06 15:02 UTC, SachaZvetelman commented on packages/f-checkout/src/components/Address.vue
> +                    v-if="!isAddressPostcodeValid"
I'm thinking, should we rename this one `isAddressPostcodeEmpty` and then the one below would be `isAddressPostcodeValid`?
Up to you, really. My reasoning is that the first one is actually checking if it's empty or not, not if it's "valid".

2020-11-06 15:02 UTC, SachaZvetelman commented on packages/f-checkout/src/components/Checkout.vue
> +                // TODO: Babel 'optional-chaining' plugin not working in storybook
I guess we can remove this now?

2020-11-06 15:10 UTC, xander-marjoram commented on packages/f-checkout/src/components/Address.vue
> +                <template #error>
Is it necessary to use the `template`? Would this work?
```vue
<error-message #error>
    v-if="!isAddressCityValid"
    data-test-id="error-address-city-empty">
    {{ copy.validationMessages.city.requiredError }}
</error-message>
```

2020-11-06 15:11 UTC, xander-marjoram commented on packages/f-checkout/src/components/Address.vue
> +                <template #error>
I see you also have it below when passing in two errors, which makes more sense

2020-11-06 15:16 UTC, xander-marjoram commented on packages/f-checkout/src/components/Address.vue
> +    inject: ['$v', 'copy'],
Would be good to get an explanation of this and why it's necessary for those of us who aren't familiar with provide/inject

2020-11-06 15:25 UTC, FayeCarter commented on packages/f-checkout/src/components/Address.vue
> +    inject: ['$v', 'copy'],
Yeah sure, I'll add something

2020-11-06 15:27 UTC, FayeCarter commented on packages/f-checkout/src/components/Address.vue
> +                    v-if="!isAddressPostcodeValid"
Can do. I'd image it would be best to rename the others that I have for address and mobile number from 'Valid' to be 'Empty' as well?

2020-11-06 15:33 UTC, FayeCarter commented on packages/f-checkout/src/components/Address.vue
> +                <template #error>
Ah, I thought you needed the template tag for a named slot, I'll have a look

2020-11-10 09:06 UTC, FayeCarter commented on packages/f-checkout/src/components/Checkout.vue
> +            heading="Error">
Will update with design as a separate ticket

2020-11-10 11:21 UTC, xander-marjoram commented on packages/f-checkout/src/components/Address.vue
> +                    v-if="!isAddressPostcodeEmpty"
This doesn't quite make semantic sense to me. It reads as "if postcode is **not** empty then show the error", shouldn't we be showing the error if the postcode is empty?

2020-11-10 11:29 UTC, xander-marjoram commented on packages/f-checkout/src/components/Address.vue
> +            return !(this.$v.addressErrors.postcode.$dirty && !this.$v.addressErrors.postcode.isValidPostcode);
Can we simplify this to:
`!this.$v.addressErrors.postcode.$dirty || this.$v.addressErrors.postcode.isValidPostcode`?
I think it's more readable, you can see it means "untouched or actually valid".

2020-11-10 11:33 UTC, xander-marjoram commented on packages/f-checkout/src/components/Checkout.vue
> +            const isMobileNumberValid = !(!this.$v.mobileNumber.required || !this.$v.mobileNumber.numeric || !this.$v.mobileNumber.minLength);
This can also be simplified:
`this.$v.mobileNumber.required && this.$v.mobileNumber.numeric && this.$v.mobileNumber.minLength`

2020-11-10 11:34 UTC, FayeCarter commented on packages/f-checkout/src/components/Address.vue
> +            return !(this.$v.addressErrors.postcode.$dirty && !this.$v.addressErrors.postcode.isValidPostcode);
Thanks

2020-11-10 11:35 UTC, xander-marjoram commented on packages/f-checkout/src/components/Checkout.vue
> +            return !(this.$v.mobileNumber.$dirty && !isMobileNumberValid);
`!this.$v.mobileNumber.$dirty || isMobileNumberValid`

2020-11-10 11:35 UTC, FayeCarter commented on packages/f-checkout/src/components/Checkout.vue
> +            const isMobileNumberValid = !(!this.$v.mobileNumber.required || !this.$v.mobileNumber.numeric || !this.$v.mobileNumber.minLength);
Thank you!

2020-11-10 11:36 UTC, FayeCarter commented on packages/f-checkout/src/components/Checkout.vue
> +            return !(this.$v.mobileNumber.$dirty && !isMobileNumberValid);
Brilliant, thanks

2020-11-10 11:37 UTC, FayeCarter commented on packages/f-checkout/src/components/Address.vue
> +                    v-if="!isAddressPostcodeEmpty"
Good point

2020-11-10 11:41 UTC, xander-marjoram commented on packages/f-checkout/src/components/tests/Checkout.test.js
> +                wrapper.destroy();
I'm happy for this to stay, but is this necessary if we're reassigning it for every test anyway?

2020-11-10 11:42 UTC, FayeCarter commented on packages/f-checkout/src/components/tests/Checkout.test.js
> +                wrapper.destroy();
Tests still pass without it. I'm happy to remove it

2020-11-10 13:01 UTC, xander-marjoram commented on packages/f-checkout/src/components/tests/Checkout.test.js
> +                expect(wrapper.vm.address.required).toBe(undefined);
I think this might be checking `data.address` rather than the validation, so this is likely to always be undefined.

2020-11-10 14:53 UTC, ashleynolan commented on packages/f-checkout/package.json
> +    "vuelidate": "0.7.6"
Not necessarily one for this PR, but we should definitely create a ticket to spike if we can make Vueliddate a `peerDependency` so that we don't bundle it into every component that needs validation (as registration also uses vuelidate for instance).

2020-11-10 14:56 UTC, ashleynolan commented on packages/f-checkout/src/components/Address.vue
> +                <template #error>
Not sure if this has been addressed, but why do you need the `template` tags here?

2020-11-10 15:03 UTC, ashleynolan commented on packages/f-checkout/src/components/Checkout.vue
> +        async onFormSubmit () {
This is quite a big method. Can it be split up so that it calls other smaller methods that do smaller things (instead of one big method that does all the things)? So imo the `try` should be in a separate method that handles the API call, and then the `catch` should be a separate method that handles the error state being applied (you could likely just put the inner code of the try/catch into different methods).

Would also be good to have some comments to explain what's happening (so I'm guessing the try/catch if trying to submit to an endpoint and if this fails, it catches the error?).

2020-11-10 15:08 UTC, ashleynolan commented on packages/f-checkout/src/components/Checkout.vue
> +        isDeliveryMethod () {
Not sure the name makes complete sense. Looks like it's checking for if the checkout method is `Delivery` in which case I'd call this `isDelivery` or `isCheckoutMethodDelivery` (if it should be more explicit).

2020-11-10 15:09 UTC, ashleynolan commented on packages/f-checkout/src/components/Checkout.vue
> +$checkout-width                           : 462px;
Looks like a bit of a magic number – is there a reason it's exactly `462px` rather than just `460px`?

2020-11-10 15:11 UTC, ashleynolan commented on packages/f-checkout/src/components/Checkout.vue
>          @include font-size(heading-s);
Referring to the line above (don't need to do this as part of this PR, but should be done at some point).

Best to give the `h1` a class of `.c-checkout-title` as that way if the heading tag ever changes, the styles are less brittle and won't break.

2020-11-10 15:12 UTC, FayeCarter commented on packages/f-checkout/package.json
> +    "vuelidate": "0.7.6"
Sure, I can set of a ticket for this if that's ok?

2020-11-10 15:14 UTC, ashleynolan commented on packages/f-checkout/package.json
> +    "vuelidate": "0.7.6"
Yep – that'd be good 👍

2020-11-10 15:15 UTC, FayeCarter commented on packages/f-checkout/src/components/Checkout.vue
> +$checkout-width                           : 462px;
So this is the width that the checkout component is set to in consumerWeb. I was trying to get it as close to ConsumerWeb for now. Is that OK?

2020-11-10 15:16 UTC, xander-marjoram submitted a review, later dismissed

2020-11-10 15:54 UTC, FayeCarter commented on packages/f-checkout/src/components/Checkout.vue
> +        async onFormSubmit () {
Hey @ashleynolan, I've updated and created new methods/descriptions. Are these ok?

2020-11-11 09:23 UTC, xander-marjoram submitted a review, later dismissed

2020-11-11 15:11 UTC, dandel10n submitted a review, later dismissed
Looks good to me. I noticed that allerst are not responsive, but this will be covered in next ticket.

2020-11-11 16:21 UTC, ashleynolan commented on packages/f-checkout/src/components/Address.vue
> +        isFieldEmpty (field) {
Super NIT – can you add some JSDoc comments to this function? (happy for this to happen in next PR though)

2020-11-11 16:23 UTC, ashleynolan commented on packages/f-checkout/src/components/Checkout.vue
> +            :locale="locale"
Not sure (as haven't looked at the alert component), but if it uses the same code as other components, it should just inherit the locale from the global `i18n` config that gets set, so you may not need to pass this through.

2020-11-11 16:25 UTC, ashleynolan commented on packages/f-checkout/src/components/Checkout.vue
> +        async onFormSubmit () {
Yep – looks much better 👍 

Could you add JSDoc comments to the methods too? (we're trying to add these to anything added to the methods object in components going forward)

2020-11-11 16:30 UTC, ashleynolan commented on packages/f-checkout/src/components/tests/Checkout.test.js
> +            line1: 'Fleet Place House',
I'd probably change this to be data that means as little as possible (as close to lorem ipsum style as you can while still passing the validations)

2020-11-12 08:29 UTC, SachaZvetelman commented on packages/f-checkout/src/components/Address.vue
> +                :label-text="$t.labels.line2"
This doesn't look right. As far as I know, and I could be wrong, it should be `$t('labels.line2')`.
Same for all of the places where we're using `$t`.

2020-11-12 09:42 UTC, FayeCarter commented on packages/f-checkout/src/components/Address.vue
> +                <template #error>
Discussed this with Ash and Xander, template tags are needed for the named slots and allows standardisation where multiple error messages are needed

2020-11-12 09:44 UTC, FayeCarter commented on packages/f-checkout/src/components/Address.vue
> +                :label-text="$t.labels.line2"
This is now updated 😄

2020-11-12 09:55 UTC, SachaZvetelman submitted a review, later dismissed

2020-11-12 12:13 UTC, xander-marjoram commented on packages/f-checkout/src/components/Checkout.vue
> +            * Check to see if any `Vulidate` calidation errors
Nit: typos `Vuelidate`, `validation`

I think I might have seen other instances of "vulidate" as well?

2020-11-12 12:16 UTC, xander-marjoram commented on packages/f-checkout/package.json
> +    "vuelidate": "0.7.6",
Nit: Can you move this dependency to the bottom please?

2020-11-12 12:44 UTC, xander-marjoram approved these changes

2020-11-12 13:30 UTC, SachaZvetelman approved these changes

2020-11-12 13:32 UTC, merged