f-checkout@0.8.0 Get necessary data from the CheckoutOrchestrator
justeattakeaway/fozzie-components pull request #412
Opened 2020-11-04 16:02 UTC by pkedziora

Displays data populated from GET endpoint

v0.8.0
------------------------------
*November 4, 2020*

### Added
- Checkout component calls server to get data

---

## UI Review Checks
<img width="300" alt="Screenshot 2020-11-05 at 10 28 26" src="https://user-images.githubusercontent.com/6950110/98229409-c56d0380-1f51-11eb-91e4-ed6fe515ca8f.png">
<img width="300" alt="Screenshot 2020-11-05 at 10 28 58" src="https://user-images.githubusercontent.com/6950110/98229415-c867f400-1f51-11eb-8d30-11b857fa32f6.png">

- [ ] README and/or UI Documentation has been [created|updated]
- [x] Unit tests have been [created|updated]
- [ ] This code has been checked with regard to [our accessibility standards](http://fozzie.just-eat.com/documentation/general/accessibility/checklist)

## Browsers Tested

- [x] Chrome (latest)
- [ ] Internet Explorer 11
- [ ] Mobile (Please list device/browser – Ideally one iPhone model and one Android)

### List any other browsers that this PR has been tested in:

- [View the Browser Support Checklist](http://fozzie.just-eat.com/documentation/general/browser-support)

2020-11-04 19:08 UTC, DamianMullins commented on packages/f-checkout/stories/Checkout.stories.js
> +    checkoutUrl: 'http://all-checkoutorchestrator-qa1.cwa.je-labs.com/uk/checkout/12345'
Do we want references to QA environments in an open source code? Sounds like something InfoSec would want us to purge?

2020-11-05 09:40 UTC, pkedziora commented on packages/f-checkout/stories/Checkout.stories.js
> +    checkoutUrl: 'http://all-checkoutorchestrator-qa1.cwa.je-labs.com/uk/checkout/12345'
@DamianMullins isn't this a private repo?

2020-11-05 09:44 UTC, kevinrodrigues commented on packages/f-checkout/stories/Checkout.stories.js
> +    checkoutUrl: 'http://all-checkoutorchestrator-qa1.cwa.je-labs.com/uk/checkout/12345'
It's in the process of being made public @pkedziora

2020-11-05 10:32 UTC, DamianMullins commented on packages/f-checkout/stories/Checkout.stories.js
> +    checkoutUrl: 'http://all-checkoutorchestrator-qa1.cwa.je-labs.com/uk/checkout/12345'
Which does worry me. It's very easy for things like this to slip through. I know iOS has a similar approach with modules in a mono-repo but at least theirs is private.

2020-11-05 10:36 UTC, pkedziora commented on packages/f-checkout/stories/Checkout.stories.js
> +    checkoutUrl: 'http://all-checkoutorchestrator-qa1.cwa.je-labs.com/uk/checkout/12345'
Fixed

2020-11-05 10:42 UTC, DamianMullins commented on packages/f-checkout/stories/Checkout.stories.js
> +    checkoutUrl: 'http://all-checkoutorchestrator-qa1.cwa.je-labs.com/uk/checkout/12345'
Now that this URL has been added in a PR it will always be visible even if we squash commits etc. There's no way to fully purge it without requesting Github to delete the content or creating a new repo and copying the code across (which means we lose all PRs, issues etc.

2020-11-05 10:44 UTC, pkedziora commented on packages/f-checkout/stories/Checkout.stories.js
> +    checkoutUrl: 'http://all-checkoutorchestrator-qa1.cwa.je-labs.com/uk/checkout/12345'
This url is hardly a secret

2020-11-05 10:46 UTC, DamianMullins commented on packages/f-checkout/stories/Checkout.stories.js
> +    checkoutUrl: 'http://all-checkoutorchestrator-qa1.cwa.je-labs.com/uk/checkout/12345'
Not in this case it isn't, but what if something sensitive gets through like some credentials?

2020-11-05 10:46 UTC, pkedziora commented on packages/f-checkout/stories/Checkout.stories.js
> +    checkoutUrl: 'http://all-checkoutorchestrator-qa1.cwa.je-labs.com/uk/checkout/12345'
And it's not available externally

2020-11-05 11:30 UTC, SachaZvetelman requested changes
Probably something we should do on a separate PR (unless you want to do it in this PR, and I can help you with that), but we should introduce `Vuex` to be able to keep state in a centralised manner. That will help us reduce the number of props and data we need to inject into child components.

2020-11-05 11:30 UTC, SachaZvetelman commented on packages/f-checkout/package.json
> +    "axios": "0.20.0",
@ashleynolan, we should actually be using `f-services` for this, right? Or is it correct to be importing `axios`?

2020-11-05 11:30 UTC, SachaZvetelman commented on packages/f-checkout/package.json
> +    "axios-mock-adapter": "^1.19.0"
Please remove the `^` so we can pin the version down.

2020-11-05 11:30 UTC, SachaZvetelman commented on packages/f-checkout/src/components/Checkout.vue
> +                    v-model="customer.phoneNumber"
If we're using `phoneNumber` instead of `mobileNumber`, we should rename the rest of the attribute values for this element. cc @FayeCarter

2020-11-05 11:30 UTC, SachaZvetelman commented on packages/f-checkout/src/components/Checkout.vue
> +            default: 'delivery',
_I think_, @FayeCarter is extracting this to a `constant` somewhere. So when we merge Faye's changes, let's use that constant instead of using a magic string here.

2020-11-05 11:30 UTC, SachaZvetelman commented on packages/f-checkout/src/components/Checkout.vue
> +            id: '',
Maybe a silly question, but what is this `id`? Is it a `CheckoutId`? `BasketId`?

2020-11-05 11:30 UTC, SachaZvetelman commented on packages/f-checkout/src/components/Checkout.vue
> +            return this.name ? `${this.name}, confirm your details` : '';
At this stage, we should always have a name. If we don't have a name it means it's a guest checkout (we have a separate ticket for that), so I don't think we need this change.

2020-11-05 11:30 UTC, SachaZvetelman commented on packages/f-checkout/src/components/Checkout.vue
> +            return {
Nit: I'd probably assign this object to a `const` called `tenants` or something like that to improve readability a bit.

2020-11-05 11:30 UTC, SachaZvetelman commented on packages/f-checkout/src/components/Checkout.vue
> +            this.messages = data.messages;
Very nit: add an empty line before this, please.

2020-11-05 11:30 UTC, SachaZvetelman commented on packages/f-checkout/src/components/tests/Checkout.test.js
> +        const propsData = { checkoutUrl: '/checkout/uk/12345' };
We can extract `checkout/uk/12345` to a constant since we're using this in multiple places.

2020-11-05 11:30 UTC, SachaZvetelman commented on packages/f-checkout/src/components/tests/Checkout.test.js
> +                    checkoutMethod: 'delivery',
Same as above, let's try to use the constant that Faye is introducing in the future.

2020-11-05 11:30 UTC, SachaZvetelman commented on packages/f-checkout/src/components/tests/Checkout.test.js
> +                    checkoutMethod: 'collection',
Same as above.

2020-11-05 11:30 UTC, SachaZvetelman commented on packages/f-checkout/src/demo/checkoutMock.js
> +
Ultra nit: remove empty line please :D

2020-11-05 11:32 UTC, pkedziora commented on packages/f-checkout/package.json
> +    "axios": "0.20.0",
@SachaZvetelman btw I haven't imported axios. It was already there, it just moved couple of lines down

2020-11-05 11:34 UTC, pkedziora commented on packages/f-checkout/src/components/Checkout.vue
> +            id: '',
@SachaZvetelman it's a CheckoutId that is currently actually a BasketId . David mentioned that it will be it separate thing in the future. For now it maps to BasketId

2020-11-05 11:42 UTC, xander-marjoram commented on packages/f-checkout/package.json
> +    "axios-mock-adapter": "^1.19.0"
Please can you pin this version (remove `^`)

2020-11-05 11:53 UTC, SachaZvetelman commented on packages/f-checkout/src/components/Checkout.vue
> +            id: '',
Can we please rename it to `basketId` for now?

2020-11-05 13:10 UTC, pkedziora commented on packages/f-checkout/src/components/Checkout.vue
> +            id: '',
@SachaZvetelman I think it should be checkoutId in that case as that's what the id is meant to represent

2020-11-05 13:36 UTC, pkedziora commented on packages/f-checkout/package.json
> +    "axios-mock-adapter": "^1.19.0"
Fixed

2020-11-05 13:36 UTC, pkedziora commented on packages/f-checkout/src/demo/checkoutMock.js
> +
Fixed

2020-11-05 13:37 UTC, pkedziora commented on packages/f-checkout/src/components/tests/Checkout.test.js
> +        const propsData = { checkoutUrl: '/checkout/uk/12345' };
Fixed

2020-11-05 13:37 UTC, pkedziora commented on packages/f-checkout/src/components/Checkout.vue
> +            this.messages = data.messages;
Fixed

2020-11-05 13:37 UTC, pkedziora commented on packages/f-checkout/src/components/Checkout.vue
> +            return this.name ? `${this.name}, confirm your details` : '';
Fixed

2020-11-05 13:37 UTC, pkedziora commented on packages/f-checkout/src/components/Checkout.vue
> +            return {
Fixed

2020-11-05 13:37 UTC, pkedziora commented on packages/f-checkout/src/components/Checkout.vue
> +            id: '',
Changed to checkoutId

2020-11-05 13:37 UTC, pkedziora commented on packages/f-checkout/package.json
> +    "axios-mock-adapter": "^1.19.0"
Fixed

2020-11-05 13:39 UTC, pkedziora commented
@SachaZvetelman I would prefer to do Vuex as a separate PR

2020-11-05 18:15 UTC, DamianMullins commented on packages/f-checkout/stories/Checkout.stories.js
> +    checkoutUrl: 'http://all-checkoutorchestrator-qa1.cwa.je-labs.com/uk/checkout/12345'
In any case the same applies to all of our open source code so I guess we just need to be vigilant.

2020-11-16 14:36 UTC, closed without merging