f-checkout@0.9.0 Wire up the form with response from get checkout
justeattakeaway/fozzie-components pull request #443
Opened 2020-11-16 14:20 UTC by pkedziora

v0.9.0
------------------------------
*November 16, 2020*

### Added
- Checkout component calls server to get data

## UI Review Checks

<img width="391" alt="Screenshot 2020-11-16 at 14 21 41" src="https://user-images.githubusercontent.com/6950110/99263650-65127780-2817-11eb-893e-9b33bc5930c2.png">
<img width="392" alt="Screenshot 2020-11-16 at 14 21 51" src="https://user-images.githubusercontent.com/6950110/99263641-6348b400-2817-11eb-9a5a-7dde17db82d9.png">

- [x] README and/or UI Documentation has been [created|updated]
- [x] Unit tests have been [created|updated]
- [ ] This code has been checked with regard to [our accessibility standards](http://fozzie.just-eat.com/documentation/general/accessibility/checklist)

## Browsers Tested

- [x] Chrome (latest)
- [ ] Internet Explorer 11
- [ ] Mobile (Please list device/browser – Ideally one iPhone model and one Android)

### List any other browsers that this PR has been tested in:

- [View the Browser Support Checklist](http://fozzie.just-eat.com/documentation/general/browser-support)

2020-11-16 14:47 UTC, SachaZvetelman requested changes

2020-11-16 14:47 UTC, SachaZvetelman commented on packages/f-checkout/package.json
> +     "axios-mock-adapter": "1.19.0"
Nit: indentation.

2020-11-16 14:47 UTC, SachaZvetelman commented on packages/f-checkout/src/components/Checkout.vue
>          },
We should remove this prop, actually. Happy to do it in a different ticket, if you think it's better, though.

2020-11-16 14:47 UTC, SachaZvetelman commented on packages/f-checkout/src/components/Checkout.vue
>          }
What's the advantage of passing the checkout timeout as a prop?

2020-11-16 14:47 UTC, SachaZvetelman commented on packages/f-checkout/src/components/Checkout.vue
> +            buttonText: 'Go to payment',
This should be removed. It's no longer used. It's coming from the tenant files.

2020-11-16 14:47 UTC, SachaZvetelman commented on packages/f-checkout/src/components/Checkout.vue
> +            delivery: CHECKOUT_METHOD_DELIVERY,
We should get rid of this as well, if we have `serviceType`.

2020-11-16 14:47 UTC, SachaZvetelman commented on packages/f-checkout/src/components/Checkout.vue
> +            this.firstName = data.customer.firstName;
Do we always get a `customer`? If there are scenarios in which we don't, this will fail.

2020-11-16 14:47 UTC, SachaZvetelman commented on packages/f-checkout/src/components/Checkout.vue
> +            this.times = data.fulfillment.times;
Do we always get a `fulfillment`? If there are scenarios in which we don't, this will fail.

2020-11-16 14:47 UTC, SachaZvetelman commented on packages/f-checkout/src/components/Selector.vue
> +            data-test-id="delivery-time"
This will be `collection-time` when it's a collection order. Should we update this in this PR even though you haven't modified this line?

2020-11-16 14:47 UTC, SachaZvetelman commented on packages/f-checkout/src/components/Selector.vue
>      }
Could you please clarify why we need a `watch` here? 🙂

2020-11-16 14:47 UTC, SachaZvetelman commented on packages/f-checkout/src/components/tests/Checkout.test.js
> +                    checkoutMethod: 'delivery',
As I mentioned above, we'll remove this prop, so we might have to update these tests. Again, if you think it should be better done in a separate PR, I understand.

2020-11-16 14:47 UTC, SachaZvetelman commented on packages/f-checkout/src/components/tests/Checkout.test.js
> +        function CheckoutGetData (serviceType) {
This could be a `let` at the top of the file which is updated in a `beforeEach`.
You can then do something like:
```
let defaultCheckoutGetData = ...;
...
... // beforeEach and other magic.
...
const checkoutGetData = { ...defaultCheckoutGetData, serviceType };
```

2020-11-16 14:47 UTC, SachaZvetelman commented on packages/f-checkout/src/components/tests/Checkout.test.js
> +                CheckoutServiceApi.getCheckout.mockClear();
You can move this to an `afterEach` so the `beforeEach` ends up being cleaner.

2020-11-16 14:47 UTC, SachaZvetelman commented on packages/f-checkout/src/components/tests/Checkout.test.js
> +        function CheckoutGetData () {
Not sure why we need to redefine this function here? I think it adds confusion since this function had already been defined above (but I suggested removing it actually, hehe)

2020-11-16 14:47 UTC, SachaZvetelman commented on packages/f-checkout/src/components/tests/Checkout.test.js
> +            beforeEach(() => {
I think we normally create a `beforeEach` when we have things that are reused in multiple tests. Otherwise, we just include it in the tests, since it's easier to read.

2020-11-16 14:47 UTC, SachaZvetelman commented on packages/f-checkout/stories/Checkout.stories.js
> +        '<vue-checkout :checkoutMethod="checkoutMethod" checkoutUrl="/checkout.json" :locale="locale" />'
I'm not entirely sure what's the benefit of passing the `checkoutUrl` as a prop, and similarly, we probably need to ensure this works with non-relative paths (i.e. when we deploy this to other environments).

2020-11-16 14:47 UTC, SachaZvetelman commented on packages/f-checkout/stories/Checkout.stories.js
> +        '<vue-checkout :checkoutMethod="checkoutMethod" checkoutUrl="/checkout.json" :locale="locale" />'
One thing we should probably do is to provide a couple of different json files. One for delivery, one for collection. So then we provide a dropdown in storybook to choose between the two files?

2020-11-16 15:24 UTC, pkedziora commented on packages/f-checkout/stories/Checkout.stories.js
> +        '<vue-checkout :checkoutMethod="checkoutMethod" checkoutUrl="/checkout.json" :locale="locale" />'
@SachaZvetelman That's what registration component does and it makes sense because how else would you pass this to a component if it's hosted outside of fozzie-components.
Having dropdown with file selection makes sense

2020-11-16 15:26 UTC, pkedziora commented on packages/f-checkout/src/components/Checkout.vue
>          }
So that the calling page can configure the timeout

2020-11-17 10:11 UTC, pkedziora commented on packages/f-checkout/src/components/Selector.vue
>      }
Watch is needed to update the selected item in the drop down when the GET request comes back

2020-11-17 10:29 UTC, pkedziora commented on packages/f-checkout/package.json
> +     "axios-mock-adapter": "1.19.0"
Fixed

2020-11-17 10:31 UTC, pkedziora commented on packages/f-checkout/src/components/Checkout.vue
> +            buttonText: 'Go to payment',
Removed

2020-11-17 10:31 UTC, pkedziora commented on packages/f-checkout/src/components/Checkout.vue
> +            delivery: CHECKOUT_METHOD_DELIVERY,
Removed

2020-11-17 10:31 UTC, pkedziora commented on packages/f-checkout/src/components/Checkout.vue
> +            this.firstName = data.customer.firstName;
Fixed

2020-11-17 10:31 UTC, pkedziora commented on packages/f-checkout/src/components/Checkout.vue
> +            this.times = data.fulfillment.times;
I think we can assume that fulfillment will always be there

2020-11-17 10:32 UTC, pkedziora commented on packages/f-checkout/src/components/Selector.vue
> +            data-test-id="delivery-time"
Changed to fulfillment-time

2020-11-17 10:32 UTC, pkedziora commented on packages/f-checkout/src/components/tests/Checkout.test.js
> +        function CheckoutGetData (serviceType) {
Fixed

2020-11-17 10:32 UTC, pkedziora commented on packages/f-checkout/src/components/tests/Checkout.test.js
> +                CheckoutServiceApi.getCheckout.mockClear();
Fixed

2020-11-17 10:32 UTC, pkedziora commented on packages/f-checkout/src/components/tests/Checkout.test.js
> +        function CheckoutGetData () {
Removed

2020-11-17 10:33 UTC, pkedziora commented on packages/f-checkout/src/components/tests/Checkout.test.js
> +            beforeEach(() => {
I'm inclined to leave it as it's very likely more tests will be added here as the codebase grows

2020-11-17 11:46 UTC, pkedziora commented on packages/f-checkout/src/components/Checkout.vue
>          },
Removed

2020-11-17 11:47 UTC, pkedziora commented on packages/f-checkout/src/components/tests/Checkout.test.js
> +                    checkoutMethod: 'delivery',
Removed

2020-11-17 13:36 UTC, SachaZvetelman commented on packages/f-checkout/src/demo/demo.js
> +            checkoutMethod: 'delivery',
We can remove this now, right?

2020-11-17 13:36 UTC, SachaZvetelman commented on packages/f-checkout/src/components/tests/Checkout.test.js
> +                await wrapper.vm.$nextTick();
Do we need `$nextTick` in these tests?

2020-11-17 14:01 UTC, pkedziora commented on packages/f-checkout/src/components/tests/Checkout.test.js
> +                await wrapper.vm.$nextTick();
yes, tests fail without it as the ui doesn't get a chance to update after data change

2020-11-17 14:03 UTC, pkedziora commented on packages/f-checkout/src/demo/demo.js
> +            checkoutMethod: 'delivery',
Yep, well spotted. Removed

2020-11-17 14:03 UTC, SachaZvetelman approved these changes

2020-11-17 14:16 UTC, kevinrodrigues commented on packages/f-checkout/src/components/Checkout.vue
>              tenantConfigs,
Does `tenantConfigs` actually get used somewhere?

2020-11-17 14:16 UTC, kevinrodrigues commented on packages/f-checkout/src/components/Checkout.vue
> +    VALID_CHECKOUT_METHOD, CHECKOUT_METHOD_DELIVERY, CHECKOUT_METHOD_COLLECTION, TENANT_MAP
Could you break these onto separate lines please.

2020-11-17 14:16 UTC, kevinrodrigues commented on packages/f-checkout/src/components/Checkout.vue
> +                this.$emit(EventNames.CheckoutGetSuccess);
I assume this is listened to by the consuming app? Does the checkout component pass these listeners up? (Couldn't see it anywhere)

2020-11-17 14:29 UTC, tommcclean commented on packages/f-checkout/src/components/Checkout.vue
>              tenantConfigs,
It is used by the globalisation mixin, this is how the tenant configs get from a component and wired up to vue-i18n

https://www.npmjs.com/package/@justeat/f-globalisation#usage

2020-11-17 14:40 UTC, pkedziora commented on packages/f-checkout/src/components/Checkout.vue
> +    VALID_CHECKOUT_METHOD, CHECKOUT_METHOD_DELIVERY, CHECKOUT_METHOD_COLLECTION, TENANT_MAP
@kevinrodrigues this is outdated diff as this change is no longer there

2020-11-17 14:43 UTC, pkedziora commented on packages/f-checkout/src/components/Checkout.vue
> +                this.$emit(EventNames.CheckoutGetSuccess);
@kevinrodrigues calling component would be able to bind to those events. I assume the calling component can just bind to those with @ or v-on

2020-11-17 14:44 UTC, kevinrodrigues commented on packages/f-checkout/src/components/Checkout.vue
> +    VALID_CHECKOUT_METHOD, CHECKOUT_METHOD_DELIVERY, CHECKOUT_METHOD_COLLECTION, TENANT_MAP
Ah my bad!

2020-11-17 14:47 UTC, kevinrodrigues commented on packages/f-checkout/src/components/Checkout.vue
> +                this.$emit(EventNames.CheckoutGetSuccess);
Yeah should be able to provided that the component is passing those emits up when it's being used. Normally the base component or the component that's going to be used in the consuming app would need to set `v-on="$listeners"` so that the `@` can be used. This is how i've done it before but it might work differently in how you guys are building checkout so wanted to check.

2020-11-17 14:52 UTC, kevinrodrigues approved these changes
LGTM - only that emit question, could be looked at separately tho.

2020-11-17 14:54 UTC, merged