fozzie-components@v2.17.0 - Consolidate data-test-ids and data-js-test attributes #globalconfig
justeattakeaway/fozzie-components pull request #446
Opened 2020-11-17 15:38 UTC by LTurns

### Changed

- Consolidated test ids - replaced `data-js-test` attribute with `data-test-id` where possible, to be shared by unit and component tests. The only test ids in the repo should now be either 'data-test-id' or 'data-theme-{component-name}', where required.

2020-11-17 15:42 UTC, xander-marjoram commented on packages/f-header/test-utils/component-objects/f-header.component.js
> +//do one for offerslinkdesktop too
@LTurns Do we have a ticket for this or is this still a WIP?

2020-11-17 15:43 UTC, xander-marjoram commented on packages/f-registration/test-utils/component-objects/f-registration.component.js
>  const firstNameInvalidError = () => $('[data-test-title="error-first-name-invalid"]');
I think you missed this one 😄

2020-11-17 15:49 UTC, LTurns commented on packages/f-header/test-utils/component-objects/f-header.component.js
> +//do one for offerslinkdesktop too
@xander-marjoram think I'll quickly do that now actually - should only be one small test. Thanks for reminding me!

2020-11-17 15:50 UTC, LTurns commented on packages/f-registration/test-utils/component-objects/f-registration.component.js
>  const firstNameInvalidError = () => $('[data-test-title="error-first-name-invalid"]');
whoops, thank youu!

2020-11-17 18:59 UTC, ashleynolan commented
I've added `#globalconfig` to your title so that it stops asking for CHANGELOG entries at package level

2020-11-18 08:33 UTC, LTurns commented
> I've added `#globalconfig` to your title so that it stops asking for CHANGELOG entries at package level

thanks Ash, will remember to do that next time! :)

2020-11-18 10:53 UTC, siggerzz commented on packages/f-header/test-utils/component-objects/f-header.component.js
> +const offersLinkDesktop = () => $('[data-test-id="offers-link-desktop]"');
Is there a way we can consolidate this into a single selector that can be used for both mobile and desktop?

2020-11-18 10:54 UTC, siggerzz requested changes
See comments!

2020-11-18 11:25 UTC, xander-marjoram commented on packages/f-header/test-utils/component-objects/f-header.component.js
> +const offersLinkDesktop = () => $('[data-test-id="offers-link-desktop]"');
Could we have two data-test-ids on each link, one "offers-link-mobile/desktop" for the mobile/desktop tests and one "offers-link" for generic use?

2020-11-18 11:45 UTC, minrwhite commented on packages/f-header/test-utils/component-objects/f-header.component.js
> +const offersLinkDesktop = () => $('[data-test-id="offers-link-desktop]"');
Wouldn't the attribute starts-with selector `$('[data-test-id^="offers-link"]')` suffice for [the case where we need to match either]? Also the closing quotes and square-parens are in the wrong order above: 
```suggestion
const offersLinkDesktop = () => $('[data-test-id="offers-link-desktop"]');
```

2020-11-18 11:54 UTC, minrwhite commented on packages/f-header/test-utils/component-objects/f-header.component.js
> +const offersLinkMobile = () => $('[data-test-id="offers-link-mobile]"');
This line also needs that change:
```suggestion
const offersLinkMobile = () => $('[data-test-id="offers-link-mobile"]');
```

2020-11-18 14:18 UTC, minrwhite approved these changes

2020-11-18 15:08 UTC, siggerzz approved these changes

2020-11-18 15:09 UTC, merged