fozzie-components@v2.19.0 - Added webdriver tests for f-header and video-reporting
justeattakeaway/fozzie-components pull request #462
Opened 2020-11-24 15:09 UTC by LTurns

### Added
- Additional webdriver tests for f-header.
- Allure reporter in the package.json script of each component folder (so it can be called more easily).
- Video reporter in wdio.conf so errors are shown via recording in allure report.

2020-11-26 14:31 UTC, siggerzz commented on packages/f-footer/test/specs/component/f-footer.component.spec.js
> +        browser.back();
Do we need to go back after we've already done our assert?

2020-11-26 14:32 UTC, siggerzz commented on packages/f-header/test-utils/component-objects/f-header.component.js
>  exports.isLogoDisplayed = () => headerLogo().isDisplayed();
Can we use the same isDisplayedInViewport here too?

2020-11-26 14:33 UTC, siggerzz commented on packages/f-header/test/specs/component/f-header.component.spec.js
> +        browser.setWindowSize(500, 500)
Are we trying to emulate mobile here? If so, it might be worth to try and enter emulation mode instead somehow (we can look into this!)

2020-11-26 14:33 UTC, siggerzz commented on packages/f-header/test/specs/component/f-header.component.spec.js
> +         browser.setWindowSize(1000, 1000);
ditto (but for desktop)

2020-11-26 14:34 UTC, siggerzz requested changes
Few comments to address, but otherwise looking good!

2020-11-26 14:55 UTC, LTurns commented on packages/f-header/test-utils/component-objects/f-header.component.js
>  exports.isLogoDisplayed = () => headerLogo().isDisplayed();
yep can change that

2020-11-26 14:56 UTC, LTurns commented on packages/f-header/test/specs/component/f-header.component.spec.js
> +        browser.setWindowSize(500, 500)
yeah that was the aim, that sounds good!

2020-11-27 11:10 UTC, siggerzz submitted a review, later dismissed

2020-11-27 11:47 UTC, minrwhite commented on wdio.conf.js
> +    },
```suggestion
    }
```

2020-11-27 11:50 UTC, minrwhite commented on packages/f-header/test-utils/component-objects/f-header.component.js
> +const offersLink = () =>$$('[data-test-id="offers-link"]');
Typo on the double `$`?

2020-11-27 11:57 UTC, minrwhite commented on packages/f-button/package.json
> +    "report": "cd ../.. && yarn report",
For each of these packages, is this simply a convenience script for CLI access to the allure report when within a package?

2020-11-27 11:58 UTC, LTurns commented on packages/f-header/test-utils/component-objects/f-header.component.js
> +const offersLink = () =>$$('[data-test-id="offers-link"]');
it's actually part of the syntax in webdriver - lets you grab multiple elements with the same id

2020-11-27 11:59 UTC, LTurns commented on packages/f-button/package.json
> +    "report": "cd ../.. && yarn report",
yeah exactly, seemed to make things easier than having to cd out of folders before running the report 👍

2020-11-27 13:10 UTC, minrwhite commented on packages/f-header/test-utils/component-objects/f-header.component.js
> +const offersLink = () =>$$('[data-test-id="offers-link"]');
Cool, that makes sense - in that case, please keep the space in between the `=>` and the first `$` then, to make it clear and consistent.

2020-11-27 13:43 UTC, LTurns commented on packages/f-header/test-utils/component-objects/f-header.component.js
> +const offersLink = () =>$$('[data-test-id="offers-link"]');
ooh yes thank you - will do that now

2020-11-30 11:50 UTC, minrwhite approved these changes

2020-11-30 12:27 UTC, JoshuaNg2332 approved these changes

2020-11-30 13:28 UTC, merged