fozzie-components@1.2.0 – Consoildate utility methods in f-header and f-footer
justeattakeaway/fozzie-components pull request #49
Opened 2019-09-12 14:01 UTC by smilburn1990

## Changelog

### Changed
- Service has been made to handle duplicate code in header and footer.
- Gitignore updated
- Vue for header and footer changed and methods removed

## TODO
- Write tests for services

👍

2019-09-12 14:32 UTC, BanksySan submitted a review, later dismissed

2019-09-16 08:34 UTC, dandel10n requested changes
@smilburn1990 hey!

LGTM only few small things:

- I think that `@babel/plugin-proposal-optional-chaining` should be added as a dev dependency on mono repo root level package.json to avoid duplication in children packages.
- Maybe we need to make a folder for shared services? Now we have `packages/f-header`,  `packages/f-footer` etc and a js file with shared service.
- And a conflict needs to be resolved

2019-09-18 10:22 UTC, ashleynolan commented on services/shared.service.js
> +
Looks like there's a duplicate of this file here and at the base of `/packages`?

2019-09-18 10:23 UTC, ashleynolan commented on services/shared.service.js
> +/**
Also, would be good to have some tests for these service functions (might be worth putting in a TODO, unless you fancy making these as realise you're just moving them).

2019-09-18 10:24 UTC, smilburn1990 commented on services/shared.service.js
> +
Still WIP @ashleynolan - sorry my bad. Will let you know when it needs review 👍

2019-09-18 10:24 UTC, smilburn1990 commented on services/shared.service.js
> +/**
Can we get a ticket created? Who is the best person to speak to? @ashleynolan

2019-09-18 12:34 UTC, ashleynolan commented on services/shared.service.js
> +/**
We usually just create the tickets ourselves as we come across them – would add this to the [header epic](https://jira.just-eat.net/browse/WCP-107).  If you don't have access, let Darren know and he can make sure you have access.

2019-09-18 12:38 UTC, smilburn1990 commented on services/shared.service.js
> +/**
@ashleynolan - i will add one now, can you approve this when you get a moment, would be nice to move some stuff over today :)

2019-09-18 12:46 UTC, ashleynolan submitted a review, later dismissed
LGTM – think it just needs @dandel10n to re-review.

2019-09-18 13:31 UTC, DamianMullins submitted a review, later dismissed
Needs a version bump and changelog entry.

2019-09-18 14:41 UTC, dandel10n commented
@DamianMullins @ashleynolan  this change is related more to monorepo structure, moving repeated logic out of component level, than to one of the packages. Do you think it is worth to update both `f-footer` and `f-header` versions and changelogs?

2019-09-18 14:47 UTC, ashleynolan commented
@dandel10n If it's more of a mono-repo change, then the CHANGELOG in the root should be updated and the package.json there updated. If there's changes to header/footer though too, they'll also need a CHANGELOG entry and package bump as it should be a versioned release for both of them.

We probably need to document the process for changes like this but in essence, all packages that change should have a `version` and `CHANGELOG` entry so that it's traceable (mainly for if a bug occurs and we need to look back at version history).

2019-09-18 15:44 UTC, dandel10n approved these changes

2019-09-18 15:48 UTC, ashleynolan approved these changes

2019-09-18 15:49 UTC, merged

2019-09-18 15:52 UTC, SachaZvetelman commented on .gitignore
> +package-lock.json
We shouldn't be ignoring this file, in my opinion.

2019-09-19 08:51 UTC, ashleynolan commented on .gitignore
> +package-lock.json
We should have a `yarn.lock`, so it shouldn't be an issue to ignore the `package-lock.json`.