f-checkout@0.31.0 - Storybook component tests
justeattakeaway/fozzie-components pull request #546
Opened 2020-12-15 16:00 UTC by JoshuaNg2332

v0.31.0
------------------------------
*December 23, 2020*

### Changed
- Updated skipped tests to work with Storybook component tests.

### Added
- New `clearCheckoutForm` function added to clear the fields in tests in the `f-checkout-component.js` file.

2020-12-15 17:18 UTC, minrwhite commented on packages/f-checkout/test/specs/component/f-checkout.component.spec.js
>          // Waiting for route here, so we can grab redirect url and show form submits.
Should we be asserting something here?

2020-12-15 17:18 UTC, minrwhite commented on packages/f-checkout/test/specs/component/f-checkout.component.spec.js
> +    it('should enable a user to submit without adding a note', () => {
And should we assert in this test also?

2020-12-15 17:18 UTC, minrwhite commented on packages/f-checkout/test/specs/component/f-checkout-collection.component.spec.js
> +    before(() => {
Can I ask, why the change from 'beforeEach()'?

2020-12-15 17:21 UTC, JoshuaNg2332 commented on packages/f-checkout/test/specs/component/f-checkout.component.spec.js
>          // Waiting for route here, so we can grab redirect url and show form submits.
We're not asserting anything here yet as we don't have the URLs to test this just yet.

2020-12-15 17:21 UTC, JoshuaNg2332 commented on packages/f-checkout/test/specs/component/f-checkout.component.spec.js
> +    it('should enable a user to submit without adding a note', () => {
Same as above. We need the URLs to assert stuff here.

2020-12-16 08:23 UTC, SachaZvetelman requested changes

2020-12-16 08:23 UTC, SachaZvetelman commented on packages/f-checkout/test-utils/component-objects/f-checkout-selectors.js
> +export const KNOB_CHECKOUT_DROPDOWN = '[name="Checkout Url"]';
I'd add a `data-test-id` to this element and use it instead of the name.

2020-12-16 08:23 UTC, SachaZvetelman commented on packages/f-checkout/test-utils/component-objects/f-checkout.component.js
>  const orderTimeDropdownOptions = () => $$(ORDER_TIME_DROPDOWN_OPTIONS);
I know you haven't modified this line, but is this `$$` correct?

2020-12-16 08:23 UTC, SachaZvetelman commented on packages/f-checkout/test-utils/component-objects/f-checkout.component.js
> +exports.changeToCollectionMethod = () => {
I'd personally make this function more generic so it will also work to change to `delivery` as well if we needed. Not a must-have right now, tho.

2020-12-16 08:23 UTC, SachaZvetelman commented on packages/f-checkout/test/specs/component/f-checkout-collection.component.spec.js
> +        expect(CheckoutComponent.isFieldVisible(field)).toBe(false);
I'm a bit confused between the name of the test and the assertion. A field could exist without being visible.
The assertion probably should be to check the element exists, rather than if it's visible or not. 😄

2020-12-16 08:23 UTC, SachaZvetelman commented on packages/f-checkout/test/specs/component/f-checkout-delivery.component.spec.js
> +    before(() => {
Same as above from Ben.

2020-12-16 08:23 UTC, SachaZvetelman commented on packages/f-checkout/test/specs/component/f-checkout-delivery.component.spec.js
>              mobileNumber: '+4512345678911'
I know this was added on a previous PR, but this is not necessarily a wrong number format. I believe this would be valid in Denmark, so we should either change the test name, the value of `mobileNumber` or something else.
For example, we could be existing that for UK, it should display an error if the number doesn't start with `+44`, although you need to be careful since a valid UK number without `+44` is still...valid, hehe. Feel free to address this in a separate PR.

2020-12-16 08:23 UTC, SachaZvetelman commented on packages/f-checkout/test/specs/component/f-checkout.component.spec.js
> +    it('should prevent user from writing a note of over 200 characters', () => {
I don't remember, so this comment may be irrelevant, but do we show an error message saying the max limit is 200 characters for notes when users reach it? If we do, we should have a test for that.

2020-12-16 08:23 UTC, SachaZvetelman commented on packages/f-checkout/test/specs/component/f-checkout.component.spec.js
>          CheckoutComponent.selectOrderTime('As soon as possible');
More of a general question for all of us to think about rather than a specific comment on this PR.
Going forward, how are we planning to test each tenant shows the right text? This test would automatically fail for non-English tenants. Not a big concern now, since it's the UK first, but I'd like to at least think about how we want to tackle this.
cc @Festivejelly, @xander-marjoram, @siggerzz, @LTurns.

2020-12-16 08:24 UTC, SachaZvetelman commented on packages/f-checkout/test/specs/component/f-checkout-collection.component.spec.js
> +        expect(CheckoutComponent.isFieldVisible(field)).toBe(false);
One more tiny comment on this. We should stick to the same naming convention for our functions. It should be `doesFieldExist` rather than `doesInputFieldExist`, right? (again, not your PR, but still).

2020-12-16 09:37 UTC, LTurns commented on packages/f-checkout/test/specs/component/f-checkout-collection.component.spec.js
> +    before(() => {
this was me actually - 'before' is the mocha equivalent of beforeAll in jest. Since we only want to go to the checkout url and click on collection once, it made more sense to change it so the page didn't keep reloading and switching back and fourth to delivery before every test - some tests were failing/passing inconsistently due to the time spent reloading the page. Hope that helps! :)

2020-12-16 09:40 UTC, JoshuaNg2332 commented on packages/f-checkout/test/specs/component/f-checkout-collection.component.spec.js
> +        expect(CheckoutComponent.isFieldVisible(field)).toBe(false);
Yeah, so I've looked into this and for some reason, and we can't check the field exists because when you try to do that after switching the checkout method, the fields are still visible to the tests in the DOM when switched from delivery to collection. So I've had to use the function `.isDisplayedInViewport()` to get this test to pass. We're trying to test that it can be seen in this instant.

Agreed. This is something from a previous PR that has a sister function next to it called `doesErrorMessageExist`. I can make this change.

2020-12-16 09:44 UTC, JoshuaNg2332 commented on packages/f-checkout/test/specs/component/f-checkout.component.spec.js
> +    it('should prevent user from writing a note of over 200 characters', () => {
Just checked this on storybook. This doesn't allow the user to go over 200 characters. So there isn't an error message for that.

2020-12-16 09:57 UTC, SachaZvetelman commented on packages/f-checkout/test/specs/component/f-checkout-collection.component.spec.js
> +        expect(CheckoutComponent.isFieldVisible(field)).toBe(false);
I'm not sure I fully understood, but it's probably me 😬 
Do you need some time from one of the Engineers to help to see if it's possible to assert the field exists instead, or not really?

2020-12-16 10:21 UTC, JoshuaNg2332 commented on packages/f-checkout/test-utils/component-objects/f-checkout.component.js
>  const orderTimeDropdownOptions = () => $$(ORDER_TIME_DROPDOWN_OPTIONS);
@LTurns Correct me if I'm wrong, but is this so that we can allow the selector to choose something within the selector?

2020-12-16 10:28 UTC, JoshuaNg2332 commented on packages/f-checkout/test/specs/component/f-checkout-collection.component.spec.js
> +        expect(CheckoutComponent.isFieldVisible(field)).toBe(false);
I'm not sure. As me and @LTurns tested this for a while to get this working. So in this test, we're checking that the fields are actually **not** visible (as opposed to it not existing in the dom). Happy to jump on a call when you are free to explain my thinking here.

2020-12-16 11:09 UTC, LTurns commented on packages/f-checkout/test-utils/component-objects/f-checkout.component.js
>  const orderTimeDropdownOptions = () => $$(ORDER_TIME_DROPDOWN_OPTIONS);
yep, we use $$ to fetch multiple elements - it treats them like an array so is useful for lists and dropdowns. Means you can write syntax like $$(dropdown)[0] to grab the first option for example 👍

2020-12-16 11:14 UTC, LTurns commented on packages/f-checkout/test/specs/component/f-checkout.component.spec.js
>          CheckoutComponent.selectOrderTime('As soon as possible');
My first thought would be to do something similar to what we've done here using the storybook knob button - but instead of changing the URL, we change the tenant and then write a test suite to check the text is correct. Not sure if it's the most scalable option though if we have 20 tenants, but useful for testing these in isolation with storybook. Happy to look into doing a spike for this in future 👍

2020-12-16 12:12 UTC, JoshuaNg2332 commented on packages/f-checkout/test/specs/component/f-checkout-collection.component.spec.js
> +        expect(CheckoutComponent.isFieldVisible(field)).toBe(false);
Ok, so some derping around and got the original, `doesFieldExist`(formally `doesInputFieldExist` 😉 ) test working as expected. So rather than ditching the visibility test, will add this as it's own seperate test so it actually tests for visibility on the page as opposed to visible in the DOM or it existing.

2020-12-16 13:07 UTC, Preet-Sandhu commented on packages/f-checkout/test/specs/component/f-checkout.component.spec.js
>          CheckoutComponent.selectOrderTime('As soon as possible');
Looked at this with Lizzie. Would be good to do a spike and explore different options.

2020-12-16 13:08 UTC, Preet-Sandhu commented on packages/f-checkout/test-utils/component-objects/f-checkout-selectors.js
> +export const KNOB_CHECKOUT_DROPDOWN = '[name="Checkout Url"]';
+1

2020-12-16 13:55 UTC, JoshuaNg2332 commented on packages/f-checkout/test/specs/component/f-checkout-delivery.component.spec.js
>              mobileNumber: '+4512345678911'
Ticket created for this.

2020-12-16 13:59 UTC, JoshuaNg2332 commented on packages/f-checkout/test-utils/component-objects/f-checkout-selectors.js
> +export const KNOB_CHECKOUT_DROPDOWN = '[name="Checkout Url"]';
@SachaZvetelman Do you know how to add `data-test-id` to a storybook element? This isn't a `data-test-id` for the component but for storybook itself and we're not sure you can do that as it's sorta the same as adding a `data-test-id` to a webpage not hosted by us.

2020-12-16 16:14 UTC, JoshuaNg2332 commented on packages/f-checkout/test-utils/component-objects/f-checkout-selectors.js
> +export const KNOB_CHECKOUT_DROPDOWN = '[name="Checkout Url"]';
So looking through the documentation, we couldn't find anything with regards to setting attributes on the generated HTML so we believe this can't be done.

2020-12-16 16:45 UTC, JoshuaNg2332 commented on packages/f-checkout/test/specs/component/f-checkout.component.spec.js
>          CheckoutComponent.selectOrderTime('As soon as possible');
Agreed with the above and chatting to Lizzie about this earlier, we could have the tenants called into the component.js file and the tests referring to the different tenants based on the locale setting. A spike would probably the best to explore options.

2020-12-16 17:04 UTC, siggerzz commented on packages/f-checkout/test/specs/component/f-checkout.component.spec.js
>          CheckoutComponent.selectOrderTime('As soon as possible');
My preference would be to avoid asserting on translation strings, and instead assert on something else instead. (perhaps that the dropdown option has a `value` attribute of 'ASAP'? (This will require some changes to the dropdown vue component though).

We can then test translations via visual regression instead as it'll be less expensive / maintenance. From my own experience in other repos, I've just found asserting on text to be fragile.

Happy to look at this in the new year though 👍 


(I'm going now, bye! 🏃‍♂️💨)

2020-12-16 17:08 UTC, siggerzz commented on packages/f-checkout/test-utils/component-objects/f-checkout.component.js
> +exports.changeCheckoutPage = index => {
I'd rename this to `changeCheckoutMethod` just to make it a bit clearer, then do `knobCheckoutDropdown().selectByText(text);` instead.

Then in the spec, you'll call it as: 

`CheckoutComponent.changeCheckoutMethod('Delivery');`

2020-12-16 17:28 UTC, JoshuaNg2332 commented on packages/f-checkout/test/specs/component/f-checkout.component.spec.js
>          CheckoutComponent.selectOrderTime('As soon as possible');
I've created a ticket to initiate a spike for this on the board. 👍🏼

2020-12-17 09:26 UTC, JoshuaNg2332 commented on packages/f-checkout/test-utils/component-objects/f-checkout.component.js
> +exports.changeCheckoutPage = index => {
Looked into this and we can't call it by `'Delivery'` as the text used uses, `/checkout-delivery.json`. Would you want that as the name?

2020-12-23 11:38 UTC, DamianMullins submitted a review, later dismissed

2020-12-23 11:56 UTC, SachaZvetelman commented on packages/f-checkout/test-utils/component-objects/f-checkout.component.js
> +    fields.mobileNumber.input().setValue([' ', "\uE003"]);
I'd extract `setValue([' ', "\uE003"])` into a separate function that can be reused across the board. Otherwise, it's not really clear what we're doing here for those who are unaware of the issue.
Similarly, I'd extract that unicode backspace into a `const` that shows what it is 🙂

2020-12-23 11:56 UTC, SachaZvetelman commented on packages/f-checkout/test-utils/component-objects/f-checkout.component.js
> +exports.changeCheckoutMethod = index => {
Is it possible to pass `delivery` or `collection` instead? Since people might not know which index belongs to each of them. Alternatively, let's add something like `index 0 = delivery, index 1 = collection` to the JSDoc above.

2020-12-23 11:56 UTC, SachaZvetelman commented on packages/f-checkout/test/specs/component/f-checkout-collection.component.spec.js
> +        const incorrectMobileNumber = {
We're calling this `addressDetails` in other tests, maybe we should stick to the same.

2020-12-23 12:53 UTC, JoshuaNg2332 commented on packages/f-checkout/test-utils/component-objects/f-checkout.component.js
> +exports.changeCheckoutMethod = index => {
Ben suggested a similar thing with passing `delivery` or `collection` and using a `.selectByText` above but I've looked into this and the text i pass would have be `/checkout-delivery.json` as thats the text used in storybook. I'm not to sure of an elegant way of implementing this. 🤔 
Just looked into labelling the knobs and broke my local ver of storybook 😅  in the process. I want to revisit this in a separate PR. In the meantime, I'll add this comment into the JSDoc as recommended.

2020-12-23 13:05 UTC, SachaZvetelman commented on packages/f-checkout/test-utils/component-objects/f-checkout.component.js
> +exports.changeCheckoutMethod = index => {
Well, you could always do something like:
```
exports.changeCheckoutMethod = method => {
    const file = `checkout-${method}.json`;
    ...
}
```

2020-12-24 09:43 UTC, ashleynolan approved these changes

2020-12-24 11:14 UTC, Preet-Sandhu commented on packages/f-checkout/test/specs/component/f-checkout-delivery.component.spec.js
>      });
Is this test duplicated above? 

it('should display "mobileNumber" error message when collection method is set and number is incorrect', () =>

2020-12-24 11:22 UTC, JoshuaNg2332 commented on packages/f-checkout/test/specs/component/f-checkout-delivery.component.spec.js
>      });
This is supposed to be a seperate test that tests the formatting of a number. So a number has been entered, but not a supported format (e.g. not a Tenant phone code we support). The other test above tests the error message appears if the field is blank.

2020-12-30 15:45 UTC, ashleynolan requested changes
Marking this as do not merge. This PR will need refactoring once the folder structure is changed (probably easier to make a copy of the changes you have made and re-apply them to the new locations, as merging will likely give you a bunch of conflicts)

2021-01-05 15:34 UTC, siggerzz approved these changes

2021-01-05 16:16 UTC, JoshuaNg2332 commented
This PR is being closed as a new PR was opened to address the changes to the Fozzie folder structure that this PR needed to incorporate. 
This PR is now defunct with an updated version of it found [here](https://github.com/justeat/fozzie-components/pull/562).

2021-01-05 16:16 UTC, closed without merging