f-checkout@0.27.0 - vuex mutations and actions for input fields updates
justeattakeaway/fozzie-components pull request #549
Opened 2020-12-18 12:23 UTC by dandel10n

### Changed
- Replaced direct state manipulations with mutations and actions

It is still wip, but I would appreciate some feedback.
Test should be added to this PR shortly

I am fine with upcoming repo restructuring in the end of December, I will move my changes to the fresh master in January

2020-12-18 12:28 UTC, DamianMullins commented on packages/f-checkout/src/components/Address.vue
> +            this.$store.dispatch('checkout/updateFulfilmentAddress', {
You should be able to use the mapped action here and below?

```suggestion
            this.updateFulfilmentAddress({
```

2020-12-18 12:30 UTC, DamianMullins commented on packages/f-checkout/src/components/Checkout.vue
> +            this.$store.dispatch('checkout/updateMobileNumber', value)
Should be able to map the `updateMobileNumber` action in `mapActions` above and call the action directly?

2020-12-18 13:20 UTC, DamianMullins commented on packages/f-checkout/src/store/checkout.module.js
> +        updateFulfilmentAddress ({ commit }, payload) {
NIT: Add a space between actions.

2020-12-18 13:20 UTC, DamianMullins commented on packages/f-checkout/src/store/checkout.module.js
> +        },
NIT: Add a space between mutations.

2020-12-18 13:46 UTC, matthewhardern commented on packages/f-checkout/src/components/Address.vue
> +        updateAddressLine1(value) {
Question should the methods have jsdoc comments?

2020-12-30 15:45 UTC, ashleynolan requested changes
Marking this as do not merge. This PR will need refactoring once the folder structure is changed (probably easier to make a copy of the changes you have made and re-apply them to the new locations, as merging will likely give you a bunch of conflicts)

2021-01-04 11:20 UTC, closed without merging