f-header@v4.4.0 - Updated feature tests with selector.js file
justeattakeaway/fozzie-components pull request #550
Opened 2020-12-18 14:43 UTC by LTurns

v4.4.0
------------------------------
*December 18, 2020*

### Changed
- Updated Webdriver test-utils to include `selector` file.
- Refactored component tests.

Updated beforeHook to take in a new storybook URL which can then be edited to include add-ons - happy to discuss this if people prefer the original way, but it seemed to make testing slightly easier. :)

2020-12-18 16:03 UTC, simonsandersje approved these changes

2020-12-21 12:40 UTC, siggerzz commented on packages/f-header/test-utils/component-objects/f-header.component.js
> +        icon: () => $$(NAVIGATION.offers.link)
Should this be `NAVIGATION.offers.icon`?

2020-12-21 12:44 UTC, siggerzz commented on packages/f-header/test/specs/component/f-header.component.spec.js
> +        browser.setWindowSize(500, 500);
Nit: Might be worth refactoring this at some point to use the built-in Storybook viewport feature

2020-12-21 12:44 UTC, siggerzz commented on packages/f-header/test/specs/component/f-header.component.spec.js
> +        browser.setWindowSize(1000, 1000);
ditto

2020-12-21 12:44 UTC, siggerzz commented on packages/f-header/test/specs/component/f-header.component.spec.js
> +        browser.setWindowSize(500, 1000);
ditto

2020-12-21 12:44 UTC, siggerzz requested changes
Just a few comments 👍

2020-12-22 12:10 UTC, LTurns commented on packages/f-header/test/specs/component/f-header.component.spec.js
> +        browser.setWindowSize(500, 500);
ooh yes great shout

2020-12-22 12:32 UTC, LTurns commented on packages/f-header/test-utils/component-objects/f-header.component.js
> +        icon: () => $$(NAVIGATION.offers.link)
ah so to grab the icon, I'm using the same data-test-id as link, but just iterating over it with $$, which is why I didn't add icon to the NAVIGATION object. Happy to refactor later down the line if you think it'll be clearer though?
I'm on holiday too now so might be better looking into as a separate PR and getting this one merged before Ash makes changes to the folder structure 😄

2020-12-30 15:44 UTC, ashleynolan requested changes
Marking this as do not merge. This PR will need refactoring once the folder structure is changed (probably easier to make a copy of the changes you have made and re-apply them to the new locations, as merging will likely give you a bunch of conflicts)

2021-01-04 09:01 UTC, LTurns commented
> Marking this as do not merge. This PR will need refactoring once the folder structure is changed (probably easier to make a copy of the changes you have made and re-apply them to the new locations, as merging will likely give you a bunch of conflicts)

perfect, thanks @ashleynolan, will do this today 😄

2021-01-04 13:42 UTC, closed without merging