f-header@2.0.0-beta.9 - header authentication service
justeattakeaway/fozzie-components pull request #56
Opened 2019-09-17 15:47 UTC by smilburn1990

### Changelog

### Changed
- Unit tests to reflect changed in component
- Snapshot for test

#### Added
- New logic to create return URL
- computed for `showDeliveryEnquiryWithContent`
- New snapshot for tests
- Axios for new logic
- New logic for retrieving user info 

### TODO
- Update docs

👍

2019-09-20 11:08 UTC, pikax requested changes

2019-09-20 11:08 UTC, pikax commented on package.json
> +    "@justeat/f-logger": "^0.7.1",
Can you remove the `^`, just to target a specific version.

2019-09-20 11:08 UTC, pikax commented on packages/f-header/src/components/Navigation.vue
> +                    v-if="!userInfo"
```suggestion
                    v-else
```

2019-09-20 11:08 UTC, pikax commented on packages/f-header/src/components/Navigation.vue
> +                        :href="`${accountLogin.url}${returnUrl}`"
can you create a `computed` for this link?

2019-09-20 12:26 UTC, smilburn1990 commented on packages/f-header/src/components/Navigation.vue
> +                    v-if="!userInfo"
@pikax - The logout is show on the else but it is embedded inside elements, so this won't work

2019-09-20 12:29 UTC, pikax commented on packages/f-header/src/components/Navigation.vue
> +                    v-if="!userInfo"
you right, it seemed to be the next `li`, my bad

2019-09-20 12:34 UTC, smilburn1990 commented on packages/f-header/src/components/Navigation.vue
> +                        :href="`${accountLogin.url}${returnUrl}`"
I think it's a bit overkill considering on `login` and `logout` use it but I'm happy to if anyone else agrees

2019-09-20 12:35 UTC, smilburn1990 commented on packages/f-header/src/components/Navigation.vue
> +                        :href="`${accountLogin.url}${returnUrl}`"
`returnUrl` is already a computed property

2019-09-20 12:37 UTC, pikax commented on packages/f-header/src/components/Navigation.vue
> +                        :href="`${accountLogin.url}${returnUrl}`"
but your `href` = `accountLogin.url + returnUrl`, personally I like to add almost everything as computed or data.

2019-09-20 12:42 UTC, DamianMullins reviewed
Should remove the `package-lock.json` file as everyone should be using Yarn.

2019-09-20 12:42 UTC, smilburn1990 commented on packages/f-header/src/components/Navigation.vue
> +                        :href="`${accountLogin.url}${returnUrl}`"
All done pushing now 👍

2019-09-20 12:44 UTC, DamianMullins commented on package.json
> +    "@justeat/f-logger": "^0.7.1",
One issue with adding this as a dependency is that we won't be able to run any CI tasks on Travis as it is an internal package.

One way around this is to inject the logger via a prop?

2019-09-20 12:44 UTC, smilburn1990 commented on package.json
> +    "@justeat/f-logger": "^0.7.1",
I'll do that 👍

2019-09-20 12:46 UTC, smilburn1990 commented on package.json
> +    "@justeat/f-logger": "^0.7.1",
Or is it easier to just use `console.log`? Using it as a prop opens a lot of pitfalls when the prop doesn't get passed @DamianMullins

2019-09-20 12:47 UTC, DamianMullins commented on package.json
> +    "@justeat/f-logger": "^0.7.1",
`console.log` won't give us any visibility of errors occurring, `just-log` pushes logs to an endpoint which allows us to view those logs in Kibana.

2019-09-20 12:49 UTC, smilburn1990 commented on package.json
> +    "@justeat/f-logger": "^0.7.1",
Ahh gotcha. So shall I pass props as a `[Function, Boolean]` and set the deafault as `false` with required `true`? @DamianMullins

2019-09-20 12:53 UTC, pikax commented on package.json
> +    "@justeat/f-logger": "^0.7.1",
I would create a prop `Function`, where you can send any number of arguments, the default would be an dummy function:
```js
props:{
  log: {type: Function, default: ()=>({})}
}
```

2019-09-20 13:04 UTC, pikax commented on packages/f-header/package.json
> +    "axios": "^0.19.0",
shouldn't be version specific? `without ^`

2019-09-20 13:04 UTC, pikax commented on packages/f-header/CHANGELOG.md
> + - Props in `Navigation.vue`
Do you mind add what props you added? 
Also add them to [readme.md](https://github.com/justeat/fozzie-components/tree/master/packages/f-header)

2019-09-20 13:06 UTC, smilburn1990 commented on packages/f-header/CHANGELOG.md
> + - Props in `Navigation.vue`
We are updating documentation to another ticket 💃 Will updated the Todo on the PR

2019-09-20 13:20 UTC, pikax commented on packages/f-header/src/components/Header.vue
> +            required: true
does it need to be required?

2019-09-20 13:21 UTC, smilburn1990 commented on packages/f-header/src/components/Header.vue
> +            required: true
Changed

2019-09-20 13:22 UTC, pikax submitted a review, later dismissed

2019-09-20 13:28 UTC, dandel10n commented on packages/f-header/src/components/Header.vue
> +                :just-log="justLog" />
You still have `:user-info="userInfo"` on line 15, should it be removed?

2019-09-20 13:31 UTC, smilburn1990 commented on packages/f-header/src/components/Header.vue
> +                :just-log="justLog" />
Nice spot. Changed 👍 @dandel10n

2019-09-20 13:33 UTC, pikax submitted a review, later dismissed

2019-09-20 13:41 UTC, DamianMullins commented
`package-lock.json` is still in the PR.

2019-09-20 13:41 UTC, dandel10n commented on packages/f-header/src/components/Navigation.vue
> +            return `${this.accountLogout.url}${this.returnUrl}`;
Could you please explain what the behaviour will be if returnUrl is false (when there is no `this.$route`)
As I understand `accountLogout.url = '/account/logout?returnurl='` will come from the resource files. Will it be enough?

2019-09-20 13:41 UTC, DamianMullins commented on packages/f-header/package.json
> +    "@justeat/f-vue-icons": "^1.0.0-beta.4",
Remove the `^` here.

2019-09-20 13:42 UTC, DamianMullins commented on packages/f-footer/package.json
> +    "@justeat/f-vue-icons": "^1.0.0-beta.4",
Remove the `^` here.

2019-09-20 13:43 UTC, dandel10n commented on packages/f-header/src/components/Header.vue
> +                :just-log="justLog" />
Could you change the props list in README for the f-header please

2019-09-20 13:44 UTC, DamianMullins commented on packages/f-header/src/components/Navigation.vue
> +                if (data) this.userInfo = data;
Can you wrap this in parathesis to keep it consistent with the code style used in our codebases, please?

2019-09-20 13:45 UTC, DamianMullins commented on packages/f-header/src/components/Navigation.vue
> +        async returnUserDetails () {
Maybe `setUserDetails` might better describe what this method is doing?

2019-09-20 13:46 UTC, DamianMullins commented on yarn.lock
> +  resolved "http://packages.je-labs.com/npm/private-npm/@babel/plugin-proposal-optional-chaining/-/plugin-proposal-optional-chaining-7.6.0.tgz#e9bf1f9b9ba10c77c033082da75f068389041af8"
You need to update this file by running `yarn install` or `yarn upgrade` to remove the references to our internal npm feed.

2019-09-20 13:47 UTC, dandel10n commented on packages/f-header/src/components/Navigation.vue
> +                        v-if="userInfo"
You don't need this check because parent li element will have display none with `'is-hidden': !userInfo` on line 48

2019-09-20 13:48 UTC, dandel10n commented on packages/f-header/src/components/Navigation.vue
> +                        v-if="userInfo.isAuthenticated"
Should here `userInfo.isAuthenticated` be changed to just `userInfo` as in other places

2019-09-20 13:53 UTC, dandel10n commented on packages/f-header/CHANGELOG.md
> + - Props in `Navigation.vue`
You've added your changes as `v2.0.0-beta-8` which is already published. Should become `v2.0.0-beta-9` now

2019-09-20 13:53 UTC, smilburn1990 commented on packages/f-header/src/components/Navigation.vue
> +            return `${this.accountLogout.url}${this.returnUrl}`;
It was carried over from the current static header in menuweb. To be honest I don't think we need it anymore either. let me get rid of it. @DamianMullins - Was there any particular reason it was used in the current header?

2019-09-20 13:55 UTC, smilburn1990 commented on packages/f-header/CHANGELOG.md
> + - Props in `Navigation.vue`
I have pulled from master and can't see an updated changelog @dandel10n

2019-09-20 14:09 UTC, DamianMullins commented on packages/f-header/src/components/Navigation.vue
> +            return `${this.accountLogout.url}${this.returnUrl}`;
Without it you'll always be redirected back to the homepage after signing in/out rather than the page where you clicked the link.

2019-09-20 14:11 UTC, pikax submitted a review, later dismissed

2019-09-20 14:11 UTC, DamianMullins commented on packages/f-header/src/components/Navigation.vue
> +            return `${this.accountLogout.url}${this.returnUrl}`;
I'm not sure what happens if you don't have vue-router configured though (I'm guessing it'll throw an error), so you'll probably want to add this back in and set the return URL using standard JS techniques.

2019-09-20 14:15 UTC, pikax submitted a review, later dismissed

2019-09-20 14:16 UTC, dandel10n submitted a review, later dismissed

2019-09-20 14:18 UTC, smilburn1990 commented on packages/f-header/src/components/Navigation.vue
> +            return `${this.accountLogout.url}${this.returnUrl}`;
Could you pass `$route` through as a prop? @DamianMullins

2019-09-20 14:22 UTC, smilburn1990 commented on packages/f-header/src/components/Navigation.vue
> +            return `${this.accountLogout.url}${this.returnUrl}`;
Actually won't `$route` be accessible from the component?

2019-09-20 14:33 UTC, pikax submitted a review, later dismissed

2019-09-20 14:33 UTC, DamianMullins commented on packages/f-header/src/components/Navigation.vue
> +            return `${this.accountLogout.url}${this.returnUrl}`;
Not sure, `$route` might be, `$router` won't.

2019-09-20 14:37 UTC, DamianMullins commented on packages/f-header/src/components/Navigation.vue
> +            return `${this.accountLogout.url}${this.returnUrl}`;
Either way, you need the return URL part otherwise you'd have to find your way back to the menu page after logging in (very annoying). 

You should be able to set the value using `document.location.pathname`? Making sure to encode it using `encodeURIComponent` like in the original code.

2019-09-20 14:38 UTC, dandel10n submitted a review, later dismissed

2019-09-23 09:56 UTC, dandel10n approved these changes

2019-09-23 09:57 UTC, pikax approved these changes

2019-09-23 09:59 UTC, merged

2019-09-23 10:14 UTC, zlatinivanov-je commented
Are we happy to have an internal menuweb link in the description?

2019-09-23 10:15 UTC, smilburn1990 commented
@zlatinivanov-je  - No one can access but I have removed anyway

2019-09-23 10:49 UTC, zlatinivanov-je reviewed
Not sure if adding `Axios` and making the auth call here is necessary. I would assume the host app will already use a service(s) to get page data and could provide the necessary to the component.

2019-09-23 10:49 UTC, zlatinivanov-je commented on packages/f-header/src/components/Navigation.vue
> +        returnUrl () {
Can we have the option to provide a return Url value. In our project we have specific requirement for Query string not matching the `document.location.pathname` at all times.

2019-09-23 10:49 UTC, zlatinivanov-je commented on packages/f-header/src/components/Header.vue
> -                :user-info="userInfo"
I liked that approach since my app already has the user info Object available

2019-09-23 10:49 UTC, zlatinivanov-je commented on packages/f-header/src/components/Header.vue
>                  :nav-links="copy.navLinks"
Does it no make sense to have a single `copy` prop to pass, following a convention, instead of so many...

2019-09-23 10:49 UTC, zlatinivanov-je commented on packages/f-header/src/components/Navigation.vue
> +            try {
In my case, the app already does that request in a separate occasion and can provide the object, instead. Duplicate request can be avoided and saves on `Axios` added.

2019-09-23 10:55 UTC, DamianMullins commented
@zlatinivanov-je Menu Web has no awareness of user details so we rely on the `api/account/details` endpoint to provide that. We don't plan on adding the user middleware to Menu Web, it was considered but ultimately we decided against as we wanted the back-end to be as light as possible.

2019-09-23 10:57 UTC, pikax commented
couldn't we use `fetch` and enforce a polyfill if that functionality gets used, IMHO is a bit more elegant than bundle axios.

2019-09-23 11:15 UTC, ashleynolan commented on packages/f-header/src/components/Navigation.vue
> +            try {
Would be good to have the option to pass this in and not make the call if it's present. Think that's a valid use-case (like in Help)

2019-09-23 11:16 UTC, ashleynolan commented
@DamianMullins @zlatinivanov-je We could make this like the locale though, whereby having an optional prop that can accept the user details and would mean the header then doesn't make the call?

2019-09-23 11:31 UTC, zlatinivanov-je commented
@DamianMullins in my case it is not the backend that provides the user data. The app utilises user object for LiveChat, BotChat, and Order Help Automation components. The Vue app is the one that calls the same endpoint `/api/account/details` and has the user object already.

2019-09-23 12:37 UTC, smilburn1990 commented on packages/f-header/src/components/Navigation.vue
> +            try {
@zlatinivanov-je - I did raise this in `guild-ui` meeting last week and have raised it multiple times in other channels. It was a unanimous decision to go with this approach in the end, but I agree with @ashleynolan that we could toggle it off with a prop if the app already has the functionality.

2019-09-23 12:37 UTC, smilburn1990 commented on packages/f-header/src/components/Navigation.vue
> +            try {
@zlatinivanov-je - I did raise this in `guild-ui` meeting last week and have raised it multiple times in other channels. It was a unanimous decision to go with this approach in the end, but I agree with @ashleynolan that we could toggle it off with a prop if the app already has the functionality.

2019-09-23 14:13 UTC, zlatinivanov-je commented on packages/f-header/src/components/Navigation.vue
> +            try {
@smilburn1990 Sorry I was away last week. But I am happy with @ashleynolan's proposal.