f-metadata@v0.1.0 – Initial Setup
justeattakeaway/fozzie-components pull request #57
Opened 2019-09-18 11:10 UTC by cak8

Enabling Braze SDK

2019-09-18 11:22 UTC, simonsandersje commented on packages/f-metadata/package.json
> +  "version": "v1.0.0",
If this is the first commit, we usually start at v0.1.0

2019-09-18 11:37 UTC, dandel10n commented on packages/f-metadata/package.json
> +    "yalc": "^1.0.0-pre.34"
I think we don't need yalc as a package dependency :)

2019-09-18 11:38 UTC, dandel10n commented on packages/f-metadata/src/index.js
> +const intialiseBraze = (apiKey, enableLogging = false) => {
typo _initialize_

2019-09-18 11:39 UTC, dandel10n commented on packages/f-metadata/package-lock.json
> +{
We usually don't commit `package-lock.json` because we use yarn as a rool. So package-lock.json needs to be added to .gitignore

2019-09-18 11:46 UTC, dandel10n commented on packages/f-metadata/package.json
> +    "appboy-web-sdk": "^2.4.0",
This package is in dev dependencies in the monorepo root and here in projects dependencies. If you add a `f-metadata` as a root dependency like [this](https://github.com/justeat/fozzie-components/blob/ccee407abb0018c35c66e68a3d4d018c28126052/package.json#L64-L68) I think you won't need  "appboy-web-sdk" on projects level

2019-09-18 12:32 UTC, ashleynolan reviewed
Could you add a README for how this package is used when it gets pulled in (for example) how it could be included in a project like Home/Menu. Can likely copy the README from one of the other packages and edit it.

2019-09-18 12:32 UTC, ashleynolan commented on package.json
> +    "appboy-web-sdk": "^2.4.0"
Can you remove the `^` to lock the dependency to that version?

2019-09-18 12:32 UTC, ashleynolan commented on packages/f-metadata/CHANGELOG.md
> +*September 10, 2019*
Bump the date 😄

2019-09-19 14:31 UTC, pikax submitted a review, later dismissed

2019-09-19 14:40 UTC, xander-marjoram commented on package.json
> +    "@justeat/f-metadata": "file:packages/f-metadata"
Super nit-picky, but can we keep these alphabetical please?

2019-09-19 14:44 UTC, xander-marjoram commented on packages/f-metadata/README.md
> +    import metadata from '@justeat/f-metadata';
Is this how you're doing it at the moment?

Currently we're exporting just the `initialiseBraze` function from `index.js` rather than an object containing the function, i.e.,
```
export default {
    initialiseBraze
};
```

And then in the SFC you would do `import { initialiseBraze } from '@justeat/f-metadata';`

2019-09-19 14:46 UTC, xander-marjoram commented on yarn.lock
> +yalc@^1.0.0-pre.34:
Please could you try deleting `yarn.lock` and re-running `yarn`? I don't think we need some of these dependencies

2019-09-20 09:27 UTC, tommcclean submitted a review, later dismissed

2019-09-20 09:46 UTC, pikax submitted a review, later dismissed

2019-09-20 10:35 UTC, DamianMullins commented on packages/f-metadata/src/index.js
> +const intialiseBraze = (apiKey, enableLogging = false) => {
Missing "i" — "initialiseBraze"

2019-09-20 10:36 UTC, DamianMullins commented on packages/f-metadata/src/index.js
> +export default intialiseBraze;
To match the instructions in the readme this should be 

```js
export default {
    initialiseBraze
};
```

That way you can do `import { initialiseBraze } from '@justeat/f-metadata';`

2019-09-20 10:54 UTC, tommcclean approved these changes

2019-09-20 11:02 UTC, xander-marjoram approved these changes

2019-09-20 11:02 UTC, merged

2019-09-20 11:03 UTC, pikax requested changes

2019-09-20 11:03 UTC, pikax commented on packages/f-metadata/README.md
> +    You can import it in your Vue SFC like this (please note that styles have to be imported separately):
I don't see any Vue component here, is this correct?

2019-09-20 11:03 UTC, pikax commented on packages/f-metadata/README.md
> +<p>Global Header Component for Vue.js.</p>
Is this copied from: [@justeat/f-header](https://github.com/justeat/fozzie-components/tree/master/packages/f-header)?
Can you have a description, because I have no idea what this package is about :/