f-header@2.0.0-beta.8 accessibility improvements
justeattakeaway/fozzie-components pull request #60
Opened 2019-09-19 15:51 UTC by dandel10n

### Changed
 - Added some accessibility improvements to the navigation component

2019-09-19 15:56 UTC, DamianMullins commented on packages/f-header/src/components/Navigation.vue
> +                        :tabindex="isBelowMid ? '-1' : '0'"
The values can just be numbers rather than strings.

2019-09-19 16:00 UTC, BanksySan requested changes
Just confirm that the whitespace changes are on purpose and not incidental.

2019-09-19 16:00 UTC, BanksySan commented on packages/f-header/src/components/Navigation.vue
> -    <nav
Is this reformatting to bring it inline with the rest of the formatting conventions or is it a mistake?

2019-09-19 16:00 UTC, dandel10n commented on packages/f-header/src/components/Navigation.vue
> +                        :tabindex="isBelowMid ? '-1' : '0'"
✅

2019-09-19 16:06 UTC, dandel10n commented on packages/f-header/src/components/Navigation.vue
> -    <nav
If it is only clean html markup like here that it should be on one line. If there are vue attributes than for better readability it should be splitted onto new lines - it is done by eslint check

2019-09-20 09:41 UTC, BanksySan submitted a review, later dismissed

2019-09-20 09:48 UTC, pikax commented on packages/f-header/src/components/Navigation.vue
> +                <template v-if="isBelowMid">
```suggestion
                <template v-else>
```
`v-if` and `v-else` makes easier to read

2019-09-20 09:49 UTC, pikax commented on packages/f-header/CHANGELOG.md
> +*September 19, 2019*
```suggestion
*September 20, 2019*
```

2019-09-20 09:49 UTC, pikax commented on packages/f-header/src/components/Navigation.vue
> +
NIT: remove space

2019-09-20 09:52 UTC, ashleynolan commented on packages/f-header/CHANGELOG.md
> +*September 19, 2019*
I didn't know you could make code suggestions like this inline…

![Alt Text](https://thumbs.gfycat.com/MaleGlitteringGalapagostortoise-size_restricted.gif)

2019-09-20 10:03 UTC, DamianMullins commented on packages/f-header/src/components/Navigation.vue
> +                <template v-if="isBelowMid">
If you're going to use if/else could you move this block to the top so the if check is against `isBelowMid` and not `!isBelowMid`, please.

2019-09-20 10:16 UTC, pikax submitted a review, later dismissed

2019-09-20 10:19 UTC, dandel10n commented on packages/f-header/src/components/Navigation.vue
> +                <template v-if="isBelowMid">
✅

2019-09-20 10:39 UTC, pikax requested changes

2019-09-20 10:39 UTC, pikax commented on packages/f-header/src/components/Navigation.vue
> +                            v-if="!isBelowMid"
rollback?

2019-09-20 11:14 UTC, dandel10n commented on packages/f-header/src/components/Navigation.vue
> +                            v-if="!isBelowMid"
No, this one is shown only for wider screens and can't be a part of if/else template because here logout link is a part of `c-nav-popoverList` when help is not, and for mobile view they both are inside a dropdown.

2019-09-20 11:16 UTC, DamianMullins approved these changes

2019-09-20 11:24 UTC, pikax commented on packages/f-header/src/components/Navigation.vue
> +                            v-if="!isBelowMid"
My bad, seemed a rollback, sorry about that

2019-09-20 11:25 UTC, pikax approved these changes

2019-09-20 11:25 UTC, merged