f-header@2.0.0-beta.11 - mobile transparent menu styles for open state
justeattakeaway/fozzie-components pull request #61
Opened 2019-09-23 16:03 UTC by dandel10n

### Added
- `no-js` css for mobile hamburger menu

### Changed
- Styling for mobile open menu state header when transparent

[![Image from Gyazo](https://i.gyazo.com/f5a9460c16083e7271ee88f6605b9899.gif)](https://gyazo.com/f5a9460c16083e7271ee88f6605b9899)

2019-09-24 07:09 UTC, pikax requested changes

2019-09-24 07:09 UTC, pikax commented on packages/f-header/src/components/Header.vue
> +        :class="['c-header', { 'c-header--transparent c-header--gradient': isTransparent && !mobileNavIsOpen }]">
moving `isTransparent && !mobileNavIsOpen` to a computed might be a good idea because you're repeating that for a few times in the template

2019-09-24 07:09 UTC, pikax commented on packages/f-header/src/components/Navigation.vue
> +                if (this.justLog.error) {
`justLog` is describe as a function in the props on line 235, please update to an Object and validate if justLog is not `null` or `undefined`

2019-09-24 07:09 UTC, pikax commented on packages/f-header/src/components/Navigation.vue
> +            this.onNavToggle();
is onNavToggle being used elsewhere? Wouldn't be better to drop it, since `onHamburgerMenuClick` is the same as `onNavToggle`

2019-09-24 08:39 UTC, ashleynolan commented on packages/f-header/src/components/Navigation.vue
> +            this.onNavToggle();
I think they're slightly different (might be worth commenting the function tom explain this difference though).

`onNavToggle` applies to all screen widths whereas `onHamburgerClick` is only related to when the hamburger icon shows on mobile. Is that right @dandel10n ?

2019-09-24 08:40 UTC, ashleynolan commented on packages/f-header/src/components/Header.vue
> +        mobileNavToggled (value) {
Would be good to have some comments around these methods (and the functions/methods throughout the `.vue` files).

2019-09-24 08:44 UTC, dandel10n commented on packages/f-header/src/components/Navigation.vue
> +            this.onNavToggle();
@ashleynolan @pikax yes, Ash explained correctly, `onNavToggle` is only for toggling open/closed nav state and `onHamburgerMenuClick` activates onNavToggle and then emits the `onMobileNavToggle` for header components itself only for Hamburger menu click.

2019-09-25 09:53 UTC, pikax submitted a review, later dismissed

2019-09-25 09:59 UTC, pikax submitted a review, later dismissed

2019-09-25 10:34 UTC, pikax approved these changes

2019-09-25 10:35 UTC, simonsandersje approved these changes

2019-09-25 10:36 UTC, merged

2019-09-25 10:37 UTC, ashleynolan commented on packages/f-header/src/components/Header.vue
> +        // to be able to deside when to show transparent header styles on mobile view
Typo – `deside` > `decide`