f-service@2.0.0-beta.4-service-updates-with-tests
justeattakeaway/fozzie-components pull request #62
Opened 2019-09-24 10:16 UTC by smilburn1990

### Changelog

### Added
- Created service package for shared logic
- Tests for the methods inside

### Removed
- Old imports for logic on root

2019-09-24 10:20 UTC, simonsandersje submitted a review, later dismissed

2019-09-24 10:21 UTC, pikax requested changes

2019-09-24 10:21 UTC, pikax commented on packages/f-services/README.md
> +<div align="center">
copy & paste from `f-header`, please improve this file.

2019-09-24 10:21 UTC, pikax commented on packages/f-services/package.json
> +  "version": "v2.0.0-beta.1",
is it v2?

2019-09-24 10:21 UTC, pikax commented on packages/f-services/package.json
> +    "build": "vue-cli-service build --target lib --name f-services ./src/index.js",
is this a vue library?

2019-09-24 10:21 UTC, pikax commented on packages/f-services/src/index.js
> +// Import vue component
not a vue component

2019-09-24 10:21 UTC, pikax commented on yarn.lock
> +    "@justeat/f-services" "file:../Library/Caches/Yarn/v4/npm-@justeat-f-header-2.0.0-beta.9-0468012f-b3f3-4f83-8f1b-8a3980760e6e-1569319556885/node_modules/@justeat/f-header/.yalc/@justeat/f-service
is this correct?

2019-09-24 10:21 UTC, pikax commented on yarn.lock
> +"@justeat/f-services@file:packages/f-header/.yalc/@justeat/f-services":
local files...

2019-09-24 10:31 UTC, smilburn1990 commented on yarn.lock
> +"@justeat/f-services@file:packages/f-header/.yalc/@justeat/f-services":
Need to publish the component first

2019-09-24 11:20 UTC, pikax commented on packages/f-services/CHANGELOG.md
> +0.1.0
the current version is: v2.0.0-beta.1

2019-09-24 12:04 UTC, smilburn1990 commented on packages/f-services/CHANGELOG.md
> +0.1.0
I believe this relates to the fozzie version? Might be wrong but that is what it is like in the meta component which was created recently.

2019-09-24 12:50 UTC, pikax requested changes

2019-09-24 12:50 UTC, pikax commented on packages/f-header/src/components/Navigation.vue
> +                if (this.justLog.error) {
just log has been declared as a function on the prop type, but you're using as an object.

2019-09-24 12:50 UTC, pikax commented on packages/f-services/package.json
> +  "version": "v0.1.0",
remove the `v`

2019-09-24 13:44 UTC, pikax submitted a review, later dismissed

2019-09-25 15:11 UTC, simonsandersje submitted a review, later dismissed

2019-09-25 15:40 UTC, dandel10n requested changes

2019-09-25 15:40 UTC, dandel10n commented on packages/f-header/src/components/Header.vue
>          const theme = sharedService.getTheme(locale);
Should be changed to `sharedServices` here too as on line 66

2019-09-25 15:40 UTC, dandel10n commented on packages/f-services/README.md
> +2.  Import the component
Could we call it a package not a component maybe?

2019-09-25 15:40 UTC, dandel10n commented on packages/f-services/src/index.js
> +// Import vue component
+1

2019-09-26 08:29 UTC, dandel10n approved these changes

2019-09-26 09:18 UTC, simonsandersje approved these changes

2019-09-26 09:23 UTC, merged