Add MoreVertical Icon
justeattakeaway/fozzie-components pull request #683
Opened 2021-02-05 11:57 UTC by nehadhanuka-justeat

__*This is the standard PR description template.*__

__*Delete the parts of this template that aren’t relevant to the current PR you are submitting – for example, you may not need to amend documentation or testing of the component.*__

---

_A short description of your PR goes here. Feel free to copy & paste the CHANGELOG entry that you've added here._

---

## UI Review Checks

![image](https://user-images.githubusercontent.com/805184/35801356-f756b018-0a63-11e8-8ca4-ec045d43c16c.png)

- [ ] README and/or UI Documentation has been [created|updated]
- [ ] Unit tests have been [created|updated]
- [ ] This code has been checked with regard to [our accessibility standards](http://fozzie.just-eat.com/documentation/general/accessibility/checklist)

## Browsers Tested

- [ ] Chrome (latest)
- [ ] Internet Explorer 11
- [ ] Mobile (Please list device/browser – Ideally one iPhone model and one Android)

### List any other browsers that this PR has been tested in:

- [View the Browser Support Checklist](http://fozzie.just-eat.com/documentation/general/browser-support)

2021-02-05 12:28 UTC, ashleynolan requested changes
You'll need to update the `package.json` version of the `f-vue-icons` to `2.4.0` to publish the package.

Also, if you pull in latest master, the bot error you're seeing should disappear when you push that commit (that was fixed yesterday)

2021-02-05 12:28 UTC, ashleynolan commented on packages/tools/f-vue-icons/CHANGELOG.md
> +v2.3.2
Should bump this to `v2.4.0`

2021-02-05 13:28 UTC, ashleynolan submitted a review, later dismissed

2021-02-05 13:30 UTC, FayeCarter submitted a review, later dismissed

2021-02-05 13:31 UTC, kevinrodrigues commented
Missing the yarn.lock file

2021-02-05 14:06 UTC, kevinrodrigues submitted a review, later dismissed

2021-02-05 14:08 UTC, DamianMullins approved these changes, later dismissed

2021-02-05 14:10 UTC, nehadhanuka-justeat commented
Can this be merged pls?

2021-02-05 14:21 UTC, kevinrodrigues commented on yarn.lock
> +  resolved "http://packages.je-labs.com/npm/private-npm/@justeat/f-icons/-/f-icons-3.4.0.tgz#dbdeb97c562926dc1c4b98685b25203a97dbd5ff"
Looks like the build is failing because of the private npm reference.

2021-02-05 16:20 UTC, nehadhanuka-justeat commented
The build error is UnAuthorized - any idea why so?

2021-02-08 14:39 UTC, ashleynolan approved these changes

2021-02-08 14:41 UTC, simonsandersje approved these changes

2021-02-08 15:01 UTC, merged