f-button@v0.8.0 - Extend f-button to include icon
justeattakeaway/fozzie-components pull request #692
Opened 2021-02-08 15:42 UTC by nehadhanuka-justeat

Add isIcon prop to f-button

- [ ] README and/or UI Documentation has been [created|updated]
- [ ] Unit tests have been [created|updated]
- [ ] This code has been checked with regard to [our accessibility standards](http://fozzie.just-eat.com/documentation/general/accessibility/checklist)

## Browsers Tested

- [ ] Chrome (latest)
- [ ] Internet Explorer 11
- [ ] Mobile (Please list device/browser – Ideally one iPhone model and one Android)

### List any other browsers that this PR has been tested in:

- [View the Browser Support Checklist](http://fozzie.just-eat.com/documentation/general/browser-support)

2021-02-08 16:13 UTC, ashleynolan commented on packages/components/atoms/f-button/CHANGELOG.md
> +- Added styles to display the icons properly if button is ddisplayed as an icon
```suggestion
- Added styles to display the icons properly if button is displayed as an icon
```

2021-02-08 17:43 UTC, ashleynolan requested changes

2021-02-08 17:43 UTC, ashleynolan commented on packages/components/atoms/f-button/src/components/Button.vue
> +            (isIcon ? $style['o-icon'] : '')
I would change this to be a modifier of the base button component. Then you can chain selectors for the size as well (I'll put that comment below to show how I think that would work)

```suggestion
            (isIcon ? $style['o-btn--icon'] : '')
```

2021-02-08 17:43 UTC, ashleynolan commented on packages/components/atoms/f-button/src/components/Button.vue
> +                $style[`o-btn--size${buttonSizeClassname}`]),
I would leave this as it was, and just use the modifier to change the width of the btn 

```suggestion
            $style[`o-btn--size${buttonSizeClassname}`],
```

2021-02-08 17:43 UTC, ashleynolan commented on packages/components/atoms/f-button/src/components/Button.vue
> +.o-icon {
```suggestion
.o-btn--icon {
```

2021-02-08 17:43 UTC, ashleynolan commented on packages/components/atoms/f-button/src/components/Button.vue
> +}
If you chain the modifiers then you can just do this:

```suggestion

     &.c-btn--sizeSmall {
        width: $icon-sizeSmall-width;
    }

    &.o-btn-sizeLarge {
        width: $icon-sizeLarge-width;
    }
}
```

2021-02-09 09:09 UTC, dandel10n requested changes
Could you please add an example where this is needed. At the moment we already use  buttonType='icon' property for buttons like close button with only cross icon, arrow button etc

2021-02-09 09:59 UTC, nehadhanuka-justeat commented
> Could you please add an example where this is needed. At the moment we already use buttonType='icon' property for buttons like close button with only cross icon, arrow button etc

We want some icon buttons (like MoreVertical icon) in the new page being developed for RestaurantPartners for PromotedPlacement(https://justeattakeaway.atlassian.net/browse/PP-4835)

2021-02-09 10:15 UTC, ashleynolan commented
@dandel10n This change will make the icon button more inline with the PIE designs, as the icon button needs to be able to use the different types of button available (primary/secondary/outline and ghost) and the way it's implemented atm this isn't possible. I'll be putting in a PR to remove the old `buttonType="icon"` once this change gets merged and we'll look to update this in any components currently using this method.

2021-02-10 12:45 UTC, nehadhanuka-justeat commented
closing this one as again having issues with the branch from the forked repository - it is not updating the PR with the commits on the branch so have made another [PR](https://github.com/justeat/fozzie-components/pull/702) without using forked repo branch

2021-02-10 12:45 UTC, closed without merging