f-footer@2.0.0-beta.23-add-new-services
justeattakeaway/fozzie-components pull request #72
Opened 2019-09-30 15:37 UTC by smilburn1990

2019-10-01 08:56 UTC, pikax commented on yarn.lock
> +"@justeat/f-footer@file:packages/f-footer":
local packages

2019-10-01 09:36 UTC, ashleynolan commented on yarn.lock
> +"@justeat/f-footer@file:packages/f-footer":
Yep – this is a yalc link I think? Will need to be removed

2019-10-01 09:37 UTC, ashleynolan requested changes
Looks good – just needs the changes @pikax suggested

2019-10-08 12:54 UTC, simonsandersje submitted a review, later dismissed

2019-10-08 12:56 UTC, pikax commented on packages/f-footer/CHANGELOG.md
> +*September 30, 2019*
```suggestion
*October 8, 2019*
```

2019-10-08 12:57 UTC, InsungMulumba submitted a review, later dismissed

2019-10-08 13:01 UTC, pikax submitted a review, later dismissed

2019-10-08 13:05 UTC, InsungMulumba submitted a review, later dismissed

2019-10-08 13:09 UTC, SachaZvetelman commented on packages/f-footer/src/components/LinkList.vue
> +            this.currentScreenWidth = sharedServices.getWindowHeight();
Shouldn't this be `getWindowWidth?`

2019-10-08 13:14 UTC, pikax commented on packages/f-header/src/tenants/it-IT.js
> +            text: 'Credito dell',
is this intentional?

2019-10-08 13:17 UTC, smilburn1990 commented on packages/f-header/src/tenants/it-IT.js
> +            text: 'Credito dell',
Yep. Added to change log

2019-10-08 13:22 UTC, SachaZvetelman approved these changes

2019-10-08 13:29 UTC, InsungMulumba approved these changes

2019-10-08 13:35 UTC, ashleynolan approved these changes

2019-10-08 13:35 UTC, kevinrodrigues commented on packages/f-footer/src/components/LinkList.vue
> +import sharedServices from '@justeat/f-services';
Would it not be better to just pull out the methods you require here then use them directly below without having to reference the variable name?

`import { getWindowWidth, removeEvent, addEvent} from '@justeat/f-services'`

2019-10-08 13:36 UTC, merged

2019-10-08 13:37 UTC, smilburn1990 commented on packages/f-footer/src/components/LinkList.vue
> +import sharedServices from '@justeat/f-services';
@kevinrodrigues - Will add in the next PR. This is blocking me atm