Updated error-message, mega-modal and tabs with component tests. #trivial
justeattakeaway/fozzie-components pull request #765
Opened 2021-03-03 10:09 UTC by JoshuaNg2332

f-error-message - v0.3.2
------------------------------
*March 3, 2021*

### Added
- Added component test file and tests

f-mega-modal - v0.4.1
------------------------------
*March 3, 2021*

### Added
- Added component test file, component object file and tests
- Added `Data-test-id` to elements within the `MegaModal.stories.js`

f-tabs - v0.2.2
------------------------------
*March 3, 2021*

### Added
- Added component tests
- Added supporting code to component object file

### Changed
- `Data-test-id` naming for `tab-` to `tab-button-` in `Tabs.vue`
- `Data-test-id` naming for `transition-tab-` to `tab-content-` in `Tab.vue`

2021-03-03 10:13 UTC, kevinrodrigues approved these changes, later dismissed

2021-03-03 10:39 UTC, siggerzz commented on packages/components/atoms/f-error-message/CHANGELOG.md
> +v0.3.2
Should this be 0.4.0 - We only increment the 3rd digit if it's a bug fix 👍🏼

2021-03-03 10:40 UTC, siggerzz commented on packages/components/atoms/f-error-message/package.json
> +  "version": "0.3.2",
Change to 0.4.0

2021-03-03 10:40 UTC, siggerzz commented on packages/components/molecules/f-mega-modal/CHANGELOG.md
> +v0.4.1
Change to 0.5.0

2021-03-03 10:40 UTC, siggerzz commented on packages/components/molecules/f-mega-modal/package.json
> +  "version": "0.4.1",
Change to 0.5.0

2021-03-03 10:41 UTC, siggerzz commented on packages/components/molecules/f-tabs/CHANGELOG.md
> +v0.2.2
Change to 0.3.0

2021-03-03 10:41 UTC, siggerzz commented on packages/components/molecules/f-tabs/package.json
> +  "version": "0.2.2",
Change to 0.3.0

2021-03-03 10:42 UTC, siggerzz requested changes
Looking good! Just a few minor comments around the version numbers 🎉

2021-03-03 11:36 UTC, DamianMullins approved these changes, later dismissed

2021-03-03 16:34 UTC, siggerzz approved these changes

2021-03-04 08:02 UTC, FayeCarter approved these changes

2021-03-04 10:01 UTC, merged