f-checkout@v0.110.0 - Display correct error message when mobile number field is empty
justeattakeaway/fozzie-components pull request #944
Opened 2021-05-11 14:45 UTC by 1itvinka

### Changed
- Display 'Please enter your phone number' when the mobile number field is empty, and invalid phone message when the field is invalid but not empty

2021-05-11 15:00 UTC, siggerzz commented
@1itvinka Is it possible to add a visual regression test for the invalid phone number error?

I'm happy to pair on it with you if needed 👍🏼

2021-05-12 14:02 UTC, dandel10n submitted a review, later dismissed
I have no experience with percy tests but everything else looks good. A pr needs an approve from one of our testers as well

2021-05-12 16:05 UTC, JoshuaNg2332 submitted a review, later dismissed

2021-05-13 08:19 UTC, siggerzz commented on packages/components/organisms/f-checkout/test/component/f-checkout-delivery.component.desktop.spec.js
> +
These tests can be deleted as we've got the visual regression tests

2021-05-13 08:20 UTC, siggerzz commented on packages/components/organisms/f-checkout/test-utils/component-objects/f-checkout.component.js
> +            get error () { return $(FIELDS.mobileNumber.error); },
Change to `get emptyError () { return $(FIELDS.mobileNumber.emptyError); },`

2021-05-13 08:20 UTC, siggerzz requested changes
A few minor comments, but looks good!

2021-05-13 15:22 UTC, dandel10n approved these changes

2021-05-13 15:37 UTC, siggerzz approved these changes

2021-05-13 15:38 UTC, merged