fozzie-components@v3.34.0 - Added additional circleci cli tasks
justeattakeaway/fozzie-components pull request #984
Opened 2021-05-24 15:41 UTC by JoshuaNg2332

v3.34.0
------------------------------
*May 24, 2021*

## Added
- CircleCI config for running `build`, `lint` & `unit testing` steps individually locally.
- Documentation into storybook guides as to how to run these tests through CircleCI CLI locally and what each task is setup to do.

2021-05-25 08:49 UTC, LTurns submitted a review, later dismissed

2021-05-27 10:32 UTC, LTurns approved these changes, later dismissed

2021-05-27 13:07 UTC, siggerzz commented on .vscode/tasks.json
>          "label": "CircleCI CLI",
Rename this to `CircleCI Complete Build`

2021-05-27 13:08 UTC, siggerzz commented on .vscode/tasks.json
> +        "label": "CircleCI Unit Tests",
Rename to `CircleCI Unit + Integration Tests`

2021-05-27 13:08 UTC, siggerzz commented on CHANGELOG.md
> +v3.35.0
This will need to be 3.36

2021-05-27 13:08 UTC, siggerzz commented on stories/guides/circlieci-cli.stories.mdx
> +`CircleCI CLI` - Full CircleCI workflow
Make sure to update the name here too

2021-05-27 13:08 UTC, siggerzz requested changes
Few minor comments, but looking good!

2021-05-27 15:48 UTC, LTurns submitted a review, later dismissed

2021-05-27 16:01 UTC, siggerzz commented on stories/guides/circlieci-cli.stories.mdx
> +`CircleCI Unit` - Build and unit testing steps of the CircleCI workflow
Update the build name here to be `CircleCI Unit + Integration` - The description also needs to be updated, as this doesn't do a build.

2021-05-27 16:01 UTC, siggerzz requested changes
Minor comments

2021-05-27 16:39 UTC, JoshuaNg2332 commented on stories/guides/circlieci-cli.stories.mdx
> +`CircleCI Unit` - Build and unit testing steps of the CircleCI workflow
Updated this. But we need to build for some unit tests to pass.

2021-05-28 08:59 UTC, siggerzz approved these changes, later dismissed

2021-05-28 09:28 UTC, LTurns submitted a review, later dismissed

2021-05-28 14:45 UTC, siggerzz approved these changes

2021-05-28 14:47 UTC, LTurns approved these changes

2021-05-28 14:48 UTC, merged